### ISSUE TITLE
Email not verified by clicking verification link

### ISSUE THREAD

**Issue by robindijkhof** [RocketChat/Rocket.Chat#10149]
### Description:

After clicking the verification link the user is redirected to the login page. When the user tries to login it gets a message saying the user is not found or the password is incorrect. When checking as admin, the user is still unverified.

### Server Setup Information:

* Server Setup Information:
* Version of Rocket.Chat Server: 0.62.2
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): Manual install
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 8.9.4

### Steps to Reproduce:

1. Configure SMTP (test it)
2. Enable verification under Email -> verification
3. Enable verification under Accounts -> Email verification
4. Create a user.
5. Click the verification link in the email.

### Expected behavior:

Email should be verified

### Actual behavior:

Email isn't verified

### Relevant logs:

`[34mI20180315-11:14:42.564(0) [34mMeteor ➔ publish null -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.570(0) Exception while invoking method 'verifyEmail' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: emails.$.verified     at Function.MongoError.create (/home/otm-admin/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/home/otm-admin/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /home/otm-admin/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /home/otm-admin/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)  
[34mI20180315-11:14:42.570(0) [34mMeteor ➔ publish roles -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.571(0) [34mMeteor ➔ publish stream-importers -> userId: null , arguments:  { '0': 'progress', '1': { useCollection: false, args: [] } } 
[34mI20180315-11:14:42.572(0) [34mMeteor ➔ publish meteor_autoupdate_clientVersions -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.575(0) [34mMeteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'updateCustomSound',   '1': { useCollection: false, args: [] } } 
[34mI20180315-11:14:42.576(0) [34mMeteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'deleteCustomSound',   '1': { useCollection: false, args: [] } } 
[34mI20180315-11:14:42.577(0) [34mMeteor ➔ publish activeUsers -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.578(0) [34mMeteor ➔ publish userData -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.579(0) [34mMeteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'public-settings-changed',   '1': { useCollection: false, args: [] } } 
[34mI20180315-11:14:42.587(0) [34mMeteor ➔ method autoTranslate.getSupportedLanguages -> userId: null , arguments:  { '0': 'en' } 
[34mI20180315-11:14:42.590(0) [34mMeteor ➔ method listCustomSounds -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.591(0) [34mMeteor ➔ method listEmojiCustom -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.594(0) [34mMeteor ➔ method apps/is-enabled -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.595(0) [34mMeteor ➔ method permissions/get -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.597(0) [34mMeteor ➔ method public-settings/get -> userId: null , arguments:  {} 
[34mI20180315-11:14:42.622(0) [34mMeteor ➔ method UserPresence:online -> userId: null , arguments:  { '0': null } 
[34mI20180315-11:14:42.624(0) [34mMeteor ➔ method loadLocale -> userId: null , arguments:  { '0': 'nl' } 
[34mI20180315-11:14:42.852(0) [34mMeteor ➔ method permissions/get -> userId: null , arguments:  { '0': 2018-03-15T11:14:42.650Z } 
[34mI20180315-11:14:42.973(0) [34mMeteor ➔ method public-settings/get -> userId: null , arguments:  { '0': 2018-03-15T11:14:42.818Z } `

**Comment by robindijkhof** [comment]
Workaround for now is to fill in the password forgotten form.

**Comment by tranduyhung** [comment]
I just installed Rocket.chat via Docker and got the same issue.

```
Rocket.Chat Version: 0.62.2
NodeJS Version: 8.9.3 - x64
Platform: linux
Process Port: 3001
ReplicaSet OpLog: Disabled
Commit Hash: 07f0e3f77c
Commit Branch: HEAD     
```

**Comment by lightweight** [comment]
I'm seeing this, too, after upgrading to 0.62.2 from 0.61.4 - note, on mongo pinned to 3.4 because a previous upgrade of all my Docker containers (using docker-compose) that moved mongo beyond 3.4 failed...

**Comment by sergeydeg** [comment]
Me to.
Rct: 0.62.2
Node: v8.9.3
MongoDB: 3.6

**Comment by HammyHavoc** [comment]
Yep, seeing this too.

**Comment by AntMarras** [comment]
me too 
 rocket chat version: 0.62.2

**Comment by PavelZhe** [comment]
me too
Rocket 0.62.2
Node 8.9.3
MongoDB 2.6.12
CentOS 7

**Comment by theorenck** [comment]
Hi @robindijkhof, thanks let us know of the problem.

**Comment by Hudell** [comment]
Anybody still seeing this problem on version 0.63? If so, please share any more relevant logs you may have.

**Comment by geraldinkorea** [comment]
I have the same issue please let me know what logs you would like to see.

**Comment by daradurvs** [comment]
I have the same issue on v.0.63.1
SMTP is configured and tests email is sent as expected.
But I got an error `Error trying to send email:  Mail command failed` by clicking **"Resend verification email"** in **"My Account"** tab.
There is no warning in **"View Logs"**.

**Comment by geraldinkorea** [comment]
Thank you,

My error logs in send mail are sparse, there is no error.


Cheers,

Gerald

**Comment by SignalDancer** [comment]
@Hudell  Same issue here on 63.1

If there's further logs you need than what's in the rocket chat main log, let me know and I will get them.

**Comment by Hudell** [comment]
Anybody had this problem with any version prior to 0.62.2?

And do all of you have the setting  "Manually Approve New Users" set to true, or it happens with that setting set to false too?

**Comment by simopaasisalo** [comment]
On our server new users have been able to verify their emails without issues, but previously we had this issue. Unfortunately I don't know what changed, I just remember being surprised that new users could sign in without me interfering.
Version 0.63.0
Mongo 3.4

**Comment by himbeere** [comment]
Bug still present in 0.64.0-rc3.

**Comment by axis78** [comment]
@Hudell 

Have this problem on 0.62.1
"Manually Approve New Users"  set to false

**Comment by daradurvs** [comment]
Hi, my issue has been resolved after RocketChate had been updated via Snap to v.0.63.3
**"Resend verification email"** button in **"My Account"** tab works well now.
Thanks!

**Comment by himbeere** [comment]
*Sending* the verification mail is not the problem for me. Clicking on the link send by it is.

**Comment by JonCup** [comment]
Same here. I get an error when I click on the link in the email.

**Comment by tosione** [comment]
Still happening in 0.64.1. The symptoms are like #10548: you get error 500 when clicking verify link, emails remains unverified, but the error message is the same.

**Comment by tarator** [comment]
Same here on a fresh install (docker) Version 0.65.1

    rocket_1  | Exception while invoking method 'verifyEmail' MongoError: The positional operator did not find the match needed from the query.
    rocket_1  |     at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    rocket_1  |     at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
    rocket_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
    rocket_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    rocket_1  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
    rocket_1  |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by tarator** [comment]
Maybe there is something wrong with the link in the mail itself. My mailserver is also complaining, that there is no From-Header set in the mail (other notification mails from rocketchat work correctly (see Header `X-Amavis-Alert`.

Anonymised RAW-Email sent by rocketchat instance:

    Return-Path: <>
    Delivered-To: georg@example.com
    Received: from somesome.myserver.com
            by somesome.myserver.com (Dovecot) with LMTP id xxxsdfwhoh23hca
            for <georg@example.com>; Wed, 13 Jun 2018 20:07:34 +0200
    X-Quarantine-ID: <46gserhsvjl7895>
    Authentication-Results: somesome.myserver.com; dkim=permerror (bad message/signature format)
    X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "From"
    Content-Type: multipart/alternative;
    boundary="--_NmP-ed7fe0d1de64cadd-Part_1"
    To: georg@example.com
    Subject: How to verify email address on Rocket.Chat
    Message-ID: <93102c9c-xxxx-xxx-0bb2-asfjwhjkhgh2g2hfph2>
    Date: Wed, 13 Jun 2018 18:07:34 +0000
    MIME-Version: 1.0

    ----_NmP-ed7fe0d1de64cadd-Part_1
    Content-Type: text/plain
    Content-Transfer-Encoding: quoted-printable

    Hello,

    To verify your account email, simply click the link below.

    https://rocket.myserver.com/#/verify-email/xxxxxxxsnxAASojqiHiUX=
    BznUZZxxxxxx

    Thanks.

    ----_NmP-ed7fe0d1de64cadd-Part_1
    Content-Type: text/html
    Content-Transfer-Encoding: quoted-printable

    Hello,

    To verify your account email, simply click the link below.

    https://rocket.myserver.com/login/#/verify-email/xxxxxxxsnxAASoj=
    qiHiUXBznUZZxxxxxx

    Thanks.

    ----_NmP-ed7fe0d1de64cadd-Part_1--

Maybe this helps.

**Comment by tarator** [comment]
**I think I found the problem**: It's the `=` sign in the verification link.
Some mail-clients use this sign as a line-break.

They transform the link which should be 
`https://rocket.myserver.com/login/#/verify-email/xxxxxxxsnxAASoj=qiHiUXBznUZZxxxxxx`

into the following link:

`https://rocket.myserver.com/login/#/verify-email/xxxxxxxsnxAASojqiHiUXBznUZZxxxxxx`

which breaks it.

**Comment by Hudell** [comment]
Hey @tarator, Glad you figured that out! It doesn't seem to be the same bug that the others are having, but I'll look into it.

**Comment by ronnicek** [comment]
Have same problem here.

Rocketchat version: 0.66.0 (docker image rocketchat/rocket.chat:latest)

```
rocketchat_1  | Exception while invoking method 'verifyEmail' MongoError: The positional operator did not find the match needed from the query.
rocketchat_1  |     at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
rocketchat_1  |     at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
rocketchat_1  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
rocketchat_1  |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by PhilGPk** [comment]
What's the most useful thing end-users can do to help fix this?  It's a show-stopper for a potential deployment for me.

**Comment by Hudell** [comment]
If you click on the same link multiple times, do you get the same error again?

**Comment by tarator** [comment]
I just tried it again with the latest version 0.66.1. E-Mail Verification now works on my inscance of Rocketchat.
Can anybody else confirm this?

**Comment by przemika** [comment]
YES! It works also in my instance. I just upgraded it to 0.66.2

**Comment by ronnicek** [comment]
Upgraded too to 0.66.2 and its working (but had to use :latest from docker hub, because 0.66.1 nor 0.66.2 is not there yet..)

**Comment by pcmerc** [comment]
Upgraded from 0.66.0 > 0.66.3. Email verification is now working as expected.

**Comment by Hudell** [comment]
Looks like it was fixed by #11335

**Comment by pcmerc** [comment]
I do have OpLog disabled currently

**Comment by PhilGPk** [comment]
Confirmed, email verification now works as expected in 0.66.3.
I have OpLog disabled.

**Comment by Hudell** [comment]
I'll close this issue then, as #11335 fixed the issue. If anybody still runs into it, just leave a comment and I'll reopen it.
