### ISSUE TITLE
File Uploads Blurred

### ISSUE THREAD

**Issue by Stabatha** [RocketChat/Rocket.Chat#10959]
### Description:

All images are blurred uploading them to a chatroom or direct message.

### Server Setup Information:

* Version of Rocket.Chat Server:   0.65.0
* Operating System:   CentOS 7.4
* Deployment Method(snap/docker/tar/etc):  Manual @ /opt
* Number of Running Instances:  1
* Node Version:  8.9.3
* mongoDB Version:  2.6.12

### Steps to Reproduce:

Attach image from computer

### Expected behavior:

upload the image

### Actual behavior:

uploaded image is blurred.

![capture](https://user-images.githubusercontent.com/112463/40763811-dbe4418a-646b-11e8-9dfd-bacde719c956.PNG)

**Comment by vynmera** [comment]
Please update to 0.65.1, it should be fixed there.

**Comment by Stabatha** [comment]
Thanks!  will try now.

**Comment by Stabatha** [comment]
Yeap, fixed, thanks!   I'll go ahead and close this incident report now.

**Comment by cloudsandladders** [comment]
Version of Rocket.Chat Server: 0.65.1
Operating System: Ubuntu 16.04
Deployment Method(snap/docker/tar/etc): Snap
Number of Running Instances: 1
Node Version: 8.9.3
mongoDB Version: 2.6.12

On desktop and browser, I am still having this issue, even with the new version, but it only happens on very large images (ie. 6000x4000).

In addition to being blurred, large photos do not scale down and therefore take up the entire page now.

If you click on the download button for the upload, the image becomes clear, but is still enormous (full resolution) inside rocket chat.

Can we open this back up?
