### ISSUE TITLE
Duplicate key error

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#1227]
While doing my import from Slack I ran into this issue and it occurred several times.
```
I20151023-13:17:25.417(-5)? Exception in defer callback: MongoError: E11000 duplicate key error index: rocketchat.rocketchat_oembed_cache.$_id_ dup key: { : "https://rocket.chat/" }
I20151023-13:17:25.417(-5)?     at Object.Future.wait (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
I20151023-13:17:25.418(-5)?     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
I20151023-13:17:25.418(-5)?     at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
I20151023-13:17:25.418(-5)?     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:586:1)
I20151023-13:17:25.418(-5)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
I20151023-13:17:25.418(-5)?     at _Class.RocketChat.models._Base._Class.insert (packages/rocketchat_lib/server/models/_Base.coffee:17:24)
I20151023-13:17:25.418(-5)?     at _Class.RocketChat.models.OEmbedCache._Class.createWithIdAndData (packages/rocketchat_oembed/server/models/OEmbedCache.coffee:21:17)
I20151023-13:17:25.418(-5)?     at Object.OEmbed.getUrlMetaWithCache (packages/rocketchat_oembed/server/server.coffee:152:33)
I20151023-13:17:25.419(-5)?     at OEmbed.RocketUrlParser (packages/rocketchat_oembed/server/server.coffee:182:18)
I20151023-13:17:25.419(-5)?     at packages/rocketchat_lib/lib/callbacks.coffee:65:4
I20151023-13:17:25.419(-5)?     - - - - -
I20151023-13:17:25.419(-5)?     at Object.toError (C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\utils.js:114:11)
I20151023-13:17:25.419(-5)?     at C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\collection\core.js:116:29
I20151023-13:17:25.419(-5)?     at C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\db.js:1197:7
I20151023-13:17:25.419(-5)?     at C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\db.js:1905:9
I20151023-13:17:25.419(-5)?     at Server.Base._callHandler (C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\connection\base.js:453:41)
I20151023-13:17:25.420(-5)?     at C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\connection\server.js:488:18
I20151023-13:17:25.420(-5)?     at [object Object].MongoReply.parseBody (C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
I20151023-13:17:25.420(-5)?     at [object Object].<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\connection\server.js:446:20)
I20151023-13:17:25.420(-5)?     at [object Object].emit (events.js:95:17)
I20151023-13:17:25.420(-5)?     at [object Object].<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\npm-mongo\1.4.39_1\npm\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:207:13)
```

**Comment by geekgonecrazy** [comment]
Interesting... I wonder is this error happening every time someone posts a link that has already been sent before?

**Comment by graywolf336** [comment]
I'm not sure myself, just happens quite a bit when doing my import and
sending messages to let it run the full course.

**Comment by geekgonecrazy** [comment]
Find anything more out about this?

**Comment by graywolf336** [comment]
I have not, when I run the import again I will see if I can find any clues as to why this is happening.

**Comment by graywolf336** [comment]
Update: So, this seems to only occur when my import script is run. Basically the import script is going through all the messages and running the full message process on each message. Sometimes the messages contain the same url as the one right before it and since the OEmbed getting of url meta is "async", both of those messages cause the oembed to fire off and both of them to run the creating in the database about the same time which then causes the check for existing one to not succeed and the create to happen on both of them.

Hopefully that makes more sense.

**Comment by graywolf336** [comment]
```
I20151029-22:55:20.193(-5)? Parsing url: http://www.twitch.tv/sreolla
I20151029-22:55:20.216(-5)? Parsing url: http://www.twitch.tv/sreolla
```
That's the timestamps when the urls are parsed (I added custom logging to track this down), notice the less than 30 milliseconds time difference.
```
I20151029-22:55:21.241(-5)? Exception in defer callback: MongoError: E11000 duplicate key error index: rocketchat.rocketchat_oembed_cache.$_id_ dup key: { : "http://www.twitch.tv/sreolla" }
```
Then a full second later (plus some milliseconds) the response for both of them come back and they both try to create the data into the database.

**Comment by georgiosd** [comment]
We've seen this error on a live system on a call to `sendMessage` - can this actually make the application unresponsive? It would load the chat room but clicking on a room would do nothing - it got "unstuck" after a while.

```
Exception while invoking method 'sendMessage' MongoError: E11000 duplicate key error index: Web_Production.rocketchat_message.$_id_ dup key: { : "sjwkpPfZie8TSj85T" }
    at Object.Future.wait (/var/Web.Production/1.0.0.45/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:736:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
    at _Class.RocketChat.models._Base._Class.insert (packages/rocketchat_lib/server/models/_Base.coffee:17:24)
    at Object.RocketChat.sendMessage (packages/rocketchat_lib/server/functions/sendMessage.coffee:27:44)
    at [object Object].Meteor.methods.sendMessage (packages/rocketchat_lib/server/methods/sendMessage.coffee:18:14)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo 

...
```

**Comment by graywolf336** [comment]
@georgiosd No, I believe it is a passive error. The "unstuck" is sometimes the channels do take a while to load, I believe #1537 will help with that issue but it might still happen.

To fix the issue reported here, we need to change how the current code is currently handling this to take make simultaneous calls out to the same url within the time it takes for that url to load.

**Comment by graywolf336** [comment]
Closing due to a change by @rodrigok: https://github.com/RocketChat/Rocket.Chat/pull/3123/commits/db7283a6b935afecbb90a6ebda7a0671671e150b

**Comment by rvion** [comment]
just got this error too while importing my stack log

```shell
OEmbed duplicated record https://docs.google.com/forms/d/e/xxxxxxxxx/viewform
Exception in callback of async function: RangeError: Invalid array buffer length
  at new ArrayBuffer (native)
  at new Uint8Array (native)
  at createBuffer (buffer.js:25:17)
  at allocate (buffer.js:166:12)
  at new Buffer (buffer.js:56:12)
  at read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:788:38)
  at GridStore.read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:775:44)
  at GridReadStream._push (/app/bundle/programs/server/npm/node_modules/meteor/jalik_ufs-gridfs/node_modules/gridfs-stream/lib/readstream.js:181:17)
  at GridReadStream._read (/app/bundle/programs/server/npm/node_modules/meteor/jalik_ufs-gridfs/node_modules/gridfs-stream/lib/readstream.js:156:8)
  at GridReadStream.Readable.read (_stream_readable.js:336:10)
  at readableAddChunk (_stream_readable.js:154:18)
  at GridReadStream.Readable.push (_stream_readable.js:111:10)
  at /app/bundle/programs/server/npm/node_modules/meteor/jalik_ufs-gridfs/node_modules/gridfs-stream/lib/readstream.js:190:28
  at read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:801:12)
  at GridStore.read (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:775:44)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:817:12
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs/grid_store.js:1197:5
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:95:56)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1405:5
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:95:56)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor.js:674:5
  at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:171:5)
  at nextFunction (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:683:5)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:594:7
  at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:253:5)
  at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickDomainCallback (node.js:406:13)
```

I just deployed rocket.chat today with docker so it used latest images

**Comment by rvion** [comment]
@graywolf336 @georgiosd I can't seem to recover from the issue, everything seems to be locked, and restarting containers doesn't work.

Do you have any advice regarding how to proceeed?

**Comment by himbeere** [comment]
Hello Devs.

Got this error too. 

```
Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error index: rocketchat.rocketchat_subscription.$u._id
_1_name_1_t_1_code_1 dup key:
```

Happend after deleting a user who had a direct message conversation.

**Comment by FF-Ibb-PD** [comment]
Same Problem here.
When my user try to open a direct message they will get an error like "user not found"

Logging out and on again helps, but the message will appear quiet often.

when i did my last database import I got some index-error and doing db.repairDatabase() didn't solve that.

Any Idea?

Log:
> Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "uuFymgYbuKJFwqwRJ", : "Aeriko.", : "d", : null }   at Object.Future.wait (/snap/rocketchat-server/653/node_modules/fibers/future.js:449:15)   at [object Object].<anonymous> (packages/meteor.js:213:24)   at [object Object].MongoConnection.(anonymous function) [as update] (/snap/rocketchat-server/653/programs/server/packages/mongo.js:836:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/snap/rocketchat-server/653/programs/server/packages/mongo.js:3899:31)   at ModelsBaseDb.update (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:9640:32)   at ModelsBaseDb.upsert (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:9715:16)   at ModelSubscriptions.upsert (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:4192:36)   at [object Object].Meteor.methods.createDirectMessage (/snap/rocketchat-server/653/programs/server/app/app.js:6142:35)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:1021:26)   at maybeAuditArgumentChecks (/snap/rocketchat-server/653/programs/server/packages/ddp-server.js:1823:12)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/653/programs/server/packages/ddp-server.js:876:21)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:755:85      - - - - -   at Function.MongoError.create (/snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67   at /snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:489:9)   at process._tickDomainCallback (node.js:459:13)  

Version 0.56.0
Database migration 93
Node version 4.8.2

**Comment by ArchimedesFM** [comment]
Same Problem here. Occured after deleting an old local rocket.chat user and reimporting it via LDAP.
I can write a direct message to katharina.schmidt while others get the message "User not found".

[34mI20170628-08:20:03.254(2) Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "QwhRFRbzvAA6hHXFa", : "katharina.schmidt", : "d", : null }   at Object.Future.wait (/snap/rocketchat-server/653/node_modules/fibers/future.js:449:15)   at [object Object].<anonymous> (packages/meteor.js:213:24)   at [object Object].MongoConnection.(anonymous function) [as update] (/snap/rocketchat-server/653/programs/server/packages/mongo.js:836:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/snap/rocketchat-server/653/programs/server/packages/mongo.js:3899:31)   at ModelsBaseDb.update (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:9640:32)   at ModelsBaseDb.upsert (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:9715:16)   at ModelSubscriptions.upsert (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:4192:36)   at [object Object].Meteor.methods.createDirectMessage (/snap/rocketchat-server/653/programs/server/app/app.js:6142:35)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:1021:26)   at maybeAuditArgumentChecks (/snap/rocketchat-server/653/programs/server/packages/ddp-server.js:1823:12)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/653/programs/server/packages/ddp-server.js:876:21)   at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:755:85      - - - - -   at Function.MongoError.create (/snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67   at /snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:489:9)   at process._tickDomainCallback (node.js:459:13)

**Comment by geekgonecrazy** [comment]
@ArchimedesFM yours sounds like you might want to open a new issue.  Sounds like some conflict and merge logic may need some work on the ldap sync

**Comment by alokraj68** [comment]
![image](https://user-images.githubusercontent.com/9208731/118622702-3173d280-b7e5-11eb-94bc-7d6a42f5e23b.png)

Cannot use the slack bridge and import messages.
