### ISSUE TITLE
cannot create integration (incoming webhook)

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#13061]
### Description:

Hi Devs. I'm unable to create a specific incoming webhook. Error message is "invalid channel". The channel i choose to send the messages too is #noc. The channel exists *and* there is even another integration which posts to this channel. This is rather confusing to me. Choosing #noc-notify works. Any idea whats going on here? I set the log to debug but no messages.

Strange thing is i tested this on another server and there it works flawlessly.

### Steps to reproduce:

1. Create incoming webhook
2. Choose channel to post to
3. Get error "invalid channel"

### Expected behavior:

Incoming webhooks gets created.

### Actual behavior:

"invalid channel" message appears.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8.12
- MongoDB Version: 3.6

**Comment by libussa** [comment]
same here.
for me it works on an old channel, but if I try using a new one it fails with "invalid channel"

**Comment by himpierre** [comment]
I just made an observation. If i write something to the channel in question first, the creation of the incoming webhooks succeeds. But it has to be me. If someone else writes to that channel the problem persists.

**Comment by knrt10** [comment]
On it, will try to fix this.

**Comment by knrt10** [comment]
@himpierre I think this issue is fixed in latest release `1.0.0-develop`. Give it a try. If your issue is similar to #13103 then as you can on [line77](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.js#L77), you have to set both `manage-own-integrations` and `manage-integrations`. Once you do that your user will be able to add webhook on his/her own username or any other. Please do give a try. If it works, feel free to close this issue. Thanks. 👍

**Comment by himpierre** [comment]
@knrt10 Thanks. I give it a shot as soon as 1.0.0-rc0 arrives.

**Comment by knrt10** [comment]
@himpierre beta 1.0.0 is here, do try it. Thanks 👍

**Comment by himpierre** [comment]
Yeah, would love to. :-) But there seems to be no binary release at the moment. 

cheers
t.

**Comment by eloo-at-abi** [comment]
@knrt10 
Hi, i've tried the rc1 and rc2 of 1.0.0 and i cant create incoming webhooks at all.
When i'm clicking on new webhook and Incoming WebHook nothing happens.. only the text changes from `New Integration` to `Incoming WebHook Integration` on top of the page.. but i can still see the incoming webhook and outgoing webhook buttons :/

**Comment by knrt10** [comment]
@eloo-at-abi sorry for the late response. I tried on the latest `1.0.0-develop` code it is working fine. Would you please specify the exact version. Also if running locally, please rebase the code and try again.

**Comment by knrt10** [comment]
@himpierre binary release for `1.0.0-rc.3` is out

**Comment by eloo-at-abi** [comment]
@knrt10 looks goot in 1.0.0-rc.3 for me 👍

**Comment by himpierre** [comment]
Yes. Seems to be working again. Thanks @knrt10 :-) ---> closing issue.
