### ISSUE TITLE
Error 401 (you must be logged in) in some endpoints

### ISSUE THREAD

**Issue by facundomedica** [RocketChat/Rocket.Chat#13340]
/api/v1/commands.list

### Description:

In the web UI (of a self hosted server) I have errors 401 in endpoints `/api/v1/commands.list` and `/api/apps`. And sometimes using the rest api when creating a new user with an admin user (this is solved by relogging, but it's quite erratic and can't replicate it whenever I want, just like https://github.com/RocketChat/Rocket.Chat/issues/10792)

The `/api/apps` endpoint error prevents me from installing apps.

### Steps to reproduce:

1. Go to the web ui and login.
2. Go to Administration>Apps
3. Check the console

### Expected behavior:

That this endpoints work as expected

### Actual behavior:

Errors in console show up and functionality is limited.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.9

### Relevant logs:

SERVER:

```
Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
```

Chrome Console:

```
/rocketchat/api/v1/commands.list:1 Failed to load resource: the server responded with a status of 401 ()
79fee541c97bbd76940588ee2c027b4994fbd142.js:235 Uncaught (in promise) Error
    at Object.e [as error] (79fee541c97bbd76940588ee2c027b4994fbd142.js:235)
    at l (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at Object.fireWith [as rejectWith] (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at w (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at XMLHttpRequest.<anonymous> (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
e @ 79fee541c97bbd76940588ee2c027b4994fbd142.js:235
l @ 79fee541c97bbd76940588ee2c027b4994fbd142.js:5
fireWith @ 79fee541c97bbd76940588ee2c027b4994fbd142.js:5
w @ 79fee541c97bbd76940588ee2c027b4994fbd142.js:5
(anonymous) @ 79fee541c97bbd76940588ee2c027b4994fbd142.js:5
79fee541c97bbd76940588ee2c027b4994fbd142.js:433 Loading: true
/rocketchat/tap-i18n/es.json:1 Failed to load resource: the server responded with a status of 503 ()
/rocketchat/api/apps:1 Failed to load resource: the server responded with a status of 401 ()
79fee541c97bbd76940588ee2c027b4994fbd142.js:235 Uncaught (in promise) Error
    at Object.e [as error] (79fee541c97bbd76940588ee2c027b4994fbd142.js:235)
    at l (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at Object.fireWith [as rejectWith] (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at w (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at XMLHttpRequest.<anonymous> (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
/rocketchat/api/apps:1 Failed to load resource: the server responded with a status of 401 ()
79fee541c97bbd76940588ee2c027b4994fbd142.js:433 err Error
    at Object.e [as error] (79fee541c97bbd76940588ee2c027b4994fbd142.js:235)
    at l (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at Object.fireWith [as rejectWith] (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at w (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
    at XMLHttpRequest.<anonymous> (79fee541c97bbd76940588ee2c027b4994fbd142.js:5)
click .js-install @ 79fee541c97bbd76940588ee2c027b4994fbd142.js:433

```

**Comment by frdmn** [comment]
Just a hunch, but could this be related to the [DDP rate limiter issue](https://github.com/RocketChat/Rocket.Chat/issues/13329)?

If so, disabling the affected settings (`DDP_Rate_Limit_IP_Enabled`, `DDP_Rate_Limit_User_Enabled`, `DDP_Rate_Limit_Connection_Enabled`, `DDP_Rate_Limit_User_By_Method_Enabled` and `DDP_Rate_Limit_Connection_By_Method_Enabled` to `false`) should help as a temporary workaroound for this. You can either use the REST API or set them [directly via environment variables](https://rocket.chat/docs/administrator-guides/settings-via-env-vars/).

**Comment by facundomedica** [comment]
@frdmn in that issue it says that it happens for the first admin but I've tried with 2 admin accounts. Anyway I'll give it a go. Setting those env variables to empty strings is enough right?

**Comment by frdmn** [comment]
@facundomedica You mentioned that "it's quite erratic and can't replicate it whenever I want" - that made me think about the rate limiter. Anyways, might be worth a try to see if it's related to this.
 
Oh and by the way: If you still have access to the regular admin UI, you can of course use that to set those as well: 

<img width="1530" alt="screenshot 2019-02-04 at 17 24 46" src="https://user-images.githubusercontent.com/944459/52221601-cb781100-28a1-11e9-81e2-b945245895ce.png">

**Comment by facundomedica** [comment]
@frdmn I've changed that, I'll let you know if the error when creating user disappears. In the meanwhile, can you check the 401 errors in commands.list and apps?

**Comment by MarcosSpessatto** [comment]
@facundomedica can you please share with us the calls that you are making against API and receiving this errors?

**Comment by facundomedica** [comment]
@MarcosSpessatto how would you like me to share that? I mean, in which format or how do I get them? They are `/api/v1/commands.list` and `/api/apps` in the web UI. And using the REST API as an admin I get that error in `users.create`.

**Comment by MarcosSpessatto** [comment]
@facundomedica are you running this server behind a proxy like Nginx?

**Comment by facundomedica** [comment]
@MarcosSpessatto I'm running it inside Kubernetes with Istio and accesing it by a subdirectory. This shouldn't be an issue, as I can do almost anything that Nginx can do (I think).
I have a couple of rewrites already:

```
    - match:
        - uri:
            prefix: /rocketchat/rocketchat/
        - uri:
            prefix: /rocketchat/
      rewrite:
        uri: /rocketchat/
```

This `/rocketchat/rocketchat/` is there because I couldn't make the thumbnails work correctly.

**Comment by wargamesqcf** [comment]
When trying to do oauth I am getting "internal server error" with this in the logs, but my DDP rate limiter is turned off.

Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by vitstradal** [comment]
I have similar behavior. When going directry to rocket.chat (localhost:65065) everything is ok. When going through apache reverse proxy `401 Unauthorized` is returned to `/app/v1/command.list`. Difference is, that request  through apache does not contain headers `X-Users-Id`, `X-Auth-Token`.

**Comment by MarcosSpessatto** [comment]
I opened [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13553) that fix this `loginAt` errors, I think this should fix the problem.

**Comment by facundomedica** [comment]
@MarcosSpessatto thank you! Do we have a ETA?

**Comment by vitstradal** [comment]
After some investigation I found this: 
when I have application with `ROOT_URL=http://127.0.0.1/chat`
Auth token is stored to LocalSession under key `Meteor.loginToken:/:/chat` (in meteor `_initLocalStorage` in [packages/accounts-base/accounts_client.js](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_client.js#L524))

BUT, when command `commans.list` is called, it calls `APIClient.v1.get` in ([packages/rocketchat-utils/client/lib/RestApiClient.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-utils/client/lib/RestApiClient.js#L41)), it calls `_jqueryCall`, where header `X-Auth-Token` is created from local sesion key `Meteror.loginTogen` (not `Metheor.localToken:/:/chat`):

```
                                headers: {
                                        'Content-Type': 'application/json',
                                        'X-User-Id': localStorage['Meteor.userId'],
                                        'X-Auth-Token': localStorage['Meteor.loginToken'],
                                },


```
BTW: This not only one place when `Meteor.KEY` is used directly.

**Comment by facundomedica** [comment]
@MarcosSpessatto I've just tried 1.0.0-beta.2 and this issue isn't solved

**Comment by facundomedica** [comment]
@MarcosSpessatto I have an specific case. Calling:

```
curl -H "X-Auth-Token: 123123-mytoken"      -H "X-User-Id: 6GsxZq8v47q4Wtest"      https://example.com/rocketchat/api/v1/commands.list
```

works, but the same call in my browser fails. There is no cookie nor auth token sent to the server.

![Screen Shot 2019-03-25 at 20 35 33](https://user-images.githubusercontent.com/14063057/54952370-b9c7f700-4f3d-11e9-8df5-4e131eb25db5.png)

**Comment by MarcosSpessatto** [comment]
@facundomedica sorry for the long delay. I'll take a look on this again.

**Comment by MarcosSpessatto** [comment]
@facundomedica what is the status of the response? Feel free to DM if you want (https://open.rocket.chat/direct/marcos.defendi), maybe it could be more efficient.
