### ISSUE TITLE
Livechat broken on latest develop

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#13717]
### Description:

Live chat no longer works on the latest develop version, and the log complains about missing assets.

### Steps to reproduce:

1. Get latest docker develop version.
2. Attempt to navigate to the livechat page: https://mychat.com/livechat
3. The page will error out (I run it behind a reverse-proxy so I get 502 Bad gateway).

### Expected behavior:
The public-facing livechat interface should show.

### Actual behavior:
There is an error page. Log records the following:
```
Exception in callback of async function: Error: Unknown asset: public/head.html,
    at getAsset (/app/bundle/programs/server/boot.js:329:19),
    at Object.getText (/app/bundle/programs/server/boot.js:340:16),
    at WebApp.connectHandlers.use.Meteor.bindEnvironment (app/livechat/server/livechat.js:30:22),
    at runWithEnvironment (packages/meteor.js:1356:24),
    at packages/meteor.js:1369:14,
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40,
```

### Rocket.Chat

| Version                 | 1.0.0-develop                                             |
| ----------------------- | --------------------------------------------------------- |
| Apps Engine Version     | 1.4.0                                                     |
| Database Migration      | 138                                                       |
| Database Migration Date | Thu Mar 14 2019 12:15:22 GMT-0500 (Central Daylight Time) |
| Installed at            | Tue Jul 03 2018 10:28:32 GMT-0500 (Central Daylight Time) |
| Uptime                  | 30 seconds                                                |
| Deployment ID           | **********                                         |
| PID                     | 8                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | d5c57d1778492ea0bc7e5dd4a3906ad2d2b6ffbf |
| ------- | ---------------------------------------- |
| Date    | Thu Mar 14 10:41:25 2019 -0300           |
| Branch  | develop                                  |
| Tag     | 0.74.2                                   |
| Author  | Diego Sampaio                            |
| Subject | Add Houston config (#13707)              |

### Runtime Environment

| OS Type         | Linux                 |
| --------------- | --------------------- |
| OS Platform     | linux                 |
| OS Arch         | x64                   |
| OS Release      | 4.15.0-46-generic     |
| Node Version    | v8.11.4               |
| OS Uptime       | 6 minutes, 48 seconds |
| OS Load Average | 2.33, 3.31, 1.92      |
| OS Total Memory | 7.79 GB               |
| OS Free Memory  | 537.86 MB             |
| OS CPU Count    | 4                     |

### Build Environment

| OS Platform  | linux                  |
| ------------ | ---------------------- |
| OS Arch      | x64                    |
| OS Release   | 4.4.0-141-generic      |
| Node Version | v8.11.4                |
| Date         | March 14, 2019 8:45 AM |

**Comment by bkraul** [comment]
Thanks to the develop images archive I set up 😜 , I can confirm that livechat last worked fine on commit 44d84927613d85f66745795365d9056d704d8f58 .

There have been 2 builds since that commit, so something must have changed there.

**Comment by renatobecker** [comment]
Fixed here -> https://github.com/RocketChat/Rocket.Chat/pull/13723

**Comment by bkraul** [comment]
OK so I must have missed something about this. The PR says that the livechat client is provided now as a "Community Feature", but that the "2" will be maintained for a while.

What does this mean? From the looks the snipped the only thing changing is the `?version=1.0` at the end of the URL. Could you please explain a little, @renatobecker ? My apologies if this has been explained before.

Better yet, if there is a documentation URL I can check for this, that would be great!

**Comment by reetp** [comment]
Same here.

Tried the 'modified' script which throws the error as well.

```
<script type="text/javascript">
(function(w, d, s, u) {
    w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = [];
    w.RocketChat.url = u;
    var h = d.getElementsByTagName(s)[0],
        j = d.createElement(s);
    j.async = true;
    j.src = 'https://chat.mydomain.net/livechat/1.0/rocketchat-livechat.min.js?_=201903270000';
    h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://chat.mydomain.net/livechat?version=1.0');
</script>

```

**Comment by bkraul** [comment]
Same here. Even with `?version=1.0` it is still broken. I am still trying to understand what "community feature" means. Is it not bundled with RocketChat anymore?

**Comment by renatobecker** [comment]
> OK so I must have missed something about this. The PR says that the livechat client is provided now as a "Community Feature", but that the "2" will be maintained for a while.
> 
> What does this mean? From the looks the snippet the only thing changing is the `?version=1.0` at the end of the URL. Could you please explain a little, @renatobecker ? My apologies if this has been explained before.
> 
> Better yet, if there is a documentation URL I can check for this, that would be great!

Hi @bkraul, You're still getting the error because the PR wasn't merged yet.
The reason for the error is because we have made some structural changes on the codebase/packages and it has impacted on Livechat plugin.
But, since you're running the `develop` branch, this is a kind of situation that may happen.

Related to the `Community Feature` stuff, it means that we will start providing our new Livechat solution(https://github.com/RocketChat/Rocket.Chat.Livechat) as a `Community Feature`, so please review the Javascript Snippet again, you'll see that the `j.src` has been changed as well.

Thanks.

**Comment by bkraul** [comment]
@renatobecker Thanks for the reply. Again I still do not understand what the term `Community Feature` really means but that's OK. I understand that running the develop branch will sometimes incur in some issues. As specified, I was able to go back to the latest build without the error. I will switch to a new image when the PR is merged and built.

**Comment by tassoevan** [comment]
@bkraul
> Again I still do not understand what the term Community Feature really means but that's OK.

We ran a beta testing with Enterprise customers.
