### ISSUE TITLE
Add notes in settings that require a restart

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1492]
Many settings require restarting rocket.chat.  We need to make note of these changes.
- [x] File Upload->Accepted Media Types #1460
- [ ] Push notification settings [code]
- [x] `Administration > Accounts > Avatar > Avatar Storage Type` - #3020 

@RocketChat/core do we have others?  This would probably make a good set of tasks for someone new that wants to contribute.  I know there are more.  :)

**Comment by marceloschmidt** [comment]
In this specific case (accepted media types), are you sure a server restart is required? Isn't just the client that needs to refresh the browser?

**Comment by geekgonecrazy** [comment]
@marceloschmidt i'm not completely sure.  It seemed to be with this and also #1304 that a server restart was all that solved it.

**Comment by marceloschmidt** [comment]
I'll give it a try later on, but as far as I remember, the accepted media types is only used for building a `<input type="file" accept="{{accepted_media_types}}">` tag. So if the client re-renders it, it would correctly fetch the information... but that's my best guess, I'll give it proper testing later on.

**Comment by geekgonecrazy** [comment]
@marceloschmidt that sounds right.  I think there are a few others like this, otherwise I wouldn't have bothered to create a list.  Now I just have to remember the other ones lol

**Comment by engelgabriel** [comment]
If we find settings that require a restart, let's try to fix this before making a note about it. I don't think any settings should require a restart.

**Comment by sampaiodiego** [comment]
Settings related to MAIL_URL seems needs a restart

**Comment by engelgabriel** [comment]
OK, but it can and should be fixed.

**Comment by sampaiodiego** [comment]
need a real test.. but looking at [source code](https://github.com/RocketChat/Rocket.Chat/blob/develop/server%2Flib%2Fcordova.coffee) seems like push notification settings needs a restart too

**Comment by mitar** [comment]
BTW, you can make server-side automatically restart itself by calling `process.exit(0)` on the server side.

**Comment by marceloschmidt** [comment]
As per #3020 it looks like changing Storage Type needs a restart as well

**Comment by sampaiodiego** [comment]
Just the avatar storage type @marceloschmidt ;)
the file upload storage type doesn't need a restart

**Comment by Rohlik** [comment]
I think this is solved, so we can close this.

**Comment by geekgonecrazy** [comment]
@Rohlik I believe so.  I'll go ahead and close @marceloschmidt / @sampaiodiego let me know if closing in error :)

**Comment by sampaiodiego** [comment]
We still need a restart for Push notification settings.

**Comment by geekgonecrazy** [comment]
@sampaiodiego ah right... we don't have a note there telling them a reboot is needed.  Re-opening..

**Comment by robertwessen** [comment]
any update here? spent waaaayyy too long trying to figure out what was wrong with my push settings, since i could toggle them and things were still broken. Finally out of desperation tried a reboot and then settings worked? Then searched and found this issue... @sampaiodiego @geekgonecrazy
