### ISSUE TITLE
Channel permalinks don't work when not logged-out

### ISSUE THREAD

**Issue by 2color** [RocketChat/Rocket.Chat#15583]
### Description:

When opening a channel permalink, e.g. https://aragon.chat/channel/dev the page hangs on the loading animation. 

This is not a problem when you're logged in. 

Of course, when simply going to https://aragon.chat/ the chat works and the channel can be selected.

This bug isn't unique to us. I noticed it also for https://basicattentiontoken.rocket.chat/channel/brave-browser.

### Steps to reproduce:

1. Go to https://aragon.chat/channel/dev

### Expected behavior:

Channel loading

### Actual behavior:

Loading animation

No apparent errors in the console. 

### Server Setup Information:

- Version of Rocket.Chat Server: `1.3.1`
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: `docker.io/bitnami/mongodb:4.0.12-debian-9-r5`

**Comment by reetp** [comment]
This is most likely due to your proxy or server configuration.

Please test on https://open.rocket.chat

Redirects to the login page perfectly there, and on both my instances.

**Comment by 2color** [comment]
I think there might have been a misunderstanding.

We have `Allow Anonymous Read` enabled so when opening Go to `https://aragon.chat/channel/[ANYCHANNELNAME]` it doesn't work. But if you go home without logging in you can navigate to the channel and it will load.

**Comment by reetp** [comment]
> We have `Allow Anonymous Read` enabled so when opening Go to `https://aragon.chat/channel/[ANYCHANNELNAME]` it doesn't work. But if you go home without logging in you can navigate to the channel and it will load.

Ahhh. That sort of little detail can make a big difference......

Have you tested this on latest - things may well have been fixed already so you need to test.

https://rocketchat.github.io/docs/contributing/reporting-issues/

> Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

OK, so you don't have to update, but you can easily spin up a test VM to check this sport of thing.

**Comment by eliotb** [comment]
I'm seeing this issue on  Version 2.3.1
BTW the title of this issue should be "... not logged IN"

**Comment by eliotb** [comment]
Note. This is the same as #15391

**Comment by andreirtaylor** [comment]
I see this in 2.4.0 as well. You are also unable to read replies/discussions directly by clicking on them.

**Comment by ryjones** [comment]
I also tested it on the latest bits. Can confirm, still broken.

**Comment by ryjones** [comment]
This is not fixed in 3.0.0

**Comment by jorpiell** [comment]
Still not fixed in 3.0.3

**Comment by herget** [comment]
Just tested it on the latest version and still not fixed in 3.0.4.

Does someone know a fork where this is fixed?

**Comment by Sing-Li** [comment]
@engelgabriel   -  fast track candidate

**Comment by ewaldbenes** [comment]
I've just tested it with `master` and it works like a charm. I couldn't see if the "accidental" :D fix was introduced in `3.0.5` or `3.0.6`.

Anyway awesome and thanks a lot folks!

**Comment by geekgonecrazy** [comment]
Could any of the others that had it broke on 3.x also try and confirm with the latest patch?  That would be great if it was

**Comment by ewaldbenes** [comment]
To my surprise I was a little fast in saying that it works because I was so excited about it :P. Sorry about that!

It works in the dev environment using `meteor run`. Later I upgraded the Digital Ocean One Click droplet to version `3.0.6` and it didn't work. Maybe someone else could crosscheck this behavior.

I really love **Rocket.Chat**. Nonetheless, since we want to use it for public chats where people not necessarily should have an account to (at least) read chats and channels are precreated and based on location, this bug renders the use of it pretty much impossible.

**Comment by kulla** [comment]
We updated the RocketChat we use at our project to `3.1.1` and now direct links to channels work fine :tada: Have a look at https://community.serlo.org/channel/general Thank's for fixing it :smile:

**Comment by herget** [comment]
Awesome. Just tested and it works with the latest version now 👍

**Comment by ryjones** [comment]
@ggazzo same as #15391 ?

**Comment by ryjones** [comment]
I can verify this is bug is fixed in 3.3.0, at least.
