### ISSUE TITLE
Can't access the custom Secret Registration URL

### ISSUE THREAD

**Issue by ravimallya** [RocketChat/Rocket.Chat#1585]
I created a custom Secret for registration page, and the URL can't be accessible by others. This is the app statistics.
![image](https://cloud.githubusercontent.com/assets/2795843/11626029/784b1a66-9d05-11e5-962b-9467377f7342.png)
 
This is the app settings page:
![image](https://cloud.githubusercontent.com/assets/2795843/11626056/b783aab8-9d05-11e5-9fe4-3dff9773e655.png)

This is the error Message which I received at: http://localhost:3000/register/TmEcrgm6a34YSCuNM

![image](https://cloud.githubusercontent.com/assets/2795843/11626099/1a188a54-9d06-11e5-8807-ea68ad257999.png)

How it can be fixed? Please advice.

**Comment by marceloschmidt** [comment]
Can you confirm what version of Rocket.Chat you're using? You can do it by opening your developer console and typing `RocketChat.Info`. Thanks.

**Comment by ravimallya** [comment]
Sure. 
Here you go:
{version: "0.7.0", compile: Object, commit: Object, tag: "v0.7", branch: "develop"}branch: "develop"commit: Objectcompile: Objecttag: "v0.7"version: "0.7.0"__proto__: Object

Thanks for the quick reply.

**Comment by marceloschmidt** [comment]
We've fixed a problem with secret URL on commit https://github.com/RocketChat/Rocket.Chat/commit/527ffac1fd38728a29b7cae4b77e41b08bf0ecc5. Can you try and pull our latest changes and see if it fixes for you? Thanks.

**Comment by ravimallya** [comment]
Sure. I'll update you on this ASAP. BTW, we're new to meteor and Git. So just doing git again and re-run meteor to get update?

Thanks again.

**Comment by marceloschmidt** [comment]
You'll do a `git pull` for updating the codebase. Then you can run meteor again.

**Comment by ravimallya** [comment]
The issue still exists. Did a `git pull` and then meteor. You can also check the error at: http://206.80.45.80:3000/register/TmEcrgm6a34YSCuNM . I didn't change the secret hash.

**Comment by marceloschmidt** [comment]
I can access that registration form.
Can you clear cache and try again?
![image](https://cloud.githubusercontent.com/assets/1986378/11626788/a61fc7cc-9ccc-11e5-9b0c-4f2300c4a358.png)

**Comment by ravimallya** [comment]
Yes. Now the issue fixed. Thanks a lot for fast reply and fix. Closing. Thanks again @marceloschmidt

**Comment by marceloschmidt** [comment]
Cool! I'm glad I could help!

**Comment by ravimallya** [comment]
@marceloschmidt , can you edit your previous post and remove the image please? I also changed the domain from IP to localhost. It's for security purposes. Thanks.

**Comment by marceloschmidt** [comment]
Sure! 
:)
