### ISSUE TITLE
Nextcloud & Rocketchat integration

### ISSUE THREAD

**Issue by Sys-Admin889** [RocketChat/Rocket.Chat#16963]
Hello everyone,

I’m trying to integrate Nextcloud v17.0.3 & Rocketchat v2.4.11, both of them installed on Ubuntu 18.04 LTS by snap.

Configuration configured on Nextcloud server:
1- External user authentication App has been downloaded and enabled from this path 
     /settings/apps/integration.
2- The bellow section already added to /nextcloud/config/config.php as the
     following [instructions](https://github.com/nextcloud/user_external#readme).
     ‘user_backends’ => array(
     array(
     ‘class’ => ‘\OCA\User_External\WebDAVAuth’,
     ‘arguments’ => array(‘https://192.168.1.9/webdav’),
      ), ),
3- Get the WebDav url: https://192.168.1.9/remote.php/dav/files/administrator/ 

Configuration configured on Rocketchat server:
1- Going into Administration -> Webdav Integration and set the Webdav Integration Enabled 
     setting to true.
2- Fill all needed information as follwing.
     
![08d1502ee9a30a353c179281b9ccb6bbdfc95bf7](https://user-images.githubusercontent.com/59320357/77237872-8792b900-6bd4-11ea-8546-11202ea105eb.jpeg)
     Is the user name and password entered are the same that I use to login Nextcloud with?

   3- There is an error message appears at the top right of the screen, how can it
        corrected?
  
![Capture2](https://user-images.githubusercontent.com/59320357/77237965-24eded00-6bd5-11ea-930f-610b05ae73cf.JPG)

Also the error message inside logging is here:
![Capture](https://user-images.githubusercontent.com/59320357/77237970-30d9af00-6bd5-11ea-84ad-a644c6ffedaa.JPG)

**Comment by danger89** [comment]
If you want to connect Nextcloud to Rocketchat for logging in reasons. You should create a App in nextcloud and don't use WebDAV. WebDav is for calenders and stuff.

Within Nextcloud go to Admin panel -> Security.

Like: https://your-nextcloud-server.com/settings/admin/security

Then.. At the **bottom** of the page. Create a new 'app' for your Oauth validation.

Use something like this:

![image](https://user-images.githubusercontent.com/628926/77374668-a1b2cf80-6d6b-11ea-85ab-3bcb05b5639f.png)

Redirect should be: https://your-rocketchat-domain.com/_oauth/nextcloud

The tokens and all can be entered in The Rocketchat admin panel -> Oauth.

**Comment by brtptrs** [comment]
We also see this error, using the Webdav Integration with Nextcloud to share files in conversations. We don't use it for Logging-in.

**Comment by gabriellsh** [comment]
Is this settled? Could you make it work with the suggestions above?

**Comment by brtptrs** [comment]
No, for us not. Adding Nextcloud server as shown in the screenshot used to work. But does not any more.

![grafik](https://user-images.githubusercontent.com/8102905/77577578-57e6f800-6ed7-11ea-9849-7e1ba500f41b.png)

**Comment by brtptrs** [comment]
This is the feature we are referring to:

https://rocket.chat/docs/administrator-guides/integrations/nextcloud-and-webdav/

**Comment by Sys-Admin889** [comment]
@brtptrs Exactly.

**Comment by User35123** [comment]
> This is the feature we are referring to:
> 
> https://rocket.chat/docs/administrator-guides/integrations/nextcloud-and-webdav/

Also does not work for me! Rocket.Chat 3.0.12 installed. I only get "Could not access WebDAV" within a second. Absolutlely no logs in the Log. I also use Nextcloud. Access to the Nextcloud WebDAV works from other systems.

**Comment by Sys-Admin889** [comment]
There is no one to help!

**Comment by User35123** [comment]
i fixed this problem for me. But im not sure if you having the same problem. I couldn't see anything in the logs about this problem. it was just trail and error. 

I needed to add the **full certificate chain** to the ssl-certificate on the nextcloud server. i never did that because all my windows clients doesn't have a problem with that. but Linux does. After adding the full chain everything works.

**Comment by brtptrs** [comment]
I've just tested this on 3.6.3 and it still seems to be broken.

**Comment by kokotko1337** [comment]
> full certificate chain

Not working for me even with your solution

**Comment by adymitruk** [comment]
still broken here. no useful error provided

**Comment by wokawoka** [comment]
Any news on that? Is the problem still affecting the current versions? (I'm interested in integrating nextcloud with rocketchat)
Thank you!

**Comment by poltrian** [comment]
Same here, can connect, see my Files and get popups with "too many requests"

**Comment by dougfabris** [comment]
This issue was fixed in this PR #23924, introduced in the version `4.3.0`
I'll close this one because I can't reproduce it anymore, if you guys still have problems after trying it, please let me know!
