### ISSUE TITLE
S3 File upload fails silently

### ISSUE THREAD

**Issue by ndroo** [RocketChat/Rocket.Chat#17235]
Using Rocket.Chat 3.0.10

Issue:

Upload an image (using Amazon S3 as the storage engine). Uploads to 100%, bounces back to 0%...stays there forever. Nothing useful in the logs.

Demonstration of the bug below.

https://imgur.com/a/8TQXRl1

Image used in this demonstration is below:

![IMG_4859](https://user-images.githubusercontent.com/709085/78909313-5417b180-7a51-11ea-836a-8f994d52f2c2.jpeg)

**Comment by dimm0** [comment]
Same here

**Comment by ndroo** [comment]
I figured this out.

In the setup guide they have us install nginx, but nginx by default has a limit on the max file upload. 

To correct this, in the http section of /etc/nginx/nginx.conf you need to set the client_max_body_size to something more substantial.

I've set ours to 100M

`http {
        client_max_body_size 100M;
...`

The issue is now resolved on our side.

**Comment by dimm0** [comment]
Still broken for me, and it worked fine in the previous version
