### ISSUE TITLE
[BUG] Push notifications not send for current user if mobile notifications preference set to Mentions

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17689]
### Description:
https://forums.rocket.chat/t/push-notifications-non-consistent-for-current-user/7000
I have a strange problem with my user receive push notification.
In past I successfully tested push notification on my single android smartphone in 2 different apps. My test user send me a message, and if my main user was offline or away I got push notification almost immediately. But starting from version 4.6 I think it stopped working.
Push notifications for my user work in general - I get push notification from other users or chats (but I think not every)
So I have a very strange problem with notifications. I hoped, that 4.7 will fix that, but no luck, still same behavior.
Is there **some settings** or **MongoDB collection to check** or clean to fix that?
When I press button **Admin UI - Push - Send a test push to my user** - I get push immediately. And i see **Your push was sent to 1 devices**
image
My mobile notification preferences is set to **Mentions**

I did change my mobile notification preference to **All messages (Default)** and all push notifications start come to me.
It’s a definitely a bug.
I need mobile notifications set to **Mentions** not to get a lot of messaged from all of chat where I participate.
I need push for:
- DM
- Threat I started or answered
- When someone mentions me with @ sign
And as I know, Mentions options in mobile notifications preferences is fit me perfectly.

### Steps to reproduce:

1. Set mobile notification preference to **Mentions**
2. Ask someone to send you a message
3. Do not get push

### Expected behavior:

When set mobile notification preference to **Mentions** get push only for:
- DM
- Threat I started or answered
- When someone mentions me with **@** sign

### Actual behavior:

No push notifications received when mobile notification preference set to **Mentions**

### Server Setup Information

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17
- Proxy: nginx
- Firewalls involved: -

### Relevant logs:
Logs for push notifications are off on server, because in general that function works great (iOS a little bit stable and faster)

### Client Setup Information

- Mobile App: 4.7.0
- Operating System: Android 10

**Comment by ankar84** [comment]
Issue is still exist

**Comment by ankar84** [comment]
Still an issue in 3.6.3

**Comment by ankar84** [comment]
@sampaiodiego and I noticed that when I set push notifications to **Mentions** - all my chat list in a Sidebar was updated - no private groups, only DMs on top (a have sort by activity).
It's really easy reproducible.

**Comment by sampaiodiego** [comment]
> @sampaiodiego and I noticed that when I set push notifications to **Mentions** - all my chat list in a Sidebar was updated - no private groups, only DMs on top (a have sort by activity).
> It's really easy reproducible.

interesting, but definitely a different issue.

on the main issue, I find it very weird. I personally use **Mentions** as my push notification preference and it works as expected. are you sure the issue isn't related to your mobile device being in standby (fixed by https://github.com/RocketChat/Rocket.Chat/pull/19061 ) ?

**Comment by ankar84** [comment]
> are you sure the issue isn't related to your mobile device being in standby (fixed by #19061 ) ?

I'm sure it's not related any doze mode or something.
Jist set push to mention and no push to DM
Set to all messages and push works again

**Comment by ankar84** [comment]
Hey, @sampaiodiego 
**Just checked at 4.8.2 server version and 4.29 mobile version.**
https://github.com/RocketChat/Rocket.Chat/issues/17844 still an issue!
I set both Desktop and Mobile notification to Mentions and push stop working on regular messages in DM (mention still works).
But then I set Desktop notification to Default (All Messages) and Mobile is still on Mentions then I get push on regular message!
So, I'm closing this issue and still waiting for a fix of #17844
