### ISSUE TITLE
quotes in hyperlinks aren't displayed correctly

### ISSUE THREAD

**Issue by j0nm1** [RocketChat/Rocket.Chat#17688]
### Description:

When trying to send a message that contains a single quote (`'`) in a hyperlink, the quote does get replaced by `&#39;`. Double quotes (`"`) are also affected by this (replaced by  `&quot;`).

I'm not sure whether this is a standard of Markdown but Visual Studio Code & StackEdit allow those - so it seems to me that this is indeed a bug in RocketChat.

### Steps to reproduce:

Send a message with `['google'](https://google.com)`

### Expected behavior:

The message should like this: `'google'`

### Actual behavior:

The message looks like this: `&#39;google&#39;`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Browser (Chrome  81.0.4044.138 & Firefox 76.0.1)
- Operating System: Windows

**Comment by gabriellsh** [comment]
I think it's solved by https://github.com/RocketChat/Rocket.Chat/pull/16481

**Comment by j0nm1** [comment]
I can't test this right now but it looks related.

**Comment by MartinSchoeler** [comment]
It seems to be working fine now 

![image](https://user-images.githubusercontent.com/20868078/88396869-826b9380-cd99-11ea-83f4-c4ba10c910d3.png)

Please reopen this if you are still facing the issue. Thanks!

**Comment by LeeThompson** [comment]
Still seeing this.

RocketChat: 3.5.0

![rocket_17688](https://user-images.githubusercontent.com/1982261/89077858-fc6ec000-d337-11ea-95b0-2d2460f2521d.png)
