### ISSUE TITLE
[Bug] No DM Notifications when both Desktop and Mobile Preferences is set to Mentions 

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17844]
### Description:

I already found some issue with Notification set to Mentions in #17689
But now we did all tests and can tell for sure, that there is a bug - **No DM Notifications when both Desktop and Mobile Preferences is set to Mentions** 

### Steps to reproduce:

1. User1 set **Show Desktop Notifications For** to **Mentions**
2. User1 set **Push Mobile Notifications For** to **Mentions**
3. User2 write DM to User1
4. User1 gets no notifications neither desktop or mobile

### Expected behavior:

There should be notifications (both desktop and mobile, if desktop not online) on DM messages

### Actual behavior:

Here is a problematic settings:
![image](https://user-images.githubusercontent.com/4023037/84007731-84100200-a979-11ea-9050-742980f54ec1.png)

Here is a table (matrix) of all available and tested variants of types of chats and as a result - notifications.
![image](https://user-images.githubusercontent.com/4023037/84008061-f54fb500-a979-11ea-9a6c-0cd920f26df2.png)
If YES - there was notification
If NO - there wasn't notification
Filled in red - problem notifications. There should be notifications according to settings and other tests, but in fact - no notifications.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 2.17.9 and Chrome 83
- Operating System: Windows 10

**Comment by ankar84** [comment]
Issue is still exist

**Comment by g-thome** [comment]
Hi, @ankar84 
Does it still happens to you using the latest release? We've tested the scenario described in the description but we ended up with the expected result.

**Comment by ankar84** [comment]
> Hi, @ankar84
> Does it still happens to you using the latest release? We've tested the scenario described in the description but we ended up with the expected result.

Hi, @g-thome 
Yeap, just checked that issue on most recent 3.7.1 server version, and yes - no desktop notification on DM and no push notification on DM when desktop is offline.
BUT!
If DM has mention me with `@` - push and desktop notification works fine.
But it's insane in DM mention user that only one in that conversation with `@`
DM itself should be like mention.

@g-thome just follow steps to reproduce:
1. User1 set Show Desktop Notifications For to Mentions
2. User1 set Push Mobile Notifications For to Mentions
3. User2 write DM to User1
4. User1 gets no notifications neither desktop or mobile
5. If User2 write DM with `@User1` - notification appears!

**Comment by ankar84** [comment]
On Windows 10 computer same behavior is on Web client (user Chrome 86 for that) as a desktop client version 3.0.5

Here is a desktop screens
![image](https://user-images.githubusercontent.com/4023037/98219445-1125aa00-1f5e-11eb-8537-7033a1f5d4d9.png)
And next gif illustrate that issue.
First I sent just `test` message - no any notification.
Then I sent `@karlanaa test` and there is a notification immediately.
You can see, that `test` and `@karlanaa test` was sent is same moment.
So, it's 100% proof
![dm](https://user-images.githubusercontent.com/4023037/98219920-b0e33800-1f5e-11eb-9a5d-ffdd31a3a746.gif)

**Comment by ankar84** [comment]
And again - once I changes Notifications settings - there is a lot of updates in my sidebar appears. Looks like my subscriptions are recalculate or something.

**Comment by GOID1989** [comment]
For notification "subsystem" nodejs instances exchange direct messages on 3000 port.
Try to check your 15 instances communication between each-other

['Maybe' same problem solved here](https://forums.rocket.chat/t/multitple-rc-instances-with-docker-compose/10826)

**Comment by ankar84** [comment]
> For notification "subsystem" nodejs instances exchange direct messages on 3000 port.
> Try to check your 15 instances communication between each-other


Usually errors in instances communications leads to much serious and critical issue

All instances show connected status in Admin UI - Info panel:
![image](https://user-images.githubusercontent.com/4023037/113466336-ab254c00-9443-11eb-8eb0-bdc47aa8f69b.png)

**Comment by ankar84** [comment]
> And again - once I changes Notifications settings - there is a lot of updates in my sidebar appears. Looks like my subscriptions are recalculate or something.

@g-thome hey, Gabriel! I sent demo of that case to you and Diego at open server.

**Comment by ankar84** [comment]
Just tested on most recent 3.14 - issue still here
![notifications-on-dm](https://user-images.githubusercontent.com/4023037/118430187-3305a380-b6dc-11eb-9793-a53351ba0dc9.gif)

**Comment by ankar84** [comment]
Hey, @sampaiodiego @g-thome 
**Just checked at 4.8.2 server version and 4.29 mobile version.**
I set both **Desktop** and **Mobile** notification to **Mentions**
![image](https://user-images.githubusercontent.com/4023037/189091617-dd0e3a91-c084-4ee4-a726-3d435d1c4552.png)
And **push stop working on regular messages in DM** (mention with `@` still works in DM and lead to push).
But then I set Desktop notification to Default (All Messages) and Mobile is still on Mentions then I get push on regular message!

So, issue is still the same. Please diagnose that and fix if possible.
Thank you!

**Comment by ankar84** [comment]
I'm on a 5.3.5 now and issue is still here.
But for some reason open.rocket.chat server works good in that case. I got a push notifications from opens server.
![image](https://user-images.githubusercontent.com/4023037/212237126-08b3a1a9-3e3d-4c5d-a16e-429522b90194.png)
