### ISSUE TITLE
Push notification issue upon 3.4-3.5 upgrade

### ISSUE THREAD

**Issue by brittyazel** [RocketChat/Rocket.Chat#18396]
### Description:

Upon upgrading to 3.5.0 we are getting this message "Action required The mobile notifications were disabled to all users, go to "Admin > Push" to enable the Push Gateway again"

I have followed the instructions, accepted the agreement, and it still is giving the issue. I have restarted the server as well and toggled the push gateway on and off multiple times to no avail.

### Expected behavior:

I expected the push notification message and functionality to go back to normal upon accepting the agreement and re-enabling the gateway

### Actual behavior:

No matter how the gateway is toggled, the message persists. Something isn't sticking

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: Browser, 3.5.0
- Operating System: Windows and Linux

### Relevant logs:

```
I20200728-04:34:23.153(0) LocalStore: store created at  
I20200728-04:34:23.175(0) LocalStore: store created at  
I20200728-04:34:23.176(0) LocalStore: store created at  
I20200728-04:34:23.277(0) Exception in callback of async function: MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}     at Function.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/error.js:43:12)     at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:149:22)     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/common_functions.js:376:39     at handler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:1204:22)     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:404:18     at processTicksAndRejections (internal/process/task_queues.js:79:11) {   driver: true,   name: 'MongoError',   index: 0,   code: 9,   errmsg: "'$set' is empty. You must specify a field like so: {$set: {<field>: ...}}",   [Symbol(mongoErrorContextSymbol)]: {} } 
I20200728-04:34:23.759(0) Setting default file store to GridFS 
I20200728-04:34:27.234(0) (migrations.js:120) Migrations: Not migrating, already at version 201
I20200728-04:34:27.402(0) ufs: temp directory created at "/tmp/ufs" 
I20200728-04:34:29.284(0) Configuring Prometheus { port: 9458, enabled: true, resetInterval: 0, collectGC: false } 
I20200728-04:35:00.689(0) Updating process.env.MAIL_URL 
I20200728-04:35:00.712(0) The App c33fa1a6-68a7-491e-bf49-9d7b99671c48 is checking if "poll" command exists. 
I20200728-04:35:00.822(0) Using GridFS for custom sounds storage 
I20200728-04:35:00.829(0) Using GridFS for custom emoji storage 
I20200728-04:35:00.878(0) The App c33fa1a6-68a7-491e-bf49-9d7b99671c48 is registering the command: "poll" 
I20200728-04:35:00.906(0) The App 684202ed-1461-4983-9ea7-fde74b15026c is unregistering all apis 
I20200728-04:35:00.906(0) The App 684202ed-1461-4983-9ea7-fde74b15026c is registering the api: "webhook" (/api/apps/public/684202ed-1461-4983-9ea7-fde74b15026c/webhook) 
I20200728-04:35:01.019(0) Loaded the Apps Framework and loaded a total of 2 Apps! 
I20200728-04:35:01.830(0) ➔ System ➔ startup 
I20200728-04:35:01.831(0) ➔ +-----------------------------------------------+ 
I20200728-04:35:01.831(0) ➔ |                 SERVER RUNNING                | 
I20200728-04:35:01.831(0) ➔ +-----------------------------------------------+ 
I20200728-04:35:01.831(0) ➔ |                                               | 
I20200728-04:35:01.832(0) ➔ |  Rocket.Chat Version: 3.5.0                   | 
I20200728-04:35:01.832(0) ➔ |       NodeJS Version: 12.16.1 - x64           | 
I20200728-04:35:01.832(0) ➔ |      MongoDB Version: 3.6.3                   | 
I20200728-04:35:01.832(0) ➔ |       MongoDB Engine: unknown                 | 
I20200728-04:35:01.832(0) ➔ |             Platform: linux                   | 
I20200728-04:35:01.832(0) ➔ |         Process Port: 3000                    | 
I20200728-04:35:01.833(0) ➔ |             Site URL: https://chat.gnome.org  | 
I20200728-04:35:01.833(0) ➔ |     ReplicaSet OpLog: Enabled                 | 
I20200728-04:35:01.833(0) ➔ |          Commit Hash: 72718532bc              | 
I20200728-04:35:01.833(0) ➔ |        Commit Branch: HEAD                    | 
I20200728-04:35:01.833(0) ➔ |                                               | 
I20200728-04:35:01.834(0) ➔ +-----------------------------------------------+ 

```

**Comment by irfanjunaid** [comment]
Hi,
Observing the same here as well...

```
I20200729-09:53:30.639(5.5) LocalStore: store created at  
I20200729-09:53:30.701(5.5) LocalStore: store created at  
I20200729-09:53:30.702(5.5) LocalStore: store created at  
I20200729-09:53:31.717(5.5) Setting default file store to GridFS 
I20200729-09:53:38.828(5.5) (migrations.js:120) Migrations: Not migrating, already at version 201
I20200729-09:54:18.921(5.5) Updating process.env.MAIL_URL 
I20200729-09:54:24.554(5.5) Using GridFS for custom sounds storage 
I20200729-09:54:24.582(5.5) Using GridFS for custom emoji storage 
I20200729-09:54:24.776(5.5) Loaded the Apps Framework and loaded a total of 4 Apps! 
I20200729-09:54:26.651(5.5) ➔ System ➔ startup 
I20200729-09:54:26.652(5.5) ➔ +--------------------------------------------------+ 
I20200729-09:54:26.652(5.5) ➔ |                  SERVER RUNNING                  | 
I20200729-09:54:26.652(5.5) ➔ +--------------------------------------------------+ 
I20200729-09:54:26.653(5.5) ➔ |                                                  | 
I20200729-09:54:26.653(5.5) ➔ |  Rocket.Chat Version: 3.5.0                      | 
I20200729-09:54:26.653(5.5) ➔ |       NodeJS Version: 12.14.0 - x64              | 
I20200729-09:54:26.653(5.5) ➔ |      MongoDB Version: 4.0.19                     | 
I20200729-09:54:26.654(5.5) ➔ |       MongoDB Engine: mmapv1                     | 
I20200729-09:54:26.654(5.5) ➔ |             Platform: linux                      | 
I20200729-09:54:26.654(5.5) ➔ |         Process Port: 3000                       | 
I20200729-09:54:26.655(5.5) ➔ |             Site URL: https://chat.domain.com  | 
I20200729-09:54:26.655(5.5) ➔ |     ReplicaSet OpLog: Enabled                    | 
I20200729-09:54:26.655(5.5) ➔ |          Commit Hash: 72718532bc                 | 
I20200729-09:54:26.656(5.5) ➔ |        Commit Branch: HEAD                       | 
I20200729-09:54:26.656(5.5) ➔ |                                                  | 
I20200729-09:54:26.656(5.5) ➔ +--------------------------------------------------+ 
```

> You need to accept to register your server (Setup Wizard > Organization Info > Register Server) and our privacy terms (Setup Wizard > Could Info > Cloud Service Privacy Terms Agreement) to enabled this setting and use our gateway

Followed these instructions as well. Server registered and accepted cloud privacy terms. When I click on blue "Send a test push to my user" button, nothing happens. Also, push notifications are not working for anyone.

**Comment by golflima** [comment]
Same issue here. We upgraded from 3.3.3 to 3.5.0 using the Docker Image from https://hub.docker.com/_/rocket-chat, and we just lost the push notifications too.
The server is was registered upon the first installation, I checked it and it still registered (I even "synced" it this morning, but no change), but I can't enable the push notification, it says that I need to register my server... I even went on https://cloud.rocket.chat/ to see if there is a problem, but it seems not.

```
2020-07-29T07:40:58.496412766Z ➔ +-------------------------------------------------------+
2020-07-29T07:40:58.496713026Z ➔ |                     SERVER RUNNING                    |
2020-07-29T07:40:58.496896087Z ➔ +-------------------------------------------------------+
2020-07-29T07:40:58.497128772Z ➔ |                                                       |
2020-07-29T07:40:58.497370107Z ➔ |  Rocket.Chat Version: 3.5.0                           |
2020-07-29T07:40:58.497630337Z ➔ |       NodeJS Version: 12.16.1 - x64                   |
2020-07-29T07:40:58.497850339Z ➔ |      MongoDB Version: 4.2.3                           |
2020-07-29T07:40:58.498065696Z ➔ |       MongoDB Engine: wiredTiger                      |
2020-07-29T07:40:58.498285132Z ➔ |             Platform: linux                           |
2020-07-29T07:40:58.498515629Z ➔ |         Process Port: 3000                            |
2020-07-29T07:40:58.498739585Z ➔ |             Site URL: https://rocketchat.swibeco.com  |
2020-07-29T07:40:58.498960216Z ➔ |     ReplicaSet OpLog: Enabled                         |
2020-07-29T07:40:58.499179318Z ➔ |          Commit Hash: 72718532bc                      |
2020-07-29T07:40:58.499400160Z ➔ |        Commit Branch: HEAD                            |
2020-07-29T07:40:58.499619837Z ➔ |                                                       |
2020-07-29T07:40:58.499838368Z ➔ +-------------------------------------------------------+
```

**Comment by pipozzz** [comment]
The same for me  :( ...

**Comment by rodrigok** [comment]
@golflima did you accept the Cloud Terms at `Admin > Setup Wizard > Could Info > Cloud Service Privacy Terms Agreement`?

**Comment by rodrigok** [comment]
It's important to note that you need to **restart** your server after changing any of those settings related to Push Notifications.

**Comment by sampaiodiego** [comment]
hi guys, I'm sorry the confusion and frustration this might be causing to you, but let me clarify some things and see if some are the case for you:

- the red top bar alert will not disappear automatically after you enable push notifications again, it is just an alert that should be dismissed manually (I'm sorry the bad UX on this one)
- **after** you enabled both settings (`Admin > Setup Wizard > Organization Info > Register Server` and `Admin Setup Wizard > Could Info > Cloud Service Privacy Terms Agreement`) you'll be able to enable the setting `Admin > Push > Enable Gateway` again.. after doing that you **must restart the server** to get notifications working again

so after you enable the setting `Enable Gateway` and restart the server, notifications should be working, but as the previous alert we have sent, you need to make sure to be registered via `Connectivity Services` screen (`/admin/cloud`) - see https://forums.rocket.chat/t/enforcing-registration-requirement-to-utilize-push-gateway/7545

please let me know if that still doesn't work.

**Comment by golflima** [comment]
@rodrigok Thank you, it was indeed not checked. As it was listed in the Setup Wizard I assumed it was OK since the server was registered since the beginning (and I didn't found it right away in the Admin because it's in French (but the message was in English)), but that was not the case. Everything is checked now, and I'll restart the server soon. I'll keep you updated.

**Comment by golflima** [comment]
It works fine now, sent a test push notification to my phone with success.

**Comment by brittyazel** [comment]
I believe my issue was just the red bar not going away. I interpreted that to mean the issue remained even though I had accepted the ToS and restarted the server. It never occurred to me that the issue was resolved, and the red bar just needed to be dismissed.

**Comment by irfanjunaid** [comment]
Hi @rodrigok @sampaiodiego Push notifications are working correctly now. 

I am pretty sure I have done the above mentioned steps before commenting here... When signing in as usual today, I noticed push notifications not coming at all... No one in our organization was getting push notifications either on both Android and iOS. In afternoon, at around 7 AM UTC, suddenly I got a wave of missed notifications... After few hours around 12 PM UTC, everyone started getting notifications...

**Comment by pipozzz** [comment]
@sampaiodiego Thanks, now it's working fine.

**Comment by nrenich** [comment]
Does anyone know how to clear the Connectivity Settings manually? I am stuck in a loop, I can't add my server to the workspace on the cloud rocket chat site nor remove it from the admin UI. https://forums.rocket.chat/t/cant-disconnect-from-rocket-chat-cloud-and-re-add/7874/1

**Comment by sampaiodiego** [comment]
I'll be closing this issue since it looks like it is working to everyone.

let me know if you still have any questions and I can re-open the issue if that is the case.. thanks

**Comment by markusstoll** [comment]
@sampaiodiego I still am stuck with this problem.

It appeared after upgrading from 3.4 to 3.5.1 - otherwise as stated from rocket.cat "The mobile notifications were disabled to all users, go to "Admin > Push" to enable the Push Gateway again", push notifications still were activated, but not functional.

I did register my server with Rocket.Chat cloud
I did confirm "Cloud Service Privacy Terms"
I did disable and reenable push notifications (with each time restarting the server)

But still do not get push notifications (though Rocket.Chat says "notification sent" on "send test push notification"

Anything else I can check?

Markus

**Comment by sampaiodiego** [comment]
@markusstoll I'm assuming push notifications were working for you before the upgrade, is that the case? make sure your settings are like this:

![image](https://user-images.githubusercontent.com/8591547/89685775-64db1580-d8d3-11ea-8246-83bab89b6f36.png)


also, when you hit "send a test push to my user", it should say "Your push was sent to N devices", where `N` is the number of devices you've used to log in via mobile app for that same user. Does it shows at least 1 device on the success message for you?

**Comment by markusstoll** [comment]
@sampaiodiego thanks! This resolved my issue

Markus

**Comment by dfuchs** [comment]
AND: be sure you have your mobile app connected with the correct and over authentication code send by email authenticated user.

**Comment by 88fingerslukee** [comment]
None of this is working for me. Push was working a week ago. Yesterday they started getting extremely delayed and now I can't even send myself a test message.

I have done all the steps outlined above.  Can somebody please help me?

**Comment by rodrigok** [comment]
@88fingerslukee please contact our support team at support@rocket.chat

**Comment by kkhanh** [comment]
We also have the same problem. Everything is well-configured and yet notifications are not working
