### ISSUE TITLE
[3.6.0] Does not render pdf previews

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat#18740]
### Description:

Does not render pdf previews

### Steps to reproduce:

1. Upload PDF

### Expected behavior:

Rendered preview of pdf files.

### Actual behavior:

No previews for pdf files rendered, only infinite loading cycle.
![003](https://user-images.githubusercontent.com/49910825/91656666-dfeeb080-eaba-11ea-81ba-0de1319b2c09.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.6.0
- Operating System: GNU/Debian 10 alias Buster
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Both (Webbrowser Firefox/Opera)
- Operating System: Windows / Linux

**Comment by jathan** [comment]
Looks like some sort of Javascript problem?

![image](https://user-images.githubusercontent.com/626086/91760769-8c9f5f80-eb99-11ea-9b57-aa0195c99662.png)

**Comment by ankar84** [comment]
Confirm that
![image](https://user-images.githubusercontent.com/4023037/91934824-f2542e80-ecf4-11ea-8591-b40d5c5c3523.png)

**Comment by cleocir** [comment]
Same problem here

**Comment by himpierre** [comment]
Still broken with 3.6.1. :(

**Comment by awunder** [comment]
still broken with 3.6.2

**Comment by awunder** [comment]
argh.. fix comes 10h too late.. sry, waiting for 3.6.3 it is..

**Comment by Sx3** [comment]
Same Issue here with snap version 3.6.2.

**Comment by TimmiORG** [comment]
This is fixed from 3.6.3 and 3.7.0

**Comment by Sx3** [comment]
Now it is on version 2.4.11 too ??

**Comment by TimmiORG** [comment]
> Now it is on version 2.4.11 too ??

With 2.4.11 you are referring to the client right?
This is independent from the client as the server will render it.

The issue is fixed in rocket.chat server version 3.6.3 and higher.

**Comment by Sx3** [comment]
> > Now it is on version 2.4.11 too ??
> 
> With 2.4.11 you are referring to the client right?
> This is independent from the client as the server will render it.
> 
> The issue is fixed in rocket.chat server version 3.6.3 and higher.

the issue is with server v2.4.11..so is that mean we need to switch the v2 channel to v3 in order to get the pdf thumbnail working ?

**Comment by TimmiORG** [comment]
> > > Now it is on version 2.4.11 too ??
> > 
> > 
> > With 2.4.11 you are referring to the client right?
> > This is independent from the client as the server will render it.
> > The issue is fixed in rocket.chat server version 3.6.3 and higher.
> 
> the issue is with server v2.4.11..so is that mean we need to switch the v2 channel to v3 in order to get the pdf thumbnail working ?

Yes correct.
But your post (https://github.com/RocketChat/Rocket.Chat/issues/18740#issuecomment-713716209) is saying you are using 3.6.2.

**Comment by Sx3** [comment]
we have several servers running rocket chat..one of them is on v3 channel and others are on v2 Channel..so we use both versions.
as we are using snap install we still don't have the v3.6.3 for snap ,only the v3.6.2

**Comment by Sx3** [comment]
![image](https://user-images.githubusercontent.com/3599933/104049603-40c98a80-520b-11eb-9bbd-372fde0b8705.png)

PDF thumbnail Issue again on rocket chat snap version 3.9.3

![image](https://user-images.githubusercontent.com/3599933/104049707-6787c100-520b-11eb-85c2-c618cb3b54a4.png)

**Comment by Sx3** [comment]
Surprisingly after 3 years version 6.x is having same issue
