### ISSUE TITLE
Hyperlinks on Android app client

### ISSUE THREAD

**Issue by rchikballapur** [RocketChat/Rocket.Chat#1877]
Bug: When I tap on hyperlinks sent on RC to my Android App client, I cannot open the link in a browser or on RC.

A long press offers 3 options: 1) Delete message, 2) Report Abuse 3) Cancel but there is no way to Copy the link to paste it in a browser either.

**Comment by rodrigok** [comment]
Which version of Android App and RC Server are you using. This problem already was solved.

**Comment by bsdcon** [comment]
Just FYI: On iOS9 with demo.rocket.chat (listing version 13.0) it shows both the expected copy snippet but also the delete/report/cancel large buttons.

**Comment by rodrigok** [comment]
@bsdcon, yes, we need to improve this context menu.

**Comment by geekgonecrazy** [comment]
For reference to existing issue: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/37

**Comment by rchikballapur** [comment]
@rodrigok , here are the details you requested. I updated it to the latest version this morning and issue is still there.
App version: 2.2.2
Server commit: 8da72776017a971bb02d27a6e1d602ec975eaf03

**Comment by rodrigok** [comment]
We had some problems with mobile app updates, can you delete the app and reinstall it?

Just to clarify, we are talking about open links in a browser app when you touch the link, right?

**Comment by rchikballapur** [comment]
Actually I did delete and reinstall to be sure. And yes, I am referring to being able to open hyperlinks posted in the RC app on a browser when I touch the link. I am on the latest version of Android 6.0.1 on a 2013 Nexus 5 if that helps.

**Comment by rodrigok** [comment]
@rchikballapur can you go to `/api/info` and paste here the result?

**Comment by rchikballapur** [comment]
{
"version": "0.12.0",
"compile": {
"date": "2016-01-04T18:21:38.732Z",
"nodeVersion": "v0.10.40",
"arch": "x64",
"platform": "linux",
"osRelease": "3.13.0-71-generic",
"totalMemmory": 3947401216 <tel:3947401216>,
"freeMemmory": 127201280 <tel:127201280>,
"cpus": 2
},

**Comment by rodrigok** [comment]
@rchikballapur strange, this is working for me and for @sampaiodiego

**Comment by rchikballapur** [comment]
@rodrigok what else could it be? can you give me some tips on what I can do to make it work then?

**Comment by rodrigok** [comment]
Sorry @rchikballapur, this problem was fixed in the version 0.13.0 as you can see (the tag) on the commit https://github.com/RocketChat/Rocket.Chat/commit/c33a446759c4a33bb898581c5e64f4fecd0f9433

Can you update your server and try again?

Access `/api/info` to check if your update worked.

**Comment by geekgonecrazy** [comment]
This issue was fixed in: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/37
