### ISSUE TITLE
[BUG] Non-latin search issues

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19344]
### Description:

There is a couple bugs in **Admin UI - Rooms** search (maybe in some other place too, but now I'm talking about Rooms) with non-Latin search query (Cyrillic in my case).

### Steps to reproduce:

1. Enable **UTF8 Names Validation** on **Admin UI - General**
2. Enable **Allow Special Characters in Room Names** on **Admin UI - Layout - User Interface**
3. Create channel and private room with Cyrillic names, like `тестовый канал` and `тестовый чат`
4. Go to Admin UI - Rooms and try to find that room and channel

### Expected behavior:

Non-Latin search should work in every search field in Rocket Chat interface

### Actual behavior:

UTF8 Names Validation
![image](https://user-images.githubusercontent.com/4023037/96969521-4de3b100-151b-11eb-8ded-77689ba5e3c1.png)
Allow Special Characters in Room Names
![image](https://user-images.githubusercontent.com/4023037/96970197-fbef5b00-151b-11eb-8aa9-31dc246b036e.png)
Private room and channel with Cyrillic names
![image](https://user-images.githubusercontent.com/4023037/96970302-23462800-151c-11eb-9385-4664eea39f6d.png)
Search attempts
![image](https://user-images.githubusercontent.com/4023037/96970407-51c40300-151c-11eb-8121-d22de2c77b71.png)
![image](https://user-images.githubusercontent.com/4023037/96970441-60121f00-151c-11eb-9806-cdf03bc42100.png)
Transliteration search works fine
![image](https://user-images.githubusercontent.com/4023037/96970590-9780cb80-151c-11eb-8fcb-1334569e95a4.png)
![image](https://user-images.githubusercontent.com/4023037/96970657-b2534000-151c-11eb-9609-373b0d2b6f96.png)

And a very bad thing - internal transliteration name now not shown in Room Info (it was in 3.1.1 server version)
![image](https://user-images.githubusercontent.com/4023037/96970820-ea5a8300-151c-11eb-91f6-b5d325914953.png)
![image](https://user-images.githubusercontent.com/4023037/96970889-02320700-151d-11eb-8a9d-c5aa2335a9a8.png)

And another one issue is that Discussion check box have AND logic but not OR logic (as it should be)
Here is an illustrative screenshot
![image](https://user-images.githubusercontent.com/4023037/96971106-51783780-151d-11eb-8cd8-8cca5f878ad2.png)
![image](https://user-images.githubusercontent.com/4023037/96971195-766caa80-151d-11eb-9323-0c765232adc4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOC7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Chrome 85
- Operating System: Windows 10

### Additional context

So, in that issue actually 3 bugs:
- Cyrillic search doesn't work in Rooms
- No internal name of room that was in Room Info in previous versions
- Discussions checkbox logic is incorrect (AND instead of proper OR)

@ggazzo and all Front-End team, please take a look at that issue.
Thanks!

### Relevant logs:

No logs

**Comment by ankar84** [comment]
**Admin UI - Permissions - owner - USERS IN ROLE - Choose a room** same issue
![image](https://user-images.githubusercontent.com/4023037/97027465-72fc1200-1563-11eb-9621-2b104abf7cd2.png)
But **Add User** - works perfect with Cyrillic letters
![image](https://user-images.githubusercontent.com/4023037/97027619-a8086480-1563-11eb-8007-e2e5b69bc86d.png)

**Comment by damian-centrone** [comment]
This issue is already fixed, you can now search for non latin characters. Tested on 3.8.0

**Comment by ankar84** [comment]
@damian-centrone hey!
It would be nice if you let me check if that issue is solved or not by myself.

**Comment by damian-centrone** [comment]
Hello, this was tested on the next release available in a few days. I close the ticket for internal control purposes. When 3.8.0 is deployed and if you have the same issue, I can reopen.

**Comment by ankar84** [comment]
@damian-centrone actually issue is here on 4.3.3
![image](https://user-images.githubusercontent.com/4023037/160308655-989e10a0-a37d-4994-bc0f-8af29fa53bd4.png)
![image](https://user-images.githubusercontent.com/4023037/160308692-ef667bc9-035b-4526-bf1b-76d231b43643.png)
![image](https://user-images.githubusercontent.com/4023037/160308716-90375d41-5346-4a3b-8712-9927132fff95.png)

**Comment by ankar84** [comment]
Still an issue in 5.0.3!
![image](https://user-images.githubusercontent.com/4023037/186134561-65bcd628-22dc-426c-b6dd-0c7f46e1fdab.png)
![image](https://user-images.githubusercontent.com/4023037/186134618-1ef97d4e-505c-44c2-8028-ccd44c87d351.png)
![image](https://user-images.githubusercontent.com/4023037/186134690-156f3cce-b4b8-4065-9384-1cbf4fe3b261.png)
![image](https://user-images.githubusercontent.com/4023037/186134954-201284c8-3208-4814-84ed-55988785708c.png)

**Comment by ankar84** [comment]
Actually `Admin UI - Layout - User Interface - Allow Special Characters in Room Names` setting have impact to that search behavior.
![image](https://user-images.githubusercontent.com/4023037/187113895-d1aa95d0-cfd6-4483-b7b8-0340b7d790e4.png)

**Comment by Gummikavalier** [comment]
I think this is again an issue in RC 5.3.2.

Even when `Allow Special Characters in Room Names` is disabled on our instance, I found out that one user had been able to create rooms with using spaces and Nordic characters (UTF-8). This has probably happened via desktop or mobile client (unconfirmed).

Any of these rooms are now invisible in the admin UI rooms search.

**Comment by IgorOhrimenko** [comment]
6.6.1 fixed
![изображение](https://github.com/RocketChat/Rocket.Chat/assets/24807060/81d238de-66aa-4548-b76b-25fefb093c79)
