### ISSUE TITLE
LDAP (Ad) don't work with latest version: 1.14.0

### ISSUE THREAD

**Issue by valessiobrito** [RocketChat/Rocket.Chat#1967]
Latest stable build or the beta development build (today)

LDAP: Error [Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.]
[Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.]
[LDAP] Falling back to standard account base
stream error Error during WebSocket handshake: Unexpected response code: 400

/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226
                        throw new Error('Future resolved more than once');
                              ^
Error: Future resolved more than once
    at Object.Future.return (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226:10)
    at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:98:1)
    at Client.emit (events.js:95:17)
    at Socket.onSocketError (/opt/Rocket.Chat/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:492:13)

**Comment by bsdcon** [comment]
Confirmed with docker tags 0.14.0, latest, develop. The last working docker tag is 0.13.0

**Comment by tuudik** [comment]
I have same issue with 0.14.10, worked with 0.13.0.
I tried to enable SSL in both ways, Reject Unauthorized true and false.

**_Situation currently in logs_**
**LDAP without SSL:**
```
Bind before search cn=admin,dc=ldap,dc=ldap,dc=ldap password
LDAP: Error [Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.]
[Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.]
[LDAP] Falling back to standard account base
```

**LDAP with SSL Reject Unauthorized true or false:**
```
Exception while invoking method 'login' TypeError: Object [object global] has no method '_send'
    at starttls (/usr/share/Rocket.Chat/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:955:15)
    at packages/meteor/helpers.js:118:1
    at startTLS (packages/rocketchat_ldap/ldap_server.js:58:1)
    at [object Object].LDAP.ldapCheck (packages/rocketchat_ldap/ldap_server.js:94:1)
    at [object Object].__coffeescriptShare (packages/rocketchat_ldap/ldap_server.js:256:1)
    at accounts_server.js:462:32
    at tryLoginMethod (accounts_server.js:239:14)
    at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
    at [object Object].methods.login (accounts_server.js:522:27)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
```

**Comment by andrzejwp** [comment]
+1, same problem here

**Comment by miscs** [comment]
same problem. LDAP worked with 0.13.0 but not with 0.14.0

**Comment by marceloschmidt** [comment]
Thanks, we will fix that on 0.14.1 in a couple hours.

**Comment by tuudik** [comment]
Any workarounds until then?

**Comment by rodrigok** [comment]
Guys, I updated the code, can you try again? The update is in develop branch and if you are using docker wait some minutes to docker build the container.

**Comment by tuudik** [comment]
For me the issue still occurs, tried with TLS and without.

**Comment by tuudik** [comment]
Seems like I didnt get the package with the updates, i checked programs/server/packages/rocketchat_ldap.js and wount it was old when compared to https://github.com/RocketChat/Rocket.Chat/commit/cdf762270455b9fb0d351074798dd3f85b184dc5

I then changed the file with vim accordingly, restarted rocket, but the issue still persisted.

**Comment by rodrigok** [comment]
Ok, I need access to some LDAP server to test this.

**Comment by andrzejwp** [comment]
I can confirm that LDAP issues have been resolved (I haven't checked with TLS enabled though).

**Comment by bsdcon** [comment]
Tested with following version -- LDAP succeeds but only if the account was really auto-provisioned via an LDAP authentication (e.g. if it was registered with normal password then login will not be completed successfully).
Fallback to classic password login works.

```
"version": "0.14.0",
commit": {
    "hash": "ad1ffbdc65e7ba9f5bcac5f224d682be85143b8c",
    "date": "Mon Jan 18 20:44:08 2016 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1966 from RocketChat/improvements/force_ssl_urls"
  },
```

**Comment by tuudik** [comment]
@rodrigok Unfortunately, I can't provide access to my LDAP server. Tho I did ask ldapjs dev for some ideas: https://github.com/mcavage/node-ldapjs/issues/339
```
It would appear that some of the Meteor stuff you're using is rebinding that function. I don't believe that any of the public client methods support being bound to anything but the client object itself.
```

Perhaps this could help?

**Comment by rodrigok** [comment]
@tuudik you are right, I'm sorry, was my fault, I forgot the bind of the `wrapAsync`, as I can't test the code I didn't realized that, thanks.

The change:
https://github.com/RocketChat/Rocket.Chat/commit/72a8b0ca4257eb9b08ccdb06871381469ad8c18b?ts=2

Can you update to the latest develop commit and try again?

**Comment by jeffrapp** [comment]
@rodrigok that didn't work for me.  It at least fixed the server from crashing, but it doesn't seem to resolve #1984.  

I did some testing and it looks like it's failing due to line 137 passing null instead of the email.  My scenario is based against AD, so they log in with just a user name and checks against the sAMAccountName.  In our case, the full user name isn't their email, so the domain is never split out on line 112.  

It looks like this should be resolved by setting the defaultDomain option above, but I can't seem to find that in the UI or in the database.

**Comment by tuudik** [comment]
@rodrigok It's a little bit better already, I can see from openldap log that TLS connection is established, but after this, it's silence. Even nothing in RC log:
```
Jan 21 09:30:16 ldap slapd[13534]: conn=2195 fd=25 ACCEPT from IP=127.0.0.1:59301 (IP=0.0.0.0:110)
Jan 21 09:30:16 ldap slapd[13534]: conn=2195 op=0 EXT oid=1.3.6.1.4.1.1466.20037
Jan 21 09:30:16 ldap slapd[13534]: conn=2195 op=0 STARTTLS
Jan 21 09:30:16 ldap slapd[13534]: conn=2195 op=0 RESULT oid= err=0 text=
Jan 21 09:30:16 ldap slapd[13534]: conn=2195 fd=25 TLS established tls_ssf=256 ssf=256
```

It looks from that, after establishing TLS connection, RC is just standing still and not starting bind with ldap.

**Comment by rodrigok** [comment]
@jeffrapp the email or domain isn't required to create account or login in RC, so this can't be de problem.

@tuudik there is no line starting with `StartTLS Result` in RC logs?

Sorry guys, this will be a long way since I'm not a LDAP expert and I don't have a LDAP server to test (I tried to install with no success).

**Comment by tuudik** [comment]
@rodrigok I think following the links above, you will be able to setup openldap with TLS about in 20 minutes:
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-openldap-and-phpldapadmin-on-an-ubuntu-14-04-server
https://www.digitalocean.com/community/tutorials/how-to-encrypt-openldap-connections-using-starttls

And yeah, RC logs didnt react anyhow, not a single line, I had even debug enabled.
Last line that appeared when opened the login page:
```
.....
[publish] userData -> userId: null , arguments:  {}
[methods] UserPresence:online -> userId: null , arguments:  {}
```

**Comment by valessiobrito** [comment]
LDAP Server Information (read-only access):
Server: ldap.forumsys.com  
Port: 389
Bind DN: cn=read-only-admin,dc=example,dc=com
Bind Password: password

ll user passwords are password.

You may also bind to individual Users (uid) or the two Groups (ou) that include:

ou=mathematicians,dc=example,dc=com
    riemann
    gauss
    euler
    euclid

ou=scientists,dc=example,dc=com
    einstein
    newton
    galieleo
    tesla

**Comment by rodrigok** [comment]
@valessiobrito I used this LDAP online server to develop our first version, but this server don't have TLS.

@tuudik In fact the problem isn't install the server, but how to configure, set users, groups, etc. If you can help me I can give you access to a linux server so you can configure the server as you have yours and we can get the same behaviour.

**Comment by jeffrapp** [comment]
@rodrigok - agreed, and that's what we've seen in previous releases, however that doesn't seem to be holding true at the moment.  

The problem I'm facing right now is that we can't provision new users.  The LDAP seems to work fine now, but it never proceeds beyond that point.  In the source, I changes the

```retObject.email = domain ? username + '@' + domain : false;```
to 
```retObject.email = username + '@domain.com';```

and after that, I was able to provision new users.

**Comment by rodrigok** [comment]
@jeffrapp I added the default domain option in may latest commit https://github.com/RocketChat/Rocket.Chat/commit/d2dcab302f0a1409fdd0a44ba2de3a6b8845abfe?ts=2

Can you try?

**Comment by jeffrapp** [comment]
@rodrigok That worked perfectly!

**Comment by Megatronic79** [comment]
@rodrigok let me know if you still need the ldap server, I can restart the dev one we put together for you last time.

**Comment by tuudik** [comment]
@Megatronic79 Do you have TLS also working to test StartTLS?

**Comment by rodrigok** [comment]
@Megatronic79 if you have TLS I want :smile: 

I want refactor all the LDAP code, so your server will be useful anyway.

**Comment by Megatronic79** [comment]
Hey @rodrigok this test ldap server is back online now for you and I PM'd you, im traveling at the mo from NYC to London so will enable the TLS and port forwarding when i get back tommorow.

**Comment by himbeere** [comment]
Hello.

Is this issue fixed? I have the same error with a fresh install.

thanks and cheers
t.

**Comment by jeffrapp** [comment]
Still getting occasional crashing, looks similar to the output @valessiobrito described:
```
rocketchat_1 | /app/bundle/programs/server/node_modules/fibers/future.js:226
rocketchat_1 |                  throw new Error('Future resolved more than once');
rocketchat_1 |                        ^
rocketchat_1 | Error: Future resolved more than once
rocketchat_1 |     at Object.Future.return (/app/bundle/programs/server/node_modules/fibers/future.js:226:10)
rocketchat_1 |     at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:100:1)
rocketchat_1 |     at Client.emit (events.js:95:17)
rocketchat_1 |     at Socket.onSocketError (/app/bundle/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
rocketchat_1 |     at Socket.emit (events.js:95:17)
rocketchat_1 |     at net.js:441:14
rocketchat_1 |     at process._tickDomainCallback (node.js:492:13)
rocketchat_rocketchat_1 exited with code 0
```

**Comment by liubin-cm** [comment]
I have the same error with the latest version

**Comment by apangan** [comment]
I got the same error with the develop, 0.14, 0.15 docker images. When first trying to authenticate with a valid AD account, I get the error:
```
rocketchat_1 |     Bind before search cn=admin,dc=my,dc=domain,dc=com password
rocketchat_1 |     LDAP: Error [Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.]
rocketchat_1 |     [Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.]
rocketchat_1 |     [LDAP] Falling back to standard account base
```
After a few seconds, the server crashes with the last error
```
rocketchat_1 | /app/bundle/programs/server/node_modules/fibers/future.js:226
rocketchat_1 |                  throw new Error('Future resolved more than once');
rocketchat_1 |                        ^
rocketchat_1 | Error: Future resolved more than once
rocketchat_1 |     at Object.Future.return (/app/bundle/programs/server/node_modules/fibers/future.js:226:10)
rocketchat_1 |     at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:100:1)
rocketchat_1 |     at Client.emit (events.js:95:17)
rocketchat_1 |     at Socket.onSocketError (/app/bundle/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
rocketchat_1 |     at Socket.emit (events.js:95:17)
rocketchat_1 |     at net.js:441:14
rocketchat_1 |     at process._tickDomainCallback (node.js:492:13)
rocketchat_rocketchat_1 exited with code 0
```
LDAP/AD authentication _is_ working for 0.13.0 with the same config.

**Comment by litewhatever** [comment]
Same issue hear with 0.15.0 - was really stable before changes in 0.13.0

**Comment by miscs** [comment]
for us its working quite good since 0.15.0. we just updated to 0.16.0 with no issues. 
but we aren´t using TLS yet.

**Comment by litewhatever** [comment]
Are aren't also using TLS so it dosn't seem to have anything to do with TLS. Exception handling issue?

**Comment by flauschi** [comment]
I also have crashes with the latest version with the same error message. They occur around 10 minutes after a user logged in through LDAP (without TLS).
I have temporarily worked around with an automatic restart of the docker container after failure.

**Comment by valessiobrito** [comment]
@rodrigok @engelgabriel  my last version 1.17
Normal work for a while. After no reason to.
I create a new Issue?

{ [InvalidCredentialsError: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1]
  dn: [Getter],
  code: [Getter],
  name: [Getter],
  message: [Getter] }
{ [Error: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1 [49]]
  error: 49,
  reason: '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0000',  
  details: undefined,
  message: '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0000 [49]',
  errorType: 'Meteor.Error' }
{ [Error: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1 [49]]
  error: 49,
  reason: '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0000',  
  details: undefined,
  message: '80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\u0000 [49]',
  errorType: 'Meteor.Error' }
[LDAP] Falling back to standard account base
stream error Network error: wss://domain.com.br/websocket: DEPTH_ZERO_SELF_SIGNED_CERT
LDAP search options { filter: '(|(mail=valessio.brito)(sAMAccountName=valessio.brito))',
  scope: 'sub' }
Attempt to bind CN=Valessio Soares de Brito,OU=Usuarios,DC=domain,DC=com,DC=br
/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226
                        throw new Error('Future resolved more than once');
                              ^
Error: Future resolved more than once
    at Object.Future.return (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:226:10)
    at Client.<anonymous> (packages/rocketchat_ldap/ldap_server.js:100:1)
    at Client.emit (events.js:95:17)
    at Socket.onSocketError (/opt/Rocket.Chat/programs/server/npm/rocketchat_ldap/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:492:13)

**Comment by engelgabriel** [comment]
hi @valessiobrito please create another issue for this.

**Comment by rodrigok** [comment]
@valessiobrito can you test with the latest code from our branch **develop**?
