### ISSUE TITLE
RC 3.9.0 Sidebar / GUI disappears after scrolling down in sidebar

### ISSUE THREAD

**Issue by TheWrongGuy** [RocketChat/Rocket.Chat#19719]
### Steps to reproduce:

1. Scroll down in the left sidebar. At first the scrolling works, after a distance the issue occurs.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Operating System: CentOS 7.8
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.8.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: MacOS 3.0.7 / Chrome 87.0.4280.67
- Operating System: MacOS Big Sur

### Relevant logs:

Dear all,

today I upgraded our RC Server from 3.6.1 to 3.9.0, which worked fine after upgrading node to 12.8.4. However with 3.9.0 the sidebar seems to be broken..at least for us. If you scroll down in the sidebar to get to the bottom of the direct messages the sidebar suddendly disappears and also all GUIs button disappear. After reloading the website or client all elements reappear, but it's still not possible to scroll down the sidebar. Did anybody else experience similar behaviours? I think this only appears if you have many direct messages which require to scroll down. Otherwise everything works fine. I'm unable to provide logs since I had to immediatly go back to 3.6.1 since the users have to use the server. I would give an older version a try. Is it pssible to download "install ready" older releases? I can only download the source code or the latest version.

Best regards

**Comment by sampaiodiego** [comment]
looks like some entry on the rooms list has some data that is breaking the React. is there any errors on browser console? do you have any custom code or have updated something on database directly?

@ggazzo is there something we can do to prevent this from hapenning?

**Comment by TheWrongGuy** [comment]
Thanks for the reply! As far as I know we don't have custom code for the sidebar and we never touched the database directly. I'm sorry I can't check the browser console, since I was in a hurry this morning getting the server back working. I can try to clone the VM the server is running on to reproduce the issue and provide logs or something, but it sounds like you already have an idea of whats going on. Can you tell me if I can download an older version of stable RC for testing? The main reason for the upgrade was, that the status in the sidebar is broken and not matching with the actual status. Recording to another issue this was fixed in 3.8.0.

**Comment by sampaiodiego** [comment]
we've seen this behavior with other React components, where an error makes the whole UI blank.. we didn't see it hapenning on the sidebar though.. but if you said it happens for you when you scrolled it down, I guess there might be an incompatible data somehow on some of you rooms. browser's console should show exactly what it is, so it will help a lot to get a fix for this.

>  Can you tell me if I can download an older version of stable RC for testing?

you can do it but you'll have to update the `migrations` collection to match the migration of the version you'll downgrade to. I don't recommend doing so if you don't know what you're doing.

**Comment by TheWrongGuy** [comment]
Okay I will try to find the time to reproduce this issue by cloning the VM. A blank new RC-Server will run fine interpreting your answer, that this is related to a specific set of data.

It wouldn't be a downgrade. I'm running 3.6.1 again restored from a snapshot of the VM so it would be a straight upgrade to 3.8.1. What would be the URL to download the older version?

**Comment by sampaiodiego** [comment]
> Okay I will try to find the time to reproduce this issue by cloning the VM. A blank new RC-Server will run fine interpreting your answer, that this is related to a specific set of data.

right.. I _guess_ you'll be able to reproduce it only with your current data..

> It wouldn't be a downgrade. I'm running 3.6.1 again restored from a snapshot of the VM so it would be a straight upgrade to 3.8.1. What would be the URL to download the older version?

cool, I thought you were saying you'd try to downgrade. if you're using a manual installation, you can use this link to download 3.8.2 version: https://releases.rocket.chat/3.8.2/download

**Comment by TheWrongGuy** [comment]
Okay thank you already for the help! I will try to do this tomorrow.

Thanks for the link. This will be helpful for the future, too! ;)

Where should I send you the browsers console content after capturing it?

**Comment by sampaiodiego** [comment]
it should have no personal/confidential data, so it would be fine (and preferable) to attach them here.. otherwise, you can shoot them to me at https://open.rocket.chat/direct/diego.sampaio

**Comment by TheWrongGuy** [comment]
Thanks! I will decide dependent from the content. :)

**Comment by TheWrongGuy** [comment]
Hey Diego,

I cloned the VM and ran it on another machine to test the upgrade. The version 3.6.0 was running fine after the clone, however now in 3.9.0 the sidebar instantly disappears. I extracted the following information from the Firefox Web Console: (The http error are most likely showing up due to running the server on a different URL and machine):

 Version:1.0 StartHTML:0000000100 EndHTML:0000025237 StartFragment:0000000100 EndFragment:0000025237
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/door.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/beep.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/chime.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/droplet.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/seasons.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/chelle.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/highbell.mp3 failed. home
All candidate resources failed to load. Media load paused. home
HTTP “Content-Type” of “audio/mpeg” is not supported. Load of media resource https://127.0.0.1/sounds/ding.mp3 failed. home
All candidate resources failed to load. Media load paused. home
Cannot play media. No decoders for requested formats: audio/mpeg, audio/mpeg, audio/mpeg, audio/mpeg, audio/mpeg, audio/mpeg, audio/mpeg, audio/mpeg home

TypeError: "e.uids is undefined"
    C /client/sidebar/RoomList.js:1
    e /client/sidebar/RoomList.js:1
    React 6
    unstable_runWithPriority /node_modules/scheduler/cjs/scheduler.production.min.js:27
    React 5
    node_modules rocket.chat/fuselage-hooks/dist/index.module.js:1
/node_modules/react-dom/cjs/react-dom.production.min.js:217:195

TypeError: "e.uids is undefined"
    C /client/sidebar/RoomList.js:1
    e /client/sidebar/RoomList.js:1
    React 6
    unstable_runWithPriority /node_modules/scheduler/cjs/scheduler.production.min.js:27
    React 5
    node_modules rocket.chat/fuselage-hooks/dist/index.module.js:1
/node_modules/react-dom/cjs/react-dom.production.min.js:217:195
    React 9
    unstable_runWithPriority /node_modules/scheduler/cjs/scheduler.production.min.js:27
    React 5
    current /node_modules/@rocket.chat/fuselage-hooks/dist/index.module.js:1


What occured to me is, that if I install nodejs using the manual instllation guide your provide, I end up with 12.8.4. However the bundled npm seems to be 6.14.6 not 8. Maybe the wrong NPM version during "npm install" is causing this? I can't manage to get 12.8.4 and 6.14.8 installed alongside. 6.14.8 seems to be bundled with 12.9.0.

**Comment by sampaiodiego** [comment]
thanks @TheWrongGuy .. looks like there is indeed a missing data on some of your rooms.. there is already a PR #19725 to prevent the issue from happenning, but I wonder why some of your rooms are missing `uids` field.

do you recall if you had any issues when updating to 3.1.0?

can you try something else on your test env? set this env var when starting it up: `MIGRATION_VERSION=179,rerun` it should fix the "broken room" and everything else should work just fine.

**Comment by TheWrongGuy** [comment]
@sampaiodiego 

Thank you guys for the quick fix. I don't remember any problems when upgrading to 3.1.0....At somepoint we had major issues with our RC-Docker environment, which crashed a lot and we transfered it over to a manual installation. Maybe there was something wrong then. Will the fix automatically prevent the issue when upgrading to the next release (3.9.1) Or will I  have to set the env var once? Where should I define the env var for testing? In a global bashrc or is there a specific config file where I should put this variable?

**Comment by sampaiodiego** [comment]
I'd recommend trying to get the data right/fixed first.. you'd just need to set the env var once, and you can set it the same way you set the `MONGO_URL` .. so basically, set `MIGRATION_VERSION` env var, start up the server, wait until it finishes starting up, shut it down, remove the env var and start up as you'd regularly.. but please do that on your test env first 🙏 

the fix that will land on 3.9.1 will just prevent the UI to break, but fixing the data is the best solution =)

**Comment by TheWrongGuy** [comment]
Okay. Unfortunately this didn't fix the issue. Referring to the manual installation docs I added the variable to Environments in the daemon config /lib/systemd/system/rocketchat.service. The Sidebar remains broken.... Thank you for the help. Do you have another idea. Otherwise I'll just wait for 3.9.1. I'm wondering why our sidebar is fine in 3.6.1 running atm, since the UID would be missing there, too most likely. Right?

**Comment by sampaiodiego** [comment]
just to make sure the env var was correctly set, have you seen a log like this on the server?
```
I20201201-10:49:47.389(-3) (migrations.js:120) Migrations: Rerunning version 179
I20201201-10:49:47.390(-3) (migrations.js:120) Migrations: Running up() on version 179
I20201201-10:49:47.599(-3)? DM rooms schema migration 0/21
I20201201-10:49:47.604(-3) (migrations.js:120) Migrations: Finished migrating.
```

**Comment by sampaiodiego** [comment]
yes, I guess.. 🙈 sry, it was long time ago since I last installed rocket.chat manually.. but look at rocket.chat server logs (which the default config says `syslog` so I wonder if they are saved on `/var/log`)

**Comment by TheWrongGuy** [comment]
Okay it seems that the Migration didn't run. I will experiment with the env variable.

**Comment by TheWrongGuy** [comment]
In the logs I can only see "not migrating, already at version 211", so the environment variable just doesnt workt. I added it to the End on Environment=MONGO_URL... and so on in /lib/systemd/system/rocketchat.service. Also this page isn't to helpful for me, unfortunately: https://docs.rocket.chat/guides/administrator-guides/settings-via-env-vars#managing-settings-using-environment-variables

Where is the proper place to define the environment variables for rocketchat. Globally in Unix maybe. I will try this asap.

**Comment by sampaiodiego** [comment]
if you followed this doc https://docs.rocket.chat/installation/manual-installation/ubuntu looking at the service that has the following line:

```
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://localhost:3000/ PORT=3000
```

in this case you have to append to the end of the **same line**, so it would look like this (scroll to the right 😬 ):
```
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://localhost:3000/ PORT=3000 MIGRATION_VERSION=179,rerun
```

**Comment by TheWrongGuy** [comment]
I'm pretty sure I did this the first try. This time however it seems to have an effect. Unfortunately the sidebar stays broken. Do you have a date when the hotfix will be in the stable server version?

Output in Logs:

{"line":"120","file":"migrations.js","message":"Migrations: Rerunning version 179","time":{"$date":1606907923628},"level":"info"}
Dec  2 12:18:43 centos-7 rocketchat: {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 179","time":{"$date":1606907923643},"level":"info"}
Dec  2 12:18:43 centos-7 rocketchat: DM rooms schema migration 0/667
Dec  2 12:18:45 centos-7 rocketchat: {"line":"120","file":"migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1606907925332},"level":"info"}
Dec  2 12:18:50 centos-7 rocketchat: Updating process.env.MAIL_URL

**Comment by sampaiodiego** [comment]
oh, interesting, it didn't fix the issue 🤔 
the release with a fix will be cut either today or tomorrow. I'm holding it on a little bit to add another fix.

**Comment by TheWrongGuy** [comment]
Hey Diego, @sampaiodiego 

I'm running 3.9.1 in the productive environment now and the sidebar still works, so thanks again for the quick fix. However I'm encountering another issue now, which I hoped would be fixed by this upgrade since there was a case open already about wrong user status in sidebars. (Issue #19209) I feels like the people with wrong status before are now the ones we have the issues with.

For many people I have "@" symbols next to their names instead of the status, however for some it works correctly. On the user Info screen the status is correct, but gets lost to the sidebar and the top bar. I already reran 179 migration in the test environment, which didn't help. Do you have another idea? Should I open another Github issue regarding this? I thought I would ask here first, since It maybe has something to do with the missing UIDs.

<img width="1003" alt="UserStatusWrongSidebar" src="https://user-images.githubusercontent.com/72255550/101501440-06e93800-3970-11eb-9936-80c65ee219c0.png">

**Comment by sampaiodiego** [comment]
it is weird to me it still shows `@` sign on side nav.. is this supposed to happen @ggazzo ?

anyways, @TheWrongGuy please definitely open a new issue, I don't think this is related. I haven't seen this happening before.

**Comment by TheWrongGuy** [comment]
@sampaiodiego Thank you for the swift response. I opened a new Issue #19809.

Best regards.
