### ISSUE TITLE
[Regression] Attachment sizes do not respect aspect ratios

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#20546]
### Description:

The new attachment embeds do not respect the aspect ratio of images. 

### Steps to reproduce:

1. Upload an image that is taller than it is wide
2. Boom

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/106509990-8a646880-648b-11eb-8eaf-46bce8f19f33.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/106509820-51c48f00-648b-11eb-929c-f49b37a91abe.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Additional context

Changing width to max-width and height to max-height helps!

![image](https://user-images.githubusercontent.com/6295044/106509890-67d24f80-648b-11eb-974e-d1eb66281e9f.png)

https://github.com/RocketChat/Rocket.Chat/blob/9b33bbe5d01fca435a52c2698a0a5409c3b0b7e7/client/components/Message/Attachments/context/AttachmentContext.tsx#L16
https://github.com/RocketChat/Rocket.Chat/blob/0872682d4c44d2aef20d24b87fc8fdd6d60bd639/client/components/Message/Attachments/providers/AttachmentProvider.tsx#L20
https://github.com/RocketChat/Rocket.Chat/blob/fea272a62b9c6bff9e7baccb8e10a355c3f47731/client/components/Message/Attachments/Files/ImageAttachment.tsx#L26

**Comment by wreiske** [comment]
Also, why is everything `!important` ??? I can't fix anything locally with custom CSS when everything is important :(.

**Comment by ggazzo** [comment]
hey @wreiske about the !important its a generated css, and we should not trust on these classes, they can (and will) change, and you cannot predict. 
your intention, was kinda exactly that: do not encourage customizations by selectors or specificity (because they can change very easily). but using vars .. of course its not all customizations that will be possible, but it was more or less your objective.

more than that, for some time we had some issues by the generated order being 'unordered' so we used important to solve. nowadays maybe we could remove the `important` but still you should not use the rcx-css-something =/

I will provide a properly fix to that

**Comment by yash-rajpal** [comment]
This is very similar to issue #20307 . I looked deeply into this issue, but wasn't able to fix it. I will report my findings as that maybe useful to solve this issue.
For example look at this screenshot - 
![image](https://user-images.githubusercontent.com/58601732/106600433-6fbfeb80-6580-11eb-9864-e999b7d89e9c.png)

The size of this image is - height: 4000 pixels and width is 1846 pixels as seen in screenshot below of image properties-
![image](https://user-images.githubusercontent.com/58601732/106601062-38057380-6581-11eb-88d9-dd050d15dada.png)

But when this image is rendered the height and width is interchanged which results in weird aspect ratio. I logged the imageDimensions value in ImageAttachment.tsx and got the interchanged value -
![image](https://user-images.githubusercontent.com/58601732/106601617-dc87b580-6581-11eb-9911-790ecec7f1f6.png)

Also, one more thing to not is, when I try to upload this Image, image will be shown as inverted in filePicker, I don't know if this has to do something with this issue. This can be seen in screenshot below - 
![image](https://user-images.githubusercontent.com/58601732/106602403-f1b11400-6582-11eb-8bd1-362a455b186c.png)


To debug this issue I looked into FileUpload of client and server, sendFileMessage method from sendFileMessage.js file, rooms.upload api call in rooms.js (here sendFileMessage method is called to save file to db). After looking into all these files and related files to these I am still not able to debug this issue.

It would be very helpful @ggazzo if you can guide me in right direction for this issue. :)

**Comment by tiagoevanp** [comment]
@yash-rajpal Can you send me the photo that causes that problem for some tests? I can't reproduce the issue...

**Comment by wreiske** [comment]
@tiagoevanp 

<img width="626" alt="Screen Shot 2021-02-08 at 11 29 45 AM" src="https://user-images.githubusercontent.com/6295044/107264996-f7827b80-6a00-11eb-861c-4e260590ed30.png">

<img width="621" alt="Screen Shot 2021-02-08 at 11 30 29 AM" src="https://user-images.githubusercontent.com/6295044/107265067-0ff29600-6a01-11eb-8ba5-7f02a331925a.png">

Example file:
![test](https://user-images.githubusercontent.com/6295044/107265091-16810d80-6a01-11eb-8338-b54cbd7233a3.gif)

**Comment by yash-rajpal** [comment]
@tiagoevanp I just checked again, now this image is uploaded correctly and dimensions of height and width are assigned correctly.
I think some Pull request introduced the orientation check and assigned the values correctly so, I think issue is resolved.

**Comment by pierre-lehnen-rc** [comment]
Can confirm the error is still present, at least while previewing on the webclient. The image itself doesn't seem to be changed, it's only displayed with the wrong size on the webclient preview.

**Comment by tiagoevanp** [comment]
As I see, the problem persists with gif images... Thanks for reply, I will find a solution for that asap.

**Comment by FrankDaze** [comment]
I still have the same problem with a jpg in Rocket.Chat V4.4

**Comment by wreiske** [comment]
### Example 1 with giphy

![image](https://user-images.githubusercontent.com/6295044/153910663-a3b6763a-a22a-42ff-a3e5-54085b5c95f1.png)
![image](https://user-images.githubusercontent.com/6295044/153910720-e699e14a-58c9-4d1b-91ac-38276af58d1a.png)

### Example 2 with image embeds from API
![image](https://user-images.githubusercontent.com/6295044/153910957-4fecf629-dabc-49fa-ac43-17cc6efcedfd.png)
![image](https://user-images.githubusercontent.com/6295044/153910995-44165ed3-b860-43f9-b576-cf054a87b99a.png)

**Comment by D34DC3N73R** [comment]
I have this same issue with the tenor app as well
![image](https://user-images.githubusercontent.com/9123670/156946705-1bcddf82-431b-433a-8ed3-2d7efc31198a.png)
![image](https://user-images.githubusercontent.com/9123670/156946730-e3a2c8ad-45b7-481a-b4cb-8d30088fd3da.png)
![tenor](https://user-images.githubusercontent.com/9123670/156946745-99359ca4-dc38-40a2-9ce0-5c1b017f057e.gif)

**Comment by thrakks** [comment]
Still Broken as of 4.8.0 
Server Version:
![image](https://user-images.githubusercontent.com/7259522/171790297-be1c7cdf-81ab-49a6-beb5-dc068e002572.png)

Expected Ratio:
![image](https://user-images.githubusercontent.com/7259522/166853336-b49058eb-7a2f-4004-9ae1-8dc0df49fbb3.png)

Actual Ratio:
![image](https://user-images.githubusercontent.com/7259522/166853302-7e4e2c28-2a47-4f97-9ced-fdc81333fe50.png)

**Comment by D34DC3N73R** [comment]
Still broken in RC 5.0
<img width="473" alt="image" src="https://user-images.githubusercontent.com/9123670/181627340-ebbe5b97-735f-4a53-aec4-6d199400b723.png">


expected ratio
<img width="200" alt="image" src="https://user-images.githubusercontent.com/9123670/181627427-f5636c43-d3f4-4266-a866-e4ddcbb41ae2.png">

original gif
![tenor](https://user-images.githubusercontent.com/9123670/181627576-9c292fd5-6cf0-4dcd-9680-a04c47bf0b0f.gif)


server info
<img width="181" alt="image" src="https://user-images.githubusercontent.com/9123670/181627679-e580b60d-c7f5-417b-99fe-1f68b77f95b0.png">

**Comment by D34DC3N73R** [comment]
It's not perfect, but this css helps out a ton while waiting for a fix
```
.gallery-item {
    height: auto;
}

picture[class*="rcx-css"]  {
  height: auto !important;
}
```

##examples
wide
<img width="542" alt="image" src="https://user-images.githubusercontent.com/9123670/181644823-0611a6ad-679e-4b75-a0fd-fbe54c302672.png">


tall
<img width="427" alt="image" src="https://user-images.githubusercontent.com/9123670/181645274-660860e9-ba52-4ee6-bfb8-9a7d80134234.png">


gif
<img width="541" alt="image" src="https://user-images.githubusercontent.com/9123670/181645218-356179d4-039b-4874-a38f-a24e8787e393.png">


(original gif)
![tenor3](https://user-images.githubusercontent.com/9123670/181645312-f6ac7449-d92e-45cf-ade7-7414e2e80eb1.gif)

**Comment by thrakks** [comment]
> ```
> .gallery-item {
>     height: auto;
> }
> 
> picture[class*="rcx-css"]  {
>   height: auto !important;
> }
> ```

@D34DC3N73R Yep, that fixed it for me well enough. You're my hero!

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/224904231-fbd63e16-bbc3-492b-9f67-fe61416dbec6.png)

This is even worse in 6.0.0. Notice how small the preview images are?

![image](https://user-images.githubusercontent.com/6295044/224904334-4a58d896-d564-4cb2-80d8-62e8ae30473e.png)

**Comment by D34DC3N73R** [comment]
This is the latest that I'm using with RC 6.1.3. It gets rid of the space above and below gifs wider than a 1:1 aspect ratio.

```
.gallery-item {
    height: auto;
}

picture[class*="rcx-css"]  {
  height: auto !important;
  border-width: 0 !important;
  background: transparent !important;
  position: relative !important;
}

div[class*="rcx-css"]  {
  padding-block-start: inherit !important;
}
```
<img width="388" alt="image" src="https://user-images.githubusercontent.com/9123670/232931192-5f052544-fa0d-43b4-aeb4-6b445705cd76.png">

**Comment by friedrichkeydel** [comment]
Why is this easy fix still no part of a current release version?

**Comment by wreiske** [comment]
yes, still a problem on Version 7.4.1

![Image](https://github.com/user-attachments/assets/937984c0-ec0f-49ee-bf38-b82b85853268)

**Comment by mprytoluk** [comment]
First of all, thank you, everyone, for your contributions!

I'm currently on version **7.9**.

In my tests, the rule `overflow: visible !important;` doesn't do anything to images, while it breaks some things on the UI (like threads "side-visualization" and message forwarding with images, as both overflow vertically).

I'm using this css, based on previous contributions, and it seems to work pretty well without noticeable side effects:

```css
.gallery-item {
    height: auto;
}

picture[class*="rcx-css"]  {
  height: auto !important;
  border-width: 0 !important;
  background: transparent !important;
  position: relative !important;
}

div[class*="rcx-css"]:has(.gallery-item) {
    padding-block-start: inherit !important;
}
```
