### ISSUE TITLE
Webhook is not working for the new line \n for RC 3.12.1

### ISSUE THREAD

**Issue by Cancer-zern** [RocketChat/Rocket.Chat#21040]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 3.12.1
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: 3v and 2v
- Operating System: Windows 10 20H2

### Additional context

Today when my RC server has been updated i got this issue.
I have Zabbix Server and sending notification via webhooks to the channel and after the last update from v3.10.5 to 3.12.1 i got this issue.
was
```
PROBLEM: Response time is too high on PROXY (Warning)
Date: 2021.03.09 09:46:05
Latest value: 2s 297ms
```

now
```
PROBLEM: Response time is too high on PROXY (Warning) Date: 2021.03.09 
09:46:05 Latest value: 2s 297ms
```

Message what am sending to
```[{TRIGGER.NAME} ({TRIGGER.SEVERITY})](https://zabbix.example.com/events.php?triggerid={TRIGGER.ID}&filter_set=1)\nDate: {EVENT.DATE} {EVENT.TIME}\nLatest value: {ITEM.VALUE1}```

for example
`@username 'PROBLEM' 'This is a test of something being wrong!\n123'`

the message is like that
`PROBLEM: This is a test of something being wrong!123`

but RC app for android is showing fine/okay, the problem for web browser and desktop app.

**Comment by Cancer-zern** [comment]
Script
for Slack it's working, for RC current version is broken

```
#!/bin/bash

# Slack incoming web-hook URL and user name
url='https://ntchat.example.com/hooks/boxzaY12ppknksasasatPdsasasdasdasdasdasdasdasdasda'             # example: https://hooks.slack.com/services/QW3R7Y/D34DC0D3/BCADFGabcDEF123
username='Zabbix Monitoring'

## Values received by this script:
# To = $1 (Slack channel or user to send the message to, specified in the Zabbix web interface; "@username" or "#channel")
# Subject = $2 (usually either PROBLEM {HOST.NAME} or RECOVERY {HOST.NAME}
# Message = $3 (whatever message the Zabbix action sends, preferably something like "Zabbix server is unreachable for 5 minutes - Zabbix server (127.0.0.1)")

# Get the Slack channel or user ($1), Zabbix subject (hopefully either PROBLEM or RECOVERY), and the server in question
to="$1"
subject=$(echo $2|cut -d' ' -f1) # The alert type is before the space, server after, eg
server=$(echo $2|cut -d' ' -f2-) #      "Subject: PROBLEM SomeDatabaseServer01"

# Set up the alert type (future flexibility)
if [ "$subject" == 'OK' ]; then
        type="R"
elif [ "$server" == 'Information' ]; then
        type="I"
elif [ "$server" == 'Warning' ]; then
        type="W"
elif [ "$server" == 'Average' ]; then
        type="A"
elif [ "$server" == 'High' ]; then
        type="H"
elif [ "$server" == 'Disaster' ]; then
        type="D"
else
        type="N"
fi

# Change message emoji, color, and (friendly) status depending on the subject
if [ $type == 'R' ]; then  # Triggered by 'RECOVERY' above
        emoji=':smile_troll:'    # A smile,
        color="#20E020"    # and red text
elif [ $type == 'I' ]; then  # Triggered by 'PROBLEM' above
        emoji=':om_troll:'
        color="#20D6E0"
elif [ $type == 'W' ]; then  # Triggered by 'PROBLEM' above
        emoji=':om_troll:'
        color="#FAEFA6"
#        color="#E0DC20"
elif [ $type == 'A' ]; then  # Triggered by 'PROBLEM' above
        emoji=':om_troll:'
        color="#FEB48B"
#        color="#E08920"
elif [ $type == 'H' ]; then  # Triggered by 'PROBLEM' above
        emoji=':om_troll:'
        color="#E02059"
elif [ $type == 'D' ]; then  # Triggered by 'PROBLEM' above
        emoji=':om_troll:'
        color="#E02020"
else
        emoji=':ghost:'
        color="#808080"
fi

# The message that we want to send to Slack is the "subject" value ($2 / $subject - that we got earlier)
#  followed by the message that Zabbix actually sent us ($3)
message="${subject}: $3"

# Build our JSON payload and send it as a POST request to the Slack incoming web-hook URL
# See https://api.slack.com/docs/formatting for formatting details
payload="payload={
        \"channel\": \"${to}\",
        \"username\": \"${username}\",
        \"icon_emoji\": \"${emoji}\",
        \"attachments\": [
           {
                \"fallback\": \"${message}\",
                \"text\": \"${message}\",
                \"color\": \"${color}\",
                \"mrkdwn_in\": [ \"text\" ]
           }
        ] }"

/usr/bin/curl -m 5 --data-urlencode "${payload}" $url
```

**Comment by Cancer-zern** [comment]
but RC app for android is showing fine/okay, the problem for web browser and desktop app.

**Comment by minix-it** [comment]
Hi there, i confirm all. Since 3.12.1 community edition,  \n in webhooks isnt honored in web and desktop app

**Comment by buschmann** [comment]
Anybody know??
What was the last Version with old licence model ??

**Comment by fdellwing** [comment]
I can confirm this issue, it does work if it is wrapped in something like a code block. But not as plain text.

**Comment by Cancer-zern** [comment]
I've updated to 3.13.1 and still the same issue.

**Comment by Exordian** [comment]
Emoji/Markdown rendering is broken as well

**Comment by Cancer-zern** [comment]
v3.14.4 has the same issue

**Comment by phuongnguyen2311** [comment]
![image](https://user-images.githubusercontent.com/5517848/126947544-b635ab73-9c60-4d86-8ba4-87b90a9b68f1.png)
![image](https://user-images.githubusercontent.com/5517848/126947570-b613e318-d66d-4c0a-80aa-d9547575cc2d.png)
I has problem same this, because we have upgrade version rocketchat to 3.16.3 then break "\n" not working 
how can fixed this issue?

**Comment by fdellwing** [comment]
@phuongnguyen2311 The `<br/>` will be fixed by #22727

**Comment by phuongnguyen2311** [comment]
> @phuongnguyen2311 The `<br/>` will be fixed by #22727

![image](https://user-images.githubusercontent.com/5517848/126948682-0987d9ab-7c4a-4f3d-baa7-3b5e26d2648a.png)
i will try with "<br/>" in value but not working

**Comment by debdutdeb** [comment]
Fixed in 3.17.0 

Closing.

**Comment by fdellwing** [comment]
@debdutdeb Sorry to say this, but this issue is not fixed with 3.17.0. New lines (`\n`) in attachments are still ignored/filtered out. Someone overtook this issue with the `<br/>` issue, that is indeed fixed in 3.17.0, but the original issue still persists.

**Comment by debdutdeb** [comment]
Hmm - I'll take a look at this later today Fabian. I'll reopen the issue if it's still there. Whatever happens, I'll let you know 🙂

**Comment by fdellwing** [comment]
@debdutdeb 

You can use this very simple test script to reproduce the problem:

```
import requests

data = {
    "text": f"Testhook:",
    "attachments": [
        {
            "text": "First Line\nSecond Line\nThird Line",
            "fields": [
                {
                    "short": True,
                    "title": "",
                    "value": f"[Link anyone?](http://example.com)",
                }
            ]
        }
    ]
}

requests.post("url to webhook", json=data)
```

The newlines in the attachment text will be replaced by spaces in the rendered output.

**Comment by zdumitru** [comment]
Confirming- It's not fixed. Issue needs to be reopened. New lines are replaced with the spaces, which is wrong.

**Comment by Cancer-zern** [comment]
Yeah, confirm, 3.17.0 this issue is not fixed

**Comment by debdutdeb** [comment]
Hey Dumitru, thanks for the ping at open. Sorry for not being around for a while - a lot of stuff's been going around I'm sure you guys know about already. 

Anyway, reopning this, thanks.

**Comment by qamaraden** [comment]
We are on version 3.18.2 and also getting this issue. All our newlines (\n) don't work

**Comment by Cancer-zern** [comment]
4.6.3 same issue

**Comment by ankar84** [comment]
Looks like it is related to this issue https://github.com/RocketChat/Rocket.Chat/issues/22732

**Comment by ankar84** [comment]
And according to these https://github.com/RocketChat/Rocket.Chat/pull/24924#issuecomment-1132007512 it's not a bug, but a feature (by design). I'm not agree with that for sure!

**Comment by Cancer-zern** [comment]
./zabbix_rocketchat @UserName 'OK' 'This is a test of something being wrong\n..222'
![image](https://user-images.githubusercontent.com/68541237/176359427-6b12ad8a-c4d0-472c-a4b9-1d4f8f14de0c.png)

./zabbix_rocketchat @UserName 'OK' 'This is a test of something being wrong\n\n..222'
![image](https://user-images.githubusercontent.com/68541237/176359532-55fa2762-7a65-427c-a5d6-2cc287b98e78.png)

I think It's not a feature it's a bug

**Comment by Irqendjemand** [comment]
Was this fixed? Cause I have the same problem in Version 7.10.0 newlines and block quotes are correctly displayed in the android app but not in the web version:
Problem started at 20:59:22 on 2026.02.17 Severity: Average Host: WinServer

> Problem: Windows: "GoogleUpdaterService144.0.7547.0" (Google Updater Service (GoogleUpdaterService144.0.7547.0)) is not running (startup type automatic) > Operational data: Stopped (6)

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/38983
