### ISSUE TITLE
LDAP Failing Silently

### ISSUE THREAD

**Issue by Kelwing** [RocketChat/Rocket.Chat#2205]
I configured LDAP against my OpenLDAP server.  It successfully binds using the proxy account.  It then says it is attempting to bind with the correct users DN, but still displays a login error on the login screen.  The wiki says this can be caused by an internal user matching the LDAP user, but I have only one account and its a temp account not matching any LDAP users.  Is there any other reason why it might fail silently?

**Comment by engelgabriel** [comment]
What version of Rocket.Chat?

**Comment by Kelwing** [comment]
Sorry, did a docker install with the docker-compose file in the repository.

**Comment by mrogaski** [comment]
I'm seeing the same issue after moving from 0.16.0 to 0.17.0.  It looks like LDAP binding is succeeding, but new users are not being added to the DB and are getting an authentication failure message.  I haven't found any exiting users affected.

These are logs for two users, the first one was in the DB previously and is able to log in.  The second is a user logging in for the first time and failing.

```
I20160213-03:15:28.164(0) Bind before search cn=xxxxxx,ou=auth,dc=aie-guild,dc=org xxxxxxxxxx 
I20160213-03:15:28.174(0) LDAP search dn ou=people,dc=aie-guild,dc=org 
I20160213-03:15:28.178(0) LDAP search options { filter: '(&(objectClass=person)(uid=stigg))', scope: 'sub' } 
I20160213-03:15:28.255(0) Attempt to bind uid=stigg,ou=people,dc=aie-guild,dc=org 
I20160213-03:16:59.731(0) Bind before search cn=xxxxxx,ou=auth,dc=aie-guild,dc=org xxxxxxxxxx 
I20160213-03:16:59.735(0) LDAP search dn ou=people,dc=aie-guild,dc=org 
I20160213-03:16:59.736(0) LDAP search options { filter: '(&(objectClass=person)(uid=semetye))', scope: 'sub' } 
I20160213-03:16:59.800(0) Attempt to bind uid=Semetye,ou=people,dc=aie-guild,dc=org 
```

**Comment by mrogaski** [comment]
OK, here's three cases with the Rocket.Chat logs and the LDAP logs.

1. Log in as "stigg", correct password.  SUCCESS.

```
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=0 BIND dn="cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org" method=128
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=0 BIND dn="cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org" mech=SIMPLE ssf=0
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=0 RESULT tag=97 err=0 text=
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=1 SRCH base="ou=people,dc=aie-guild,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(uid=stigg))"
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=2 BIND anonymous mech=implicit ssf=0
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=2 BIND dn="uid=stigg,ou=people,dc=aie-guild,dc=org" method=128
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=2 BIND dn="uid=stigg,ou=people,dc=aie-guild,dc=org" mech=SIMPLE ssf=0
Feb 13 15:56:10 copper slapd[17325]: conn=235670 op=2 RESULT tag=97 err=0 text=

I20160213-15:56:10.823(0) Bind before search cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org XXXXXXXXXXXXXXXXXXXX 
I20160213-15:56:10.826(0) LDAP search dn ou=people,dc=aie-guild,dc=org 
I20160213-15:56:10.827(0) LDAP search options { filter: '(&(objectClass=person)(uid=stigg))', scope: 'sub' } 
I20160213-15:56:10.834(0) Attempt to bind uid=stigg,ou=people,dc=aie-guild,dc=org 
```

2. Log in as "Semetye", wrong password. FAILURE (as expected).

```
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=0 BIND dn="cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org" method=128
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=0 BIND dn="cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org" mech=SIMPLE ssf=0
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=0 RESULT tag=97 err=0 text=
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=1 SRCH base="ou=people,dc=aie-guild,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(uid=semetye))"
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=2 BIND anonymous mech=implicit ssf=0
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=2 BIND dn="uid=Semetye,ou=people,dc=aie-guild,dc=org" method=128
Feb 13 15:57:51 copper slapd[17325]: conn=235676 op=2 RESULT tag=97 err=49 text=

I20160213-15:57:51.449(0) Bind before search cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org XXXXXXXXXXXXXXXXXXXX 
I20160213-15:57:51.451(0) LDAP search dn ou=people,dc=aie-guild,dc=org 
I20160213-15:57:51.452(0) LDAP search options { filter: '(&(objectClass=person)(uid=semetye))', scope: 'sub' } 
I20160213-15:57:51.458(0) Attempt to bind uid=Semetye,ou=people,dc=aie-guild,dc=org 
I20160213-15:57:51.460(0) { [InvalidCredentialsError: Invalid Credentials]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
I20160213-15:57:51.462(0) { [Error: Invalid Credentials [49]]   error: 49,   reason: 'Invalid Credentials',   details: undefined,   message: 'Invalid Credentials [49]',   errorType: 'Meteor.Error' } 
I20160213-15:57:51.463(0) { [Error: Invalid Credentials [49]]   error: 49,   reason: 'Invalid Credentials',   details: undefined,   message: 'Invalid Credentials [49]',   errorType: 'Meteor.Error' } 
I20160213-15:57:51.464(0) [LDAP] Falling back to standard account base
```

3. Log in as "Semetye", correct password. FAILURE.

```
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=0 BIND dn="cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org" method=128
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=0 BIND dn="cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org" mech=SIMPLE ssf=0
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=0 RESULT tag=97 err=0 text=
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=1 SRCH base="ou=people,dc=aie-guild,dc=org" scope=2 deref=0 filter="(&(objectClass=person)(uid=semetye))"
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=2 BIND anonymous mech=implicit ssf=0
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=2 BIND dn="uid=Semetye,ou=people,dc=aie-guild,dc=org" method=128
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=2 BIND dn="uid=Semetye,ou=people,dc=aie-guild,dc=org" mech=SIMPLE ssf=0
Feb 13 16:00:14 copper slapd[17325]: conn=235680 op=2 RESULT tag=97 err=0 text=


I20160213-16:00:14.729(0) Bind before search cn=XXXXXXXXXX,ou=auth,dc=aie-guild,dc=org XXXXXXXXXXXXXXXXXXXX 
I20160213-16:00:14.737(0) LDAP search dn ou=people,dc=aie-guild,dc=org 
I20160213-16:00:14.739(0) LDAP search options { filter: '(&(objectClass=person)(uid=semetye))', scope: 'sub' } 
I20160213-16:00:14.754(0) Attempt to bind uid=Semetye,ou=people,dc=aie-guild,dc=org 
```

**Comment by engelgabriel** [comment]
We will release the version 0.18.0 tomorrow. Can you guys try again with that version?

**Comment by mrogaski** [comment]
I'll be able to test it.

**Comment by Kelwing** [comment]
Me too!

**Comment by rodrigok** [comment]
We released the version 0.18.0 with the new LDAP code, can you test?

**Comment by Kelwing** [comment]
Just tested it, and it worked!  Thank you!

**Comment by mrogaski** [comment]
It's working for me, too.

```
I20160215-15:13:02.048(0) LDAP ? auth_info Authenticating uid=Semetye,ou=people,dc=aie-guild,dc=org 
I20160215-15:13:02.056(0) LDAP ? auth_info Authenticated uid=Semetye,ou=people,dc=aie-guild,dc=org 
I20160215-15:13:02.060(0) LDAP ? connection_info Disconecting 
I20160215-15:13:02.066(0) LDAPHandler ? info Querying user 
I20160215-15:13:02.071(0) LDAPHandler ? debug userQuery { username: 'semetye' } 
I20160215-15:13:02.079(0) LDAPHandler ? info User does not exists, creating semetye 
I20160215-15:13:02.320(0) LDAPHandler ? info Syncing user data 
I20160215-15:13:02.325(0) LDAPHandler ? debug user { username: 'semetye',   password: 'XXXXXXXXXX',   email: 'XXXXXXXXXX',   _id: 'kTMkeQjRDjrr2WYhh' } 
I20160215-15:13:02.342(0) LDAPHandler ? debug ldapUser { messageID: 2,   protocolOp: 100,   controls: [],   log:     { domain: null,      _events: {},      _maxListeners: 10,      _isSimpleChild: true,      _level: 30,      streams: [ [Object] ],      serializers:        { req: [Function: req],         res: [Function: res],         err: [Function: err] },      src: false,      fields:        { name: 'ldapjs',         component: 'client',         hostname: '2a18de2dbfa8',         pid: 1,         clazz: 'Client' } },   id: [Getter],   dn: [Getter],   type: [Getter],   json: [Getter],   objectName: 'uid=Semetye,ou=people,dc=aie-guild,dc=org',   attributes:     [ { type: 'uid',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'objectClass',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'sn',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'employeeType',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'cn',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'employeeNumber',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'displayName',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'mail',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] },      { type: 'userPassword',        _vals: [Object],        vals: [Getter/Setter],        buffers: [Getter],        json: [Getter] } ],   object: [Getter],   raw: [Getter],   _dn: [Getter],   connection:     { _connecting: false,      _handle: null,      _readableState:        { highWaterMark: 16384,         buffer: [],         length: 0,         pipes: null,         pipesCount: 0,         flowing: false,         ended: true,         endEmitted: true,         reading: false,         calledRead: true,         sync: false,         needReadable: true,         emittedReadable: false,         readableListening: false,         objectMode: false,         defaultEncoding: 'utf8',         ranOut: false,         awaitDrain: 0,         readingMore: false,         decoder: null,         encoding: null },      readable: false,      domain: null,      _events:        { finish: [Function: onSocketFinish],         _socketEnd: [Object],         readable: [Function] },      _maxListeners: 10,      _writableState:        { highWaterMark: 16384,         objectMode: false,         needDrain: false,         ending: true,         ended: true,         finished: true,         decodeStrings: false,         defaultEncoding: 'utf8',         length: 0,         writing: false,         sync: false,         bufferProcessing: false,         onwrite: [Function],         writecb: null,         writelen: 0,         buffer: [],         errorEmitted: false },      writable: false,      allowHalfOpen: false,      onend: null,      destroyed: true,      bytesRead: 402,      _bytesDispatched: 232,      _pendingData: null,      _pendingEncoding: '',      pipe: [Function],      addListener: [Function: addListener],      on: [Function: addListener],      pause: [Function],      resume: [Function],      read: [Function],      _consuming: true,      unbindMessageID: 4,      _idleNext: null,      _idlePrev: null,      _idleTimeout: -1,      write: [Function: writeAfterFIN] } } 
I20160215-15:13:02.356(0) LDAPHandler ? info Joining user to default channels 
```

**Comment by floriangoeldi** [comment]
Hi guys,

I still get the silent failing. I have everything configured correctly, but after a login, which is on the LDAP correct, it stays on "User does not exists, creating" and on the Login page I simply get the wrong credentials error. I use the version 19.0. Do you have an idea, why this is so?

![rocket chat screenshot](https://cloud.githubusercontent.com/assets/4731093/13244644/19bd803e-da08-11e5-8c3f-5d9dda36b8f4.png)

**Comment by rodrigok** [comment]
@floriangoeldi can you enable de debug logs?

`http://your.rc.server/admin/Logs`  -> `Log Level` -> `2 - Errors, Information and Debug`

**Comment by floriangoeldi** [comment]
@rodrigok First of all, thank you for your fast response!

I enabled them and after the login, the following is logged in the output window:

`LDAPHandler ➔ info Init login gof
LDAP ➔ Connection.info Init setup
LDAP ➔ Connection.info Connecting ldap://adserver.domain.ch:389
LDAP ➔ Connection.debug connectionOptions { url: 'ldap://adserver.domain.ch:389',
  timeout: 5000,
  connectTimeout: 10000,
  idleTimeout: 10000,
  reconnect: false }
LDAP ➔ Connection.info LDAP connected
LDAP ➔ Bind.info Binding admin user cn=LDAPProxy,ou=Domain Service Benutzer,dc=domain,dc=ch
LDAP ➔ Search.info Searching user gof
LDAP ➔ Search.debug searchOptions { filter: '(&(objectCategory=person)(objectclass=user)(|(sAMAccountName=gof)(mail=gof)))',
  scope: 'sub' }
LDAP ➔ Search.debug domain_base dc=domain,dc=ch
LDAP ➔ Search.info Search result count 1
LDAP ➔ Search.debug Search result [
  {
    "messageID": 2,
    "protocolOp": "SearchEntry",
    "objectName": "CN=Name,OU=Benutzer,OU=Team,OU=Technik,OU=Place,DC=domain,DC=ch",
    "attributes": [
      {
        "type": "objectClass",
        "vals": [
          "top",
          "person",
          "organizationalPerson",
          "user"
        ]
      },
      {
        "type": "cn",
        "vals": [
          "Fullname"
        ]
      },
      {
        "type": "sn",
        "vals": [
          "Surname"
        ]
      },
      {
        "type": "physicalDeliveryOfficeName",
        "vals": [
          "Place"
        ]
      },
      {
        "type": "telephoneNumber",
        "vals": [
          "Telephone Nr"
        ]
      },
      {
        "type": "givenName",
        "vals": [
          "name"
        ]
      },
      {
        "type": "initials",
        "vals": [
          "GOF"
        ]
      },
      {
        "type": "distinguishedName",
        "vals": [
          "CN=Name,OU=Benutzer,OU=Team,OU=Technik,OU=Place,DC=domain,DC=ch"
        ]
      },
      {
        "type": "instanceType",
        "vals": [
          "4"
        ]
      },
      {
        "type": "whenCreated",
        "vals": [
          "20150126082115.0Z"
        ]
      },
      {
        "type": "whenChanged",
        "vals": [
          "20160218134439.0Z"
        ]
      },
      {
        "type": "displayName",
        "vals": [
          "Fullname"
        ]
      },
      {
        "type": "uSNCreated",
        "vals": [
          "21496487"
        ]
      },
      {
        "type": "memberOf",
        "vals": [
          "CN=\\\\\\\\Team,OU=Gruppen,OU=Exchange,DC=domain,DC=ch",
          "CN=Grp1,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=Grp2,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=Grp3,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=\\\\\\\\Alle domain,OU=Gruppen,OU=Exchange,DC=domain,DC=ch",
          "CN=Grp4,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=\\\\\\\\Technik,OU=Gruppen,OU=Exchange,DC=domain,DC=ch",
          "CN=\\\\\\\\domain Place,OU=Gruppen,OU=Exchange,DC=domain,DC=ch",
          "CN=Grp5,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=Grp6,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=Grp7,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=Grp8,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=Grp9,CN=Users,DC=domain,DC=ch",
          "CN=Grp10,OU=Domain Gruppen,DC=domain,DC=ch",
          "CN=\\\\\\\\Entwicklung,OU=Gruppen,OU=Exchange,DC=domain,DC=ch"
        ]
      },
      {
        "type": "uSNChanged",
        "vals": [
          "31000871"
        ]
      },
      {
        "type": "department",
        "vals": [
          "Entwicklung"
        ]
      },
      {
        "type": "proxyAddresses",
        "vals": [
          "X400:C=DE;A= ;P=domain;O=Place;S=Surname;G=Name;I=GOF;",
          "SMTP:name.surname@domain.ch"
        ]
      },
      {
        "type": "homeMDB",
        "vals": [
          "CN=Postfachdatenbank Place,CN=Databases,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=domain,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=domain,DC=ch"
        ]
      },
      {
        "type": "mDBUseDefaults",
        "vals": [
          "TRUE"
        ]
      },
      {
        "type": "mailNickname",
        "vals": [
          "GOF"
        ]
      },
      {
        "type": "protocolSettings",
        "vals": [
          "POP3§0§§§§§§§§§§§§",
          "IMAP4§0§§§§§§§§§§§§"
        ]
      },
      {
        "type": "name",
        "vals": [
          "Surname Name"
        ]
      },
      {
        "type": "objectGUID",
        "vals": [
          "��\u0001\u0017})�C���U\u0007���"
        ]
      },
      {
        "type": "userAccountControl",
        "vals": [
          "512"
        ]
      },
      {
        "type": "badPwdCount",
        "vals": [
          "0"
        ]
      },
      {
        "type": "codePage",
        "vals": [
          "0"
        ]
      },
      {
        "type": "countryCode",
        "vals": [
          "0"
        ]
      },
      {
        "type": "badPasswordTime",
        "vals": [
          "131006845014552217"
        ]
      },
      {
        "type": "lastLogoff",
        "vals": [
          "0"
        ]
      },
      {
        "type": "lastLogon",
        "vals": [
          "131006934169607492"
        ]
      },
      {
        "type": "pwdLastSet",
        "vals": [
          "130987817501512391"
        ]
      },
      {
        "type": "primaryGroupID",
        "vals": [
          "513"
        ]
      },
      {
        "type": "objectSid",
        "vals": [
          "\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000!L�=5 �\u001fVM�\u0000]#\u0000\u0000"
        ]
      },
      {
        "type": "accountExpires",
        "vals": [
          "9223372036854775807"
        ]
      },
      {
        "type": "logonCount",
        "vals": [
          "3323"
        ]
      },
      {
        "type": "sAMAccountName",
        "vals": [
          "gof"
        ]
      },
      {
        "type": "sAMAccountType",
        "vals": [
          "805306368"
        ]
      },
      {
        "type": "showInAddressBook",
        "vals": [
          "CN=Globale Standardadressliste,CN=All Global Address Lists,CN=Address Lists Container,CN=domain,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=domain,DC=ch",
          "CN=Alle Benutzer,CN=All Address Lists,CN=Address Lists Container,CN=domain,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=domain,DC=ch"
        ]
      },
      {
        "type": "legacyExchangeDN",
        "vals": [
          "/o=domain/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=gof"
        ]
      },
      {
        "type": "userPrincipalName",
        "vals": [
          "gof@domain.ch"
        ]
      },
      {
        "type": "objectCategory",
        "vals": [
          "CN=Person,CN=Schema,CN=Configuration,DC=domain,DC=ch"
        ]
      },
      {
        "type": "mSMQSignCertificates",
        "vals": [
          "\u0002\u0000\u0000\u0000d\u0012�\u0017m\u000bF\u0007k�������[-�q�i�L��#����#H\u0003\u0000\u00000�\u0003D0�\u0002,�\u0003\u0002\u0001\u0002\u0002\u0004��ZU0\r\u0006\t*�H��\r\u0001\u0001\u0005\u0005\u00000d1\u00110\u000f\u0006\u0003U\u0004\u0007\u001e\b\u0000M\u0000S\u0000M\u0000Q1\u000b0\t\u0006\u0003U\u0004\n\u001e\u0002\u0000-1\u000b0\t\u0006\u0003U\u0004\u000b\u001e\u0002\u0000-1503\u0006\u0003U\u0004\u0003\u001e,\u0000B\u0000I\u0000X\u0000I\u0000\\\u0000g\u0000o\u0000f\u0000,\u0000 \u0000v\u0000s\u0000-\u0000m\u0000e\u0000l\u0000-\u0000t\u0000e\u0000s\u0000t\u000060\u001e\u0017\r150611124050Z\u0017\r230611124050Z0d1\u00110\u000f\u0006\u0003U\u0004\u0007\u001e\b\u0000M\u0000S\u0000M\u0000Q1\u000b0\t\u0006\u0003U\u0004\n\u001e\u0002\u0000-1\u000b0\t\u0006\u0003U\u0004\u000b\u001e\u0002\u0000-1503\u0006\u0003U\u0004\u0003\u001e,\u0000B\u0000I\u0000X\u0000I\u0000\\\u0000g\u0000o\u0000f\u0000,\u0000 \u0000v\u0000s\u0000-\u0000m\u0000e\u0000l\u0000-\u0000t\u0000e\u0000s\u0000t\u000060�\u0001\"0\r\u0006\t*�H��\r\u0001\u0001\u0001\u0005\u0000\u0003�\u0001\u000f\u00000�\u0001\n\u0002�\u0001\u0001\u0000�K��U��f���ӑN��)�\u0018R4&f�eH��_�\u0002!}J�\u001b[��M\u0012\u001aE�T��0�\u001c�H(�<�Ͼ�ަ�\u0017sl8���\u0016��\\\u0003y�ڳ�^�iz���q+\n]\u0015���9�轞c�g6�pH��Ļw��\u0002�i���c@��4�hӿFƎ�6oZ��1�\u000eǑ*x`�q�!�\u001f��b�\u0011FV��0$Rx�b6��\u001a�R,ks�����ȭk�p�W�n\u0013^~��\\u�VWל?�O��=�\br���p\b\f��|0�3>��%�[,\u001d���u\u001e�)�./r��Ծm+�]&I\u0003�T�M\u0002\u0003\u0001\u0000\u00010\r\u0006\t*�H��\r\u0001\u0001\u0004\u0005\u0000\u0003�\u0001\u0001\u0000tMa}�\u0007N\u000e�?A�%�9�ЧmU\r�GX�X��)\\G��ǃ�Я%\rY���������#���l����\u0000��my\u0002�ݸ]\u001ab�kŮ���Y�;�T\n*ҝx#�|��\u0014�C���$w�\u0011\u0011\u001f�Wc��;�F���\u001d�ڒ�z)��s�\u001a�?��ߣv\u0004U�\b\u000b\u001c��Rj�7�ܶl��J\u0019*�l��,\u001d\u0006D*$\u0000�+�]�C�;-��ꚺJ�7v��m[s�^\\��w\u0000�`�����V���ܱޖ�\u0019t���pN�)r\u0019j�~mt�\u001cR\u000b-���[��H\u000f\"'A-{�d�A����5e\u0002�C�n��ru\u0005\u00147�BA��&9\u0013��D���b����H\u0003\u0000\u00000�\u0003D0�\u0002,�\u0003\u0002\u0001\u0002\u0002\u0004��ZU0\r\u0006\t*�H��\r\u0001\u0001\u0005\u0005\u00000d1\u00110\u000f\u0006\u0003U\u0004\u0007\u001e\b\u0000M\u0000S\u0000M\u0000Q1\u000b0\t\u0006\u0003U\u0004\n\u001e\u0002\u0000-1\u000b0\t\u0006\u0003U\u0004\u000b\u001e\u0002\u0000-1503\u0006\u0003U\u0004\u0003\u001e,\u0000B\u0000I\u0000X\u0000I\u0000\\\u0000g\u0000o\u0000f\u0000,\u0000 \u0000v\u0000s\u0000-\u0000m\u0000e\u0000l\u0000-\u0000t\u0000e\u0000s\u0000t\u000060\u001e\u0017\r150806064542Z\u0017\r230806064542Z0d1\u00110\u000f\u0006\u0003U\u0004\u0007\u001e\b\u0000M\u0000S\u0000M\u0000Q1\u000b0\t\u0006\u0003U\u0004\n\u001e\u0002\u0000-1\u000b0\t\u0006\u0003U\u0004\u000b\u001e\u0002\u0000-1503\u0006\u0003U\u0004\u0003\u001e,\u0000B\u0000I\u0000X\u0000I\u0000\\\u0000g\u0000o\u0000f\u0000,\u0000 \u0000v\u0000s\u0000-\u0000m\u0000e\u0000l\u0000-\u0000t\u0000e\u0000s\u0000t\u000060�\u0001\"0\r\u0006\t*�H��\r\u0001\u0001\u0001\u0005\u0000\u0003�\u0001\u000f\u00000�\u0001\n\u0002�\u0001\u0001\u0000�\u000b\"�\u0012UX��0\u000bZHhQ�;k9/��ۖ��z�\u0001\u0001M�\u0013'\rs��I\u001fHB��7e���S� X�C�.\u0011Q���\u0013���o����^�\u0016Y�\u0004\u001a+�'�`��u�jW�\u001b�E�1\f-a�/�T�,귛���b-�e��)\u001baW�i�9��=��}�Z��\u0001D�$׵ЪR�5�ª\u0014�Uz����k� �F3�-~�w\u0011�O\n�\u0017����X7m��{#�٧�\t�(�iFq�ٙ�qL��^���\u001asv�2����ic�*����)�lM�z�� �8Ot\u0013\\�:}\u001f�\u0017%���;\u0004�\u0002\u0003\u0001\u0000\u00010\r\u0006\t*�H��\r\u0001\u0001\u0004\u0005\u0000\u0003�\u0001\u0001\u0000c�,e,��{���\n\u0006Ur0?����nU����\u0010؎���|�1����ќ�\"%��\u000f\u0005\u0018��\u0013\u0003q��;U���9V7�\u0012t\u0001��\u0013����#ٔo,����N���I��\u0006غi\u0016+��m\u0006��h�`�4�[�\t-��T�^0_=Ӥ��j�D\u0006�%F����\u0016��3hn�F���8��Ѵ��I=<\u000b��X��\u0011z~�e��@�\u000b¤'\u0014\u0016\u00183jZ\u0004�\u0006\u0013�\u000b\u0013ØF�e\u000f5N8�:Н���S)��V���/RX�|g�\u000e\u001eG�=�r�X0��xt��#�B�z��甝N�w�O\""
        ]
      },
      {
        "type": "mSMQDigests",
        "vals": [
          "e\u0002�C�n��ru\u0005\u00147�BA",
          "d\u0012�\u0017m\u000bF\u0007k�������"
        ]
      },
      {
        "type": "dSCorePropagationData",
        "vals": [
          "20151014074830.0Z",
          "16010101000001.0Z"
        ]
      },
      {
        "type": "lastLogonTimestamp",
        "vals": [
          "130999935671985830"
        ]
      },
      {
        "type": "msDS-AuthenticatedAtDC",
        "vals": [
          "CN=Server,OU=Domain Controllers,DC=domain,DC=ch"
        ]
      },
      {
        "type": "msTSExpireDate",
        "vals": [
          "20160304065533.0Z"
        ]
      },
      {
        "type": "msTSLicenseVersion",
        "vals": [
          "393216"
        ]
      },
      {
        "type": "msTSManagingLS",
        "vals": [
          "55041-402-5384645-84167"
        ]
      },
      {
        "type": "textEncodedORAddress",
        "vals": [
          "X400:C=DE;A= ;P=domain;O=Place;S=Surname;G=Name;I=GOF;"
        ]
      },
      {
        "type": "mail",
        "vals": [
          "Name.Surname@domain.ch"
        ]
      },
      {
        "type": "pager",
        "vals": [
          "pager-address"
        ]
      },
      {
        "type": "msExchHomeServerName",
        "vals": [
          "/o=domain/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=Mailserver"
        ]
      },
      {
        "type": "msExchMailboxSecurityDescriptor",
        "vals": [
          "\u0001\u0000\u0014�\u0014\u0000\u0000\u0000 \u0000\u0000\u0000,\u0000\u0000\u0000\\\u0000\u0000\u0000\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0005\n\u0000\u0000\u0000\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0005\n\u0000\u0000\u0000\u0002\u00000\u0000\u0002\u0000\u0000\u0000\u0002�\u0014\u0000\u0003\u0000\r\u0000\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0002�\u0014\u0000k\u0001\r\u0000\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0002\u0000\u001c\u0000\u0001\u0000\u0000\u0000\u0000\u0002\u0014\u0000\u0001\u0000\u0002\u0000\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0005\n\u0000\u0000\u0000"
        ]
      },
      {
        "type": "msExchUserAccountControl",
        "vals": [
          "0"
        ]
      },
      {
        "type": "msExchMailboxGuid",
        "vals": [
          "Ƀq9���N��J{}�H�"
        ]
      },
      {
        "type": "msExchPoliciesIncluded",
        "vals": [
          "74524229-099a-4d20-99f0-64c650d86cdc",
          "{26491cfc-9e50-4857-861b-0cb8df22b5d7}"
        ]
      },
      {
        "type": "msExchUMDtmfMap",
        "vals": [
          "reversedPhone:84805271814+",
          "emailAddress:3567426463534",
          "lastNameFirstName:465343567426",
          "firstNameLastName:356742646534"
        ]
      },
      {
        "type": "msExchMailboxTemplateLink",
        "vals": [
          "CN=Default MRM Policy,CN=Retention Policies Container,CN=domain,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=domain,DC=ch"
        ]
      },
      {
        "type": "msExchRecipientDisplayType",
        "vals": [
          "1073741824"
        ]
      },
      {
        "type": "msExchELCMailboxFlags",
        "vals": [
          "34"
        ]
      },
      {
        "type": "msExchSafeSendersHash",
        "vals": [
          "��K\u0002���\u0002r{�\u0014��h.\r��3��x=�zFA� �JI`�N�\u001dMUS08^\u000eh�pQ_یU�͎t\u0010����Q�C�\u0017Ă�\u0002�gL\u0012�Z�\u001d�"
        ]
      },
      {
        "type": "msExchUserCulture",
        "vals": [
          "de-DE"
        ]
      },
      {
        "type": "msExchVersion",
        "vals": [
          "88218628259840"
        ]
      },
      {
        "type": "msExchRecipientTypeDetails",
        "vals": [
          "1"
        ]
      },
      {
        "type": "msExchTextMessagingState",
        "vals": [
          "302120705",
          "16842751"
        ]
      },
      {
        "type": "msExchRBACPolicyLink",
        "vals": [
          "CN=Default Role Assignment Policy,CN=Policies,CN=RBAC,CN=domain,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=domain,DC=ch"
        ]
      },
      {
        "type": "msExchArchiveName",
        "vals": [
          "Compliance-Archiv - Surname Name"
        ]
      },
      {
        "type": "msExchArchiveGUID",
        "vals": [
          "\u0003\u0011\u0018�.NSA�\u0006z�뫋�"
        ]
      },
      {
        "type": "msExchArchiveDatabaseLink",
        "vals": [
          "CN=Archiv Place,CN=Databases,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=domain,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=domain,DC=ch"
        ]
      },
      {
        "type": "msExchWhenMailboxCreated",
        "vals": [
          "20151021041204.0Z"
        ]
      }
    ],
    "controls": []
  }
]
LDAP ➔ Auth.info Authenticating CN=Surname Name,OU=Benutzer,OU=Team,OU=Technik,OU=Place,DC=domain,DC=ch
LDAP ➔ Auth.info Authenticated CN=Surname Name,OU=Benutzer,OU=Team,OU=Technik,OU=Place,DC=domain,DC=ch
LDAP ➔ Connection.info Disconecting
LDAPHandler ➔ info Querying user
LDAPHandler ➔ debug userQuery { 'services.ldap.id': 'c1a601177d29ed4386aec55507e9ffd0' }
LDAPHandler ➔ debug userQuery { username: 'gof' }
LDAPHandler ➔ info User does not exists, creating gof
`

And thank you all for this amazing app! :)

**Comment by rodrigok** [comment]
Seems that you are getting error on user creation.

I added more logs, can you update to the latest develop version and try again?

**Comment by floriangoeldi** [comment]
I downloaded the version from `https://rocket.chat/releases/develop/download`.
Is this the correct version? Because I don't get more output than before, so it stucks at `User does not exists, creating gof`

**Comment by rodrigok** [comment]
Can we talk at demo.rocket.chat?

https://demo.rocket.chat/direct/rodrigo.nascimento

**Comment by floriangoeldi** [comment]
Yes of course! I sent you a message.

**Comment by floriangoeldi** [comment]
So @rodrigok and me could resolve the problem.

The problem was, that in our active directory every e-mail address was written in a camel case style. So we had e-mail addresses in this form: Name.Surname@Domain.ch

I had restricted the registration for the following domain only (in the Rocket.Chat settings `Accounts` => `Registration` => `Allowed Domains List`): `domain.ch`

So the user wasn't created, because the email domain didn't match. To fix this error you can either enter the restriction in this way: `domain.ch, Domain.ch` or you do it in a regex style: `[dD]omain.ch`, after this change, I was able to login.

Thanks to the latest ldap commit from @rodrigok it will now output the error, so if something like this happens again, it won't be silent anymore!

Thank you very much! :smile:

**Comment by rodrigok** [comment]
Thanks @floriangoeldi
