### ISSUE TITLE
Using Docker latest tag tried to downgrade to 3.14.5 from 3.15.0

### ISSUE THREAD

**Issue by jennettwheeler** [RocketChat/Rocket.Chat#22261]
### Description:

I auto update rocket chat by checking new images at the latest tag, but last night latest went from pointing to 3.15.0 to 3.14.5

I then got the following error:
```
(node:7) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
Setting default file store to AmazonS3
Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]
    at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)
    at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
    at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
    at module (server/startup/migrations/xrun.js:6:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/startup/migrations/index.js:1:4870)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/main.js:1:210)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/app/app.js:202236:15
    at /app/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:226:21
    at /app/bundle/programs/server/boot.js:464:7
    at Function.run (/app/bundle/programs/server/profile.js:280:14)
    at /app/bundle/programs/server/boot.js:463:13 {
  isClientSafe: true,
  error: "Can't find migration version 225",
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

Fixed by manually selecting 3.15.0 as my tag, but this breaks my update procedure.

IMO, the latest tag should never downgrade, but that doesn't mean bug fixes to older version can't be carried out (perhaps you could use more tags (e.g `3` for the latest major version, but no auto upgrades to `4`, and `3.14` for minor version, but no auto upgrade to `3.15`?

### Steps to reproduce:

1. Start at tag 3.15.0
2. Switch tag to latest

### Expected behavior:

Stays on 3.15.0 (or newer)

### Actual behavior:

`Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: DiskStation Manager 7.0 (linux)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 - x64
- MongoDB Version: 4.2.14 (wiredTiger)

**Comment by tom666-debug** [comment]
Confirmed, same issue here.  Dont know why they release 3.14.5 AFTER they have already released 3.15.0

**Comment by johncrisp** [comment]
Hi and thanks for reporting this and sorry for the inconvenience.

I'm sure this will get fixed.

I believe they added some performance enhancements to to 3.14.5 which is still supported. It isn't uncommon to release fixes to older versions.

Please note that It is not recommended to use the 'latest' tag for precisely this reason - this has occurred before.

It is much better to use a fixed tag and then upgrade on your own schedule.

**Comment by ankar84** [comment]
> Please note that It is not recommended to use the 'latest' tag for precisely this reason - this has occurred before.

Totally agree. It's always a bit risky.

**Comment by johncrisp** [comment]
I will try and get the docs and compose file modified as it really shouldn't use latest.

Seen this happen before.

**Comment by rynr** [comment]
Is there something I can do now?
I assume, the search for 225 comes from this entry in the database, can I just change it?
```
rs0:PRIMARY> db.migrations.find()
{ "_id" : "control", "locked" : true, "version" : 225, "buildAt" : "2021-05-28T04:16:32.940Z", "lockedAt" : ISODate("2021-06-07T10:03:30.800Z") }
```

**Comment by jennettwheeler** [comment]
There are ways to automate the major minor work. Depends how they build their docker images.

**Comment by sampaiodiego** [comment]
I'm sorry about that guys, it was fixed already and `latest` is pointing back to `3.15.0`

**Comment by ruvenss** [comment]
> > Please note that It is not recommended to use the 'latest' tag for precisely this reason - this has occurred before.
> 
> Totally agree. It's always a bit risky.

Then it shouldn't be name as production, sorry but this is not a good argument

**Comment by ruvenss** [comment]
> ### Description:
> I auto update rocket chat by checking new images at the latest tag, but last night latest went from pointing to 3.15.0 to 3.14.5
> 
> I then got the following error:
> 
> ```
> (node:7) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
> Setting default file store to AmazonS3
> Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]
>     at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)
>     at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
>     at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
>     at module (server/startup/migrations/xrun.js:6:13)
>     at fileEvaluate (packages/modules-runtime.js:336:7)
>     at Module.require (packages/modules-runtime.js:238:14)
>     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
>     at module (server/startup/migrations/index.js:1:4870)
>     at fileEvaluate (packages/modules-runtime.js:336:7)
>     at Module.require (packages/modules-runtime.js:238:14)
>     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
>     at module (server/main.js:1:210)
>     at fileEvaluate (packages/modules-runtime.js:336:7)
>     at Module.require (packages/modules-runtime.js:238:14)
>     at require (packages/modules-runtime.js:258:21)
>     at /app/bundle/programs/server/app/app.js:202236:15
>     at /app/bundle/programs/server/boot.js:401:38
>     at Array.forEach (<anonymous>)
>     at /app/bundle/programs/server/boot.js:226:21
>     at /app/bundle/programs/server/boot.js:464:7
>     at Function.run (/app/bundle/programs/server/profile.js:280:14)
>     at /app/bundle/programs/server/boot.js:463:13 {
>   isClientSafe: true,
>   error: "Can't find migration version 225",
>   reason: undefined,
>   details: undefined,
>   errorType: 'Meteor.Error'
> }
> ```
> 
> Fixed by manually selecting 3.15.0 as my tag, but this breaks my update procedure.
> 
> IMO, the latest tag should never downgrade, but that doesn't mean bug fixes to older version can't be carried out (perhaps you could use more tags (e.g `3` for the latest major version, but no auto upgrades to `4`, and `3.14` for minor version, but no auto upgrade to `3.15`?
> 
> ### Steps to reproduce:
> 1. Start at tag 3.15.0
> 2. Switch tag to latest
> 
> ### Expected behavior:
> Stays on 3.15.0 (or newer)
> 
> ### Actual behavior:
> `Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]`
> 
> ### Server Setup Information:
> * Version of Rocket.Chat Server: 3.15.0
> * Operating System: DiskStation Manager 7.0 (linux)
> * Deployment Method: docker
> * Number of Running Instances: 1
> * DB Replicaset Oplog: Enabled
> * NodeJS Version: 12.22.1 - x64
> * MongoDB Version: 4.2.14 (wiredTiger)

Had the same problem but not in the docker installation, but the manual installation.

**Comment by CrestApps** [comment]
This is still an issue for me. I can deploy version 3.15/latest with no problem. But if I want to rollback to version 3.14, then I get the following error in the logs

 > Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]

The command `db.migrations.find()` returns  the followingf

```
{ "_id" : "control", "locked" : true, "version" : 225, "buildAt" : "2021-05-28T04:16:32.940Z", "lockedAt" : ISODate("2021-06-16T19:05:27.693Z") }
```

I tried to execute 
```
db.migrations.update({_id: 'control'}, {$set: {locked: false,version:225}})
```
then I stopped, removed and re-run the container just to get the same error

**Comment by sampaiodiego** [comment]
@CrestApps rocket.chat doesn't support version downgrade.. 

if you still want to do so by your own risk, you need to *undo* all migrations between the two versions..

**Comment by CrestApps** [comment]
@sampaiodiego that sucks are 3.15 has a bug that makes the app useless for me.

**Comment by sampaiodiego** [comment]
I'm sorry, have you filled an issue regarding this bug already? this way we can fix and you can safely upgrade.
