### ISSUE TITLE
Rocket Chat turning to gray screen when quickly switching channels

### ISSUE THREAD

**Issue by BitMonster1010** [RocketChat/Rocket.Chat#23555]
### Description:

Rocket Chat turns to gray screen and needs refresh (or restart if in app) after going on a channel and quickly switching to other channels while the first one is still loading.

### Steps to reproduce:

1. Click on a channel
2. Immediately start clicking on other channels while the first channel is not loaded

### Expected behavior:

My entire Rocket Chat to not turn to gray screen and just switch to the other channels if I quickly change to another one

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: Debian 10 (Buster)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.0.0
- MongoDB Version: v4.4.6

### Client Setup Information

- Desktop App or Browser Version: 3.0.3
- Operating System: KDE Neon 5.24

### Additional context

I've been experiencing this for months at this point. (Though at some point I remember it showing invalid-user error, so it could have been another bug too, but I can't know for certain)

### Relevant logs:

BROWSER:
![image](https://user-images.githubusercontent.com/15013536/138771143-b4b3c14e-08b6-491a-82c1-eca0e4e78ca8.png)

SERVER:
![image](https://user-images.githubusercontent.com/15013536/138771436-12bb9d97-8ed8-4f8f-825a-78b540f88ba4.png)

**Comment by chotaire** [comment]
I've been seeing this too when clicking through channels to get rid of new message indication.

**Comment by krenuser** [comment]
Same issue. Fixed by Rocket.Chat's window refresh (Ctrl/Cmd+R), but looks like a bug.

**Comment by qwsj** [comment]
I have a gray screen after login in MacOS client and Safari, but all is ok in Chrome.
Also gray screen turning after "Uncollapse" button inside a channel, without any errors in log.

**Comment by glebPo** [comment]
Rocket.Chat Version: 4.1.2
Same issue

**Comment by ipikiiskinen** [comment]
Issue still in 4.3.1.
You can also get the same error with open.rocket.chat

Some remarks:
- I can get this easily with Firefox 91.4.0esr (64-bit) CentOS. Realod fixes the grey screen, but if you again switch fast between channels you can get the error state (gray screen) again.
- With Version 90.0.4430.212 (Developer Build) Fedora Project (64-bit) I can't get this as easily as with FF. And once I reload the browser tab, I can't get this error state on. But you can test & recreate the issue with opening private browsing sessions.
- Might happen a bit easier if there is a lot of messages in channels. Not really any proof of this - just feels like it happens more easily then.

**Comment by XxMoNsTeR** [comment]
This issue is still happening in version 4.5.0. Please fix this!

**Comment by Gummikavalier** [comment]
API and DDP rate limiters seem to play into this issue somewhat; disabling them all removes the issue almost completely, but I could not figure out yet which ones are most important ones.

Regardless, even when you disable all rate limiters it is still possible to reproduce the issue. You just have to switch channels longer at very rapid pace.

**Comment by Kyogre** [comment]
here is the video demo for those, who don't understand, what is this problem: https://user-images.githubusercontent.com/2260980/162573209-d5a3a195-9055-486c-9ed1-606d2f32937f.mp4
The bug is still here on RC 4.6.0 and https://open.rocket.chat

**Comment by qwsj** [comment]
Its really UI problem, please fix it. After 5.0 version gray screen replaced to error page with reload button. All collapsed messages are broken. See attached screens.
![before](https://user-images.githubusercontent.com/10673437/185879834-bc6f4627-76f2-4524-ae02-2d2192a69e14.png)
![after](https://user-images.githubusercontent.com/10673437/185879806-9046bde3-699f-44c3-8ad7-961e01a58c6b.png)
