### ISSUE TITLE
[Bug][LDAP][Enterprise] Avatars not updated

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#24555]
### Description:

@pierre-lehnen-rc to consider

Avatar sync background job don't sync avatars.
I enabled `Avatar Background Sync` in `Admin UI - LDAP - Enterprise - Background Sync` and enabled debug level of logs.
I don't see avatar sync event in logs at all, I see only update of custom fields on `LDAP_AvatarSync` cron job

### Steps to reproduce:

1. Update all users with LDAP and get `Username` instead on `username` to every Rocket Chat users username
2. All avatars are broken in that moment
3. `LDAP_AvatarSync` cron job don't fix avatars. I guess it just don't sync avatars, it sync custom fields instead.

### Expected behavior:

All avatars updated on `LDAP_AvatarSync` cron job
Or a better way - update only changed avatars (should be compare to current avatar in RC and in LDAP)

### Actual behavior:

Users without avatars after full LDAP sync and after `LDAP_AvatarSync` cron job
![image](https://user-images.githubusercontent.com/4023037/154896520-33653d09-55f0-4066-9136-2ba558494f55.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.3
- Operating System: OL8.5
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.8
- MongoDB Version: 4.4.12

### Client Setup Information

- Desktop App or Browser Version: 3.7.7 and Chrome 98
- Operating System: Windows 10

### Additional context

Previously we updated majority of our users with REST API and that users have `avatarOrigin: rest` in mongodb.
That weekend we made a full sync with LDAP, and if was a nightmare!

In 4.x version for some reason Rocket Chat team decided to use same username as in LDAP, but not lowercase of that username like it was before on pre version 4.x versions. @sampaiodiego is there a serious reason for such change?

So, on full LDAP sync every `username` become a `Username` and all messages of that user are updated with that change!
MongoDB was on a very high load, and Rocket.Chat instances crashed because of `out of memory`.
But anyway spending all weekend in that process we updated all usernames of our users to `Username` (first symbol is capitalized).
But with that all avatars of updated users was gone! And avatar sync didn't fix that issue.
 
### Relevant logs:

No

**Comment by ankar84** [comment]
Still an issue on 4.8.1
![image](https://user-images.githubusercontent.com/4023037/173776169-4d5b32b6-54da-4c28-bf08-6f6c1fbe39b7.png)

**Comment by matheusbsilva137** [comment]
Fixed in #26824 
Please reopen this issue if you notice that it persists after 5.2.0. Tks for reporting :slightly_smiling_face:

**Comment by ankar84** [comment]
> Fixed in #26824 Please reopen this issue if you notice that it persists after 5.2.0. Tks for reporting 🙂

We are on latest 5.4.1 now and issue is still here

**Comment by matheusbsilva137** [comment]
Hey @ankar84 is this issue somehow related to #28589 ? Not sure if I got what's happening in your case :thinking: 
Avatars are not being synced even if you try to sync them manually (with "Sync Now")?

**Comment by ankar84** [comment]
Hey @matheusbsilva137 
Avatars are synced in general
There appears some users with broken avatars. And that users stay with broken avatars after full sync. So sync doesn't fix such users.
Root cause of broken avatars is unknown.

**Comment by matheusbsilva137** [comment]
Hey @ankar84 . I'd like to have some more info about this so that I can try reproducing it locally
1. Is **LDAP > Data Sync > Sync User Avatar** setting enabled? If so, what is the "User Avatar Field" you're using there? Is it the default one (empty)?
2. What is the field you're using in LDAP to store users' avatars?

**Comment by shevchukma** [comment]
Hey @matheusbsilva137 !
I will try to answer your questions. We are working with @ankar84.
1. Yes, "Sync User Avatar" setting is enabled. The "User Avatar Field" is set to "photo".
2. The photo in LDAP is stored in the "photo" field.
![image](https://github.com/RocketChat/Rocket.Chat/assets/104189570/486cf2be-4b5e-48ab-a872-3815a8810eda)
3. I cannot answer the third question yet. I did not find users with a broken avatar. I will watch and find such cases.
