### ISSUE TITLE
File download doesn't work in MacOS client

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#2579]
Your Rocket.Chat version: 0.22.0
MacOS client version: 1.2.0

Downloading files in the MacOS client doesn't work although downloading in the browser works fine for the same instance. I tried both GridFS as well as FileSystem. For the latter I can see the file in the directory that I specified but users can still not download anything in the MacOS client.

**Comment by jeffrapp** [comment]
@andreas-bulling If you click the Files List fly-out, are you able to download from there?

**Comment by andreas-bulling** [comment]
no

**Comment by jeffrapp** [comment]
Interesting.  I've been experiencing similar issues with the Windows desktop client.  1.2.0 for the client, 0.22.0 for Rocket.Chat server.  On mine, the flyout menu has the entire http:// url, while the inline links only have a relative path.  The flyout list works for me, while the inline links do not.

**Comment by andreas-bulling** [comment]
I just checked with the debugger. The URL for the inline link seems to be correct. If I paste it in the browser I get a 403 forbidden (I've enabled secure links in the Rocket.Chat config) until I login to the chat in the browser. Then downloading the file works without any problem.

Maybe the client doesn't send the right HTTP header / is not authenticated properly from the point of view of the server?

**Comment by engelgabriel** [comment]
@jeffrapp  and @andreas-bulling 
This should be fixed on version 0.23.0
Can you try again?

**Comment by engelgabriel** [comment]
No, my mistake. This is not fixed on version 0.23.0
We found the bug, 2 actually. We will fix them shortly. Thanks for the info.

**Comment by andreas-bulling** [comment]
Thanks!

**Comment by andreas-bulling** [comment]
The button that you added in the latest version 0.24.0 works but I find it a bit weird that the server still shows the file title as a clickable link (that still doesn't work). I suggest to either remove the href or remove the button and make the title clickable directly.

**Comment by engelgabriel** [comment]
I agree. @rodrigok what do you think?

**Comment by orlovnv56** [comment]
Last rockchat.app 17.0 and earlier one 16.2 on macos catalina doesnt work file upload, from mobile and web work without any problem

**Comment by sampaiodiego** [comment]
@orlovnv56 can you please open an issue on the Desktop App project https://github.com/RocketChat/Rocket.Chat.Electron ? so please describe the issue as much as you can.. thanks
