### ISSUE TITLE
Channel Moderators List REST API does no longer accept roomName

### ISSUE THREAD

**Issue by jadolg** [RocketChat/Rocket.Chat#26262]
### Description:

/api/v1/channels.moderators is no longer accepting listing moderators by roomName.

Calling the endpoint with only this returns` {'error': "must have required property 'roomId' [invalid-params]", 'errorType': 'invalid-params', 'success': False}`

### Steps to reproduce:

1. Do a call against the endpoint
curl -H "X-Auth-Token: yourToken" \
     -H "X-User-Id: yourUserID" \
     http://localhost:3000/api/v1/channels.moderators?roomName=General

### Expected behavior:

Get the list of moderators for the GENERAL room

### Actual behavior:

Returns an error asking for roomId

` {'error': "must have required property 'roomId' [invalid-params]", 'errorType': 'invalid-params', 'success': False}`

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by geekgonecrazy** [comment]
@debdutdeb looks like you might have been the last one to touch this in https://github.com/RocketChat/Rocket.Chat/pull/25279 any ideas?

**Comment by debdutdeb** [comment]
This is fixed in the latest develop.

**Comment by jadolg** [comment]
I was trying to give it a try with `rocketchat/rocket.chat:develop` but seems I can't use it the same way I use `rocket.chat:latest`. The server seems to ignore `MONGO_URL` and directly tries to connect to MongoDB on localhost. :confused:

**Comment by debdutdeb** [comment]
The only situation I can see this happen is if the env variable was actually not passed to the container. Can you share the command[s] or compose file you're using?

**Comment by jadolg** [comment]
This is the compose file I use for testing. I only replaced the image.
https://github.com/jadolg/rocketchat_API/blob/master/docker-compose-test-server.yml

**Comment by jadolg** [comment]
@debdutdeb is there any schedule I can follow for when this fix will be released in `latest`?
I have a couple of PRs I'd like to merge and I would like to avoid skipping the failing test.

**Comment by jadolg** [comment]
@geekgonecrazy @debdutdeb are this changes already life in `latest`? I was not able to test against your `develop` branch.

**Comment by debdutdeb** [comment]
Yes this should now be fixed in the latest release.

**Comment by debdutdeb** [comment]
Ah no wait i might be confusing with another similar bug. Give ne 1 hours; in the store. I thought this was covered in the PR.

**Comment by debdutdeb** [comment]
Hey @jadolg thanks for waiting. I just checked, it is indeed working on latest develop so I didn't confuse. 
<img width="1440" alt="Screenshot 2022-08-07 at 3 58 47 PM" src="https://user-images.githubusercontent.com/76006232/183286641-5f1f65d0-4de7-403b-a632-e8e3b1d0fe3e.png">
I won't close the issue just yet; can you check one more time please?

**Comment by debdutdeb** [comment]
You can also check against our open server;
<img width="863" alt="Screenshot 2022-08-07 at 4 03 16 PM" src="https://user-images.githubusercontent.com/76006232/183286761-40bfecc1-0a21-4198-b93e-4ae2facaba8a.png">

**Comment by jadolg** [comment]
Thank you so much for checking. I still cannot run my tests against your `develop` image. I guess I'll wait until it gets merged and eventually lands on [this image](https://hub.docker.com/_/rocket-chat) which I use for testing every week.
Do you know approximately when these changes are being released?
Do you have any quick docker-compose setup I can use (like the one here https://github.com/jadolg/rocketchat_API/blob/master/docker-compose-test-server.yml) but for the images your produce in https://hub.docker.com/r/rocketchat/rocket.chat ?

**Comment by jadolg** [comment]
Well, the problem seems to be gone in the latest version.
