### ISSUE TITLE
Multi Line CodeBlock does not work anymore since upgrade to 5.x

### ISSUE THREAD

**Issue by amsnek** [RocketChat/Rocket.Chat#26679]
### Description:

Multi Line CodeBlock does not work anymore since upgrade to 5.0.3 (from 4.x)

### Steps to reproduce:

1. Click on Codeblock (bottom screen under prompt) or use `` manually
2. Insert multiple lines (single lines work)
3. Press Enter. No Code Block appears, the character: ` are printed as text

### Expected behavior:

expect pasted Text to be in CodeBlock

### Actual behavior:
 No Code Block appears, the character: ` are printed as text

![Multiline_CodeBlock](https://user-images.githubusercontent.com/73526449/186627135-67e27b1e-59f1-43ab-9eb1-a60d0904df47.png)

### Server Setup Information:
Rocket.Chat Version: 5.0.3
NodeJS Version: 14.18.2 - x64
MongoDB Version: 4.4.15
MongoDB Engine: wiredTiger
Platform: linux
Process Port: 3000
Site URL: https://redacted.org
ReplicaSet OpLog: Enabled
Commit Hash: c5b43b004e
Commit Branch: HEAD

**Comment by ankar84** [comment]
Strange. Works for me in both new and legacy message template
New template
![image](https://user-images.githubusercontent.com/4023037/186634308-6635f440-033d-4f40-8a3b-f238d52611d0.png)
Legacy template
![image](https://user-images.githubusercontent.com/4023037/186634504-4970db69-3d59-46d4-80fe-14603c17cb06.png)

**Comment by dazoot** [comment]
Code block usually works with 3 `.
Now after upgrade the 3 ` have to be on a separate line for the block to be displayed as code block. This is super mega annoying.

Example:
![image](https://user-images.githubusercontent.com/1543455/186635389-05c32755-9780-4b52-8712-0f57bfd88e62.png)

**Comment by amsnek** [comment]
Hmm I just tested also with a browser, I am using the electron app (3.8.8) -> but its the same issue. 
What can I do to provide more usable information?

**Comment by amsnek** [comment]
> Code block usually works with 3 `. Now after upgrade the 3 ` have to be on a separate line for the block to be displayed as code block. This is super mega annoying.
> 
> Example: ![image](https://user-images.githubusercontent.com/1543455/186635389-05c32755-9780-4b52-8712-0f57bfd88e62.png)

aah, yes, it works with 3 quotes!

**Comment by dazoot** [comment]
It was always like this with 3 \` (GRAVE ACCENT) for multiline blocks. Now the BUG is that the 3 \` (GRAVE ACCENT) must be on a separate line each. Which means you have to press Shift + Enter in the chat box.

**Comment by amsnek** [comment]
hmm interesting, for me, in the past it was 4 ` (GRAVE ACCENT) on beginning and end before needed
but yeah, grave accents must be on seperate line now too

**Comment by amsnek** [comment]
if this is working as intended (3 grave accents/backticks on seperate line) i would close the bug
however, using the gui does not work for multiline now -> not sure if that is intended?

**Comment by dazoot** [comment]
I don't think there were ever 4 \` for code block
https://docs.rocket.chat/contributors/how-can-i-help/documentation/markdown-styleguide#md046-code-block-style

In the documentation are listed only 3 \`. 
We should have this fixed (paste code is now unusable, extra Shift + Enter 2x is required).

**Comment by amsnek** [comment]
yeah, i am 100% certain i used 4x` in the past and it "worked", maybe the last backtick was just removed/ignored and i never noticed, nor ever tried with 3x` 🙈 

I agree that the paste code is rather cumbersome now and should be fixed

**Comment by ankar84** [comment]
As for me. I never used 4x backticks and always used 3x backticks and all worked perfect.
One breaking change in versions is that separation is needed between 3x backticks and code. New line.
Before code was OK even if 3x backticks was on same line with first symbols of code.

**Comment by amsnek** [comment]
tbh, i never used the: 
![image](https://user-images.githubusercontent.com/73526449/186647877-48d80181-b8f8-45db-bdb7-3fb556c19013.png)

🙈

**Comment by aaplmike** [comment]
I'm seeing the same different behavior. Backticks now have to be on their own lines. It's more work to do than it was before by having to use option-return to get them formated correctly. Before you could use the opening 3 backticks on the same line as the text. You didn't even need to close the backticks...hitting return would take care of it. Now it's much more tedious to get the same functionality. Why was it changed??  I'm going to have to look at the latest PRs to see if this was intentional, and if so, why change something that worked fine.

**Comment by jlegg0** [comment]
This only affects the main view. Search results still show with code block formatting if the triple backticks are on the same line as the code.

**Comment by dazoot** [comment]
This is the most annoying bug EVER. Not being able to paste code. I die a bit every day :) Any hopes to get one of the devs check this out ?

**Comment by ankar84** [comment]
> This is the most annoying bug EVER. Not being able to paste code. I die a bit every day :) Any hopes to get one of the devs check this out ?

I don't know what you talking about if even when you using code button it paste proper ` ``` ` code and cursor between, you just need to paste code there.
I mean this:

```

```
your code
```

```

**Comment by dazoot** [comment]
@ankar84 before the upgrade it was not required to have the 3 \`\`\` on a separate line. 

This makes pasting code in the chat box mega annoying, i have to type 3 \`\`\` then press Shift Enter, then paste the code, then press again Shift Enter then type the 3 \`\`\` (thus dying inside every day cause of it).

Please read all the coments in this issue.

**Comment by amsnek** [comment]
you can also use the multine insert button on the bottom of the screen 
![image](https://user-images.githubusercontent.com/73526449/192537715-9a99e861-9974-4db5-bd34-e9865e25a2dc.png)

but yeah, its a mouse click and not as comfortable

**Comment by hugocostadev** [comment]
Hi guys, we are following the standards for multi-line code blocks from other players, like here, for example. 

We decided to not let the multiline code blocks open in the same line as the code itself because of the code highlighting.

e.g 
```
   ```javascript
   code inside 
   \```
```

We are working on a new message composer that will easier to write and format texts. 

Since this is a matter of specification, I'll close this issue for now.

Please, let us know if we can improve in something else or if you have another point of view about this, we are open to discuss.
