### ISSUE TITLE
RocketChat is reloaded when using the channel search

### ISSUE THREAD

**Issue by birdie1** [RocketChat/Rocket.Chat#28764]
### Description:

When using CTRL+p to open the channel search and perform a search, RocketChat reloads the complete page if searching the channel search. This happens random (all users affected, sometimes it works normal sometimes this issue)

### Steps to reproduce:

1. Open channel search with CTRL+p
2. search for a user or channel
3. hit enter to take the first entry

### Expected behavior:

After hitting enter the user should be opened.

### Actual behavior:

RocketChat hangs for a few seconds, then the whole page is reloaded.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Debian 11
- Deployment Method: official RocketChat docker
- Number of Running Instances: 1
- NodeJS Version: v14.21.2
- MongoDB Version: 4.4.19 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Linux, Mac, Windows

**Comment by Abhishek1274** [comment]
Hi @birdie1, can you assign this issue to me as I want to start my open-source contribution

**Comment by CulturalProfessor** [comment]
Hey @birdie1 I tried to reproduce this issue but it was working fine in my case.

**Comment by Gummikavalier** [comment]
I also have seen this happen with RC6. Feels random.

**Comment by XshubhamX** [comment]
@hugocostadev I was able to reproduce it, working on it.

**Comment by ulope** [comment]
I looked a tiny bit deeper and this seems to be the exception that triggers the reload:
```
483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599 TypeError: Failed to fetch
    at r.send (/483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:5:168608)
    at /483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:5:166212
    at /483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599:967455
    at r.send (/483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:5:168985)
    at /483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:5:166212
    at /483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599:2095066
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1366
n @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599
sendMessage @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1410
_apply @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1410
applyAsync @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1410
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1410
callAsync @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1410
e @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599
m @ ServerProvider.tsx:1
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:5
a.retry @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1599
f @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
v @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
u @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
fetch @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
executeFetch @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
fetch @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
refetch @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
onFocus @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
a @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
onFocus @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
onFocus @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
(anonymous) @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
t @ 483a38c4c0addb9b422d114589bd28887f219bf9.js?meteor_js_resource=true:1268
```

**Comment by jmscarpa** [comment]
Do we have anything new on that failed to fetch with meteor_js_resource=true ?

**Comment by Sayan4444** [comment]
I have not been able to replicate this message! Can you check if this issue still persists?

**Comment by Sayan4444** [comment]
Can u please share a video when it happens.....it will be of immense help

**Comment by ulope** [comment]
Done: https://youtu.be/gq-BFtdXLYc

**Comment by Sayan4444** [comment]
Hi @ulope thanks for the video, I guess this issue does not exsists on 6.5, so that maybe thats a reason why I have failed to replicate it

**Comment by ulope** [comment]
I'll update our server to 6.5 soon and will re-try then.

**Comment by Sayan4444** [comment]
> I'll update our server to 6.5 soon and will re-try then.

Do report me back

**Comment by Gummikavalier** [comment]
I can still reproduce this in RC 6.5.2 by starting typing a person name (surname) for two or three first letters. Until the fourth letter the selection does not light up, and if you press enter before that reload happens.

It happens only once per search though. To replicate I have to think about some other name and type three first letters of their surname.

**Comment by Sayan4444** [comment]
@Gummikavalier Can you just record a video and send me back here, it will me super helpful

**Comment by Gummikavalier** [comment]
@Sayan4444 Not video but these two images show how it happens:

Starting typing the search for the name `Tester Fester`, after the three first letters the only person that fits the search is exactly that. Yet this search result is not selected and pressing enter at this point would reload the web client:
![Screenshot from 2024-01-04 09-15-04](https://github.com/RocketChat/Rocket.Chat/assets/6958942/3901d5a5-16bb-4c18-bb43-47b1afecf07c)

After typing the fourth letter the name becomes selected. If you now press enter at this point, the web client operates as it should:
![Screenshot from 2024-01-04 09-15-09](https://github.com/RocketChat/Rocket.Chat/assets/6958942/ce67ce3b-062d-492c-9ccc-d31ee647ec39)

The real name is `Tester Fester`. Actual username for this user is `testerfester`. The user is purely local one to this instance.

There are only ~10 users on this test instance and only few channels, of which none would hit this particular `fes` pattern. So the search is not even a big one. The issue should be reproducible with pretty minimal data set.

**Comment by Gummikavalier** [comment]
I think this may have been fixed in RC 6.6.1.
