### ISSUE TITLE
npm install gc-stats 403 Forbidden

### ISSUE THREAD

**Issue by CAberry** [RocketChat/Rocket.Chat#29600]
### Description:

```
> gc-stats@1.4.0 install /tmp/bundle/programs/server/npm/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.4.0 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz 
```

### Steps to reproduce:

1. Download last release 6.2.6  (witch is missing Engine version in the description by the way)
2. Manual install via npm install

### Expected behavior:

Should not give forbidden or should be included in the downloaded archive

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.5
- Operating System: Debian Bookworm
- Deployment Method: tarball
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.18

**Comment by hugocostadev** [comment]
Could you test with the latest release? (6.2.7) 

I think it was fixed by this PR https://github.com/RocketChat/Rocket.Chat/pull/28867

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by sampaiodiego** [comment]
@hugocostadev the PR you mentioned will be available only on the upcoming 6.3.0 release.

**Comment by Gummikavalier** [comment]
I confirm that I can see the same error during the tar install of the latest RC 6.2.8 on RHEL8. (And with the previous RC versions too.)

**Comment by PurnenduMIshra129th** [comment]
hello @CAberry sir i want to solve this issue please  assign

**Comment by CAberry** [comment]
@hugocostadev  I think you have the answer, please change the label to a more appropriate one.
@PurnenduMIshra129th I can't assign nothing sir, I'm sorry. Not my role ;)

Greetings,

**Comment by hugocostadev** [comment]
Indeed it was fixed by this PR https://github.com/RocketChat/Rocket.Chat/pull/28867 , it's expected to be released soon in the 6.3.0

**Comment by jazztickets** [comment]
This happens in 5.4.10 as well. Any chance for fix there?

**Comment by hugocostadev** [comment]
No @jazztickets only on the latests releases... For past releases we just fix security issues for some time

**Comment by tsteiner** [comment]
Should this be working now? I'm getting the same error trying to install 6.3.6.

- Version of Rocket.Chat Server: 6.3.6
- Operating System: Gentoo Linux
- Deployment Method: tarball
- Number of Running Instances:
- DB Replicaset Oplog:
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.16

**Comment by Gummikavalier** [comment]
Yup, we are still getting the error too.

**Comment by lovekyleman** [comment]
Still get the error

**Comment by paymanzafar1** [comment]
On the latest version (6.4.4) I still have this error.

**Comment by minusmillionaer** [comment]
We're still get the error too.

**Comment by lovekyleman** [comment]
Same here

**Comment by pierrecorsini** [comment]
Same here

**Comment by Gummikavalier** [comment]
If this thing does not happen to everybody, I think it is an error in the distribution of NPM components or a purposeful block. It can be done by anyone in control of AWS, anyone managing internet cache networks in the area, or someone in the control of local networks.

**Comment by villivateur** [comment]
I have the same error with v6.4.6.
If it is AWS CDN's problem, please consider not using AWS or provide another mirror CDN.

**Comment by Flashield** [comment]
Install g++

**Comment by lovekyleman** [comment]
> Install g++

g++ is already the newest version (4:10.2.1-1).
Still has the 403 error

**Comment by Flashield** [comment]
+---------------------------------------------+
|                SERVER RUNNING               |
+---------------------------------------------+
|                                             |
|  Rocket.Chat Version: 6.4.8                 |
|       NodeJS Version: 14.20.0 - x64         |
|      MongoDB Version: 6.0.0                 |
|       MongoDB Engine: wiredTiger            |
|             Platform: linux                 |
|         Process Port: 3000                  |
|             Site URL: http://*.*.*.*/im     |
|     ReplicaSet OpLog: Enabled               |
|          Commit Hash: 133e7444b6            |
|        Commit Branch: HEAD                  |
|                                             |
+---------------------------------------------+

g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)

My Env is this. After getting 403 Forbidden, Node will compile the package to continue.

**Comment by eventhorizon5** [comment]
Not sure why this was closed, I've been getting these build errors every time I attempt to upgrade, and haven't been able to upgrade my Rocket Chat server.  Just tried building the new 6.5.0, and it failed again.  I'm on Debian 12, g++ version is 12.2.0-14.

**Comment by tete2soja** [comment]
The specific version 1.4.0 is not listed on the Github repository but show on npm webpage. The Github list 1.3.0 or 1.5.0 as release. And testing the URL with 1.5.0 as version gives back a 200: http://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz.
Guess, update to 1.5.0 seems one possible solution.

**Comment by jazztickets** [comment]
Nice find @tete2soja!
I was able to get past the error on my Debian 12 box by editing /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json and changing the version to 1.5.0

However, I was met with another error related to the outdated Node.js 14.0 version that's required for rocketchat:

```
 File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
```

The 'U' option was removed in Python 3.11, so I just removed that from input.py and was able to build.

**Comment by svenseeberg** [comment]
> The 'U' option was removed in Python 3.11, so I just removed that from input.py and was able to build.

Thanks, that worked for me!

**Comment by villivateur** [comment]
> I was able to get past the error on my Debian 12 box by editing /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json and changing the version to 1.5.0

That should be the solution. I wonder why the official developers did not notice that. Maybe this issue does not affect any function?

**Comment by lovekyleman** [comment]
Nice 
That's the solution
vim /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json
Change 1.4.0 to 1.5.0
No errors now

**Comment by atanevski** [comment]
> Nice That's the solution vim /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json Change 1.4.0 to 1.5.0 No errors now

```
> gc-stats@1.5.0 install /opt/RocketChat/programs/server/npm/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.5.0 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz 
```

I am getting this error. Any updates on the issue?

**Comment by svenseeberg** [comment]
For me it was resolved with one of the newer 6.5.X patch releases of Rocket.Chat.

**Comment by lovekyleman** [comment]
> > Nice That's the solution vim /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json Change 1.4.0 to 1.5.0 No errors now
> 
> 
> 
> ```
> 
> > gc-stats@1.5.0 install /opt/RocketChat/programs/server/npm/node_modules/gc-stats
> 
> > node-pre-gyp install --fallback-to-build
> 
> 
> 
> node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz 
> 
> node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.5.0 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
> 
> node-pre-gyp WARN Hit error response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz 
> 
> ```
> 
> 
> 
> I am getting this error. Any updates on the issue?
> 
> 
> 
> Update:
> 
> 
> 
> Managed to resolve it by copy pasting the latest packages.json from https://github.com/dainis/node-gcstats to /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json
> 
> 
> 
> and installing build-essentials `$ sudo apt-get install build-essential` and then npm install
> 
> 

Yes. 1.5.0 has 403 now

**Comment by villivateur** [comment]
> Because of this change
> 
> [dainis/node-gcstats@7833701#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519](https://github.com/dainis/node-gcstats/commit/78337018c0690d9cb7291093bd7d31be47b09728#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
> 
> All node-gcstats binaries are missing on https://node-binaries.s3.amazonaws.com
> 
> Maybe this issue should be reopened ?

@hugocostadev This issue should be reopened.

**Comment by atanevski** [comment]
I've updated my comment above.

Dirty fix:
```
Modify:
/opt/RocketChat/programs/server/npm/node_modules/moleculer/package.json:91:  gc-stats": "^1.4.0", 
/opt/RocketChat/programs/server/npm/node_modules/prometheus-gc-stats/package.json:29:  gc-stats": "^1.4.0", 

to 1.5.0
```

**Comment by spaynix** [comment]
> I've updated my comment above.
> 
> Dirty fix:
> 
> ```
> Modify:
> /opt/RocketChat/programs/server/npm/node_modules/moleculer/package.json:91:  gc-stats": "^1.4.0", 
> /opt/RocketChat/programs/server/npm/node_modules/prometheus-gc-stats/package.json:29:  gc-stats": "^1.4.0", 
> 
> to 1.5.0
> ```
I tried changing the version to 1.5.0 in temporary files and after installation, but the server still does not start, are there any options?

  Process: 49973 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 49973 (code=exited, status=1/FAILURE)

Rocket rocketchat[49973]:     maxElectionId: null,
Rocket rocketchat[49973]:     maxSetVersion: null,
Rocket rocketchat[49973]:     commonWireVersion: 0,
Rocket rocketchat[49973]:     logicalSessionTimeoutMinutes: null
Rocket rocketchat[49973]:   },
Rocket rocketchat[49973]:   code: undefined,
Rocket rocketchat[49973]:   [Symbol(errorLabels)]: Set(0) {}
Rocket rocketchat[49973]: }
Rocket systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Rocket systemd[1]: rocketchat.service: Failed with result 'exit-code'.

**Comment by atanevski** [comment]
Send us the full log please. From the partial log I think rocket cannot connect to your mongo db instance.

**Comment by kobaltd** [comment]
I confirm that the problem is still relevant. Replacing with 15 does not help. Same mistake.

**Comment by atanevski** [comment]
@kobaltd Verify if you have changed the package.json also

https://github.com/dainis/node-gcstats/blob/5d8aace314e2a3443863d5d390c03ea3dd68d4a8/package.json - new one

 /tmp/bundle/programs/server/npm/node_modules/gc-stats/package.json - replace it here

**Comment by kobaltd** [comment]
If you think that I didn’t do this, you are mistaken.
![2024-03-04 204712](https://github.com/RocketChat/Rocket.Chat/assets/25199418/bf481d3e-ba78-4da5-884f-6e6b7be238c2)

**Comment by atanevski** [comment]
Yes but change the top version 1.4.1 to 1.5.0 and try using node 14

**Comment by kobaltd** [comment]
The build fails without binary packages.

![2024-03-04 205642](https://github.com/RocketChat/Rocket.Chat/assets/25199418/ffd462fc-d394-40ba-aa4f-4b3cc6f6359d)
![Снимок экрана 2024-03-04 210107](https://github.com/RocketChat/Rocket.Chat/assets/25199418/c18951fc-1321-4376-8c4e-950a076931e3)

**Comment by atanevski** [comment]
This is different kind of error

**Comment by kobaltd** [comment]
Yes, different :) but in the last proposed package.json there is no "binary" section. I'm not a nodejs specialist, but as I understand it, if there is no link to the binaries, it tries to build the package from the sources. And since nodejs =>16 is weak for 1.4.1 and higher, the build for server 14 does not work. P.S. Therefore, as I understand it, there was a link to the already compiled package.

**Comment by kobaltd** [comment]
Solution found:
In any case, if binary packages are not available. He tries to  build them from source codes. But the build does not work due to the “new” python3 (3.11 and higher). Solution: either lower the version or change "rU" to "r" in "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py#234". Didn't run it yet, but the build was successful .

**Comment by fdalsotto** [comment]
any idea about what to do here? There are so many hacks in the comments that it makes it very hard for people to understand what's going on. Thanks

**Comment by andreaswolf** [comment]
I can confirm that changing `rU` to `r` in `…/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py` works. Apparently the build runs smoothly afterwards.
