### ISSUE TITLE
Quote is interrupted instead of being displayed with a blank line

### ISSUE THREAD

**Issue by xolyu** [RocketChat/Rocket.Chat#30604]
### Description:

A blank line in a quote breaks the quote and displays a line with `>` instead of inserting a blank line within the quote.

### Steps to reproduce:

1. send a message (to someone or yourself) with the following content, e.g.:
   ```
   > my quote
   > 
   > more quoted text after a blank line
   ```

### Expected behavior:

The quote should be displayed as an entire block and should not be interrupted.

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/5889376/ce2f073b-5983-4f92-81b0-c7f3e6df0f1f)

### Actual behavior:

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/5889376/49d57657-cd2e-48b9-9103-9a9cfaee3fbd)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.12
- Operating System: Ubuntu 22.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.21

### Client Setup Information

The problem occurs in the browser as well as in the app (Android).

- Browser Version: ✔️  Chrome, Firefox
- Mobile Client: ✔️ Android (v4.41.0.49563)

**Comment by TimmiORG** [comment]
Hi @xolyu 
looks like this as have been fixed in later version. Just tried on 6.3.10.
![image](https://github.com/RocketChat/Rocket.Chat/assets/979342/b9681777-2abb-4939-a452-fb4fbe5233a9)

**Comment by AbhishekCS3459** [comment]
@xolyu I want to contribute for this issue, 
please assign me this issue.

**Comment by xolyu** [comment]
@AbhishekCS3459 I can't assign anyone to the issue, I think that privilege is reserved for Rocket.Chat maintainers.

_But contributing via pull request with reference to the ticket should still be possible without any problems, even without being assigned to an issue._

**Comment by xolyu** [comment]
I had been using the [rocket.chat Docker Official Image](https://hub.docker.com/_/rocket.chat), but this seems to be about 1 month behind, so I have now switched to [`rocketchat/rocket.chat`](https://hub.docker.com/r/rocketchat/rocket.chat). I had first updated to version `6.3.10`, then to `6.4.1` (5 days old) - but the problem persists.

@TimmiORG your screenshot looks like you quoted an entire message, however, that is not the problem. When you write a text and insert a quote, by starting the line with a `>`, then the problem occurs - that is, when you type the quote in your message.

**Comment by TimmiORG** [comment]
Hi @xolyu 

OK now I got your point. Still looks like normal behaviour.
https://developer.rocket.chat/contribute-to-rocket.chat/modes-of-contribution/documentation-contribution-guidelines/markdown-style-guide

See MD027 and MD028.

**Comment by xolyu** [comment]
@TimmiORG unfortunately, you are wrong about the two points you listed.

> MD027 - No multiple spaces after the blockquote symbol

This refers to the number of spaces between the quote-introducing symbol `>` and the text.

> MD028 - No blank line inside blockquote

This refers to blank lines (lines with a length of 0 characters, excluding end of line) inside blockquotes. The statement is that quote blocks should not be interrupted by such blank lines.

Exactly the opposite is the case in my example, because in my example **all** lines start with the symbol `>`. And just the line that has no content (but starts with `>` and therefore is not a blank line) should be interpreted as a line break or new paragraph, instead the quote block is wrongly "torn apart".

You can read about this in more detail on [John Gruber's website](https://daringfireball.net/projects/markdown/syntax#blockquote), under Blockquotes there are enough examples that exactly represent my case.
