### ISSUE TITLE
Katex parser regex bugs 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#3177]
Your Rocket.Chat version: 0.29.0 develop

With this pattern, katex kicks in:

`I have $3 in my pocket but only $1 to spend`

Also, with this pattern, you get a katex crash message rendered in line:

`Wow, that was a  f$%5#^#*$&W$#W5 crazy experience ?!`

**Comment by engelgabriel** [comment]
Hopefully fixed by https://github.com/RocketChat/Rocket.Chat/pull/3166

**Comment by Sing-Li** [comment]
Current 0.29.0 develop deployed on demo still exhibits same problem.   Both cases :(

**Comment by Burstaholic** [comment]
This may not be the exact same bug, but it has issues with Bash scripts as well (message from GitLab's Slack integration if it matters). This Rocket.Chat instance was running a Docker build from June 9.

![rocketchatparseerror](https://cloud.githubusercontent.com/assets/2072033/16232845/af312ee0-3791-11e6-8d1f-bfc163d205ca.png)

**Comment by engelgabriel** [comment]
Hi @Burstaholic do you know if this is still happening?

**Comment by taikedz** [comment]
Still happening on server 0.65.1 , desktop client 2.10.5

![image](https://user-images.githubusercontent.com/231984/40975120-c704c078-68c1-11e8-9ee7-1658d6a3d912.png)

**Comment by MartinSchoeler** [comment]
This seems to be working in the latest version, closing this issue. @Burstaholic If you are still facing this issue, please open a new dedicated issue for it. Thanks!
