### ISSUE TITLE
Community License server thinks it is air-gapped (but it's not)

### ISSUE THREAD

**Issue by saschafoerster** [RocketChat/Rocket.Chat#33989]
### Description:

I switched from starter license to community license, to be able to invite guest and help me debug another bug. Now my rocket chat instance gives this new error (what a chain of bugs): "Workspace in read-only mode. Admins can restore full functionality by connecting it to the internet or upgrading to a premium plan.“ 

But the instance is not air-gapped. So no one of the team was able to use RocketChat as it is read-only now. And I don't now how to test or debug this. How can I tell my rocketchat server, that it IS connected to the internet???

Error message: 
 „Workspace in read-only mode. Admins can restore full functionality by connecting it to the internet or upgrading to a premium plan.“

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Community 
- Number of Users: 9
- Operating System: Synology DSM 
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: - 
- MongoDB Version: - 

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: MacOS

**Comment by reetp** [comment]
Not sure why you had to switch to community?

On v7 you have 50 users on the starter plan and you are using 9.

In any event the likelihood this is due to a networking issue within your docker instance or Synology.

It can't get to the URL to check the version - you will see that in your logs.

You need to log into the docker shell via `docker -it exec blah` and test your network connectivity.


> what a chain of bugs)

Which chain of bugs? Chains are a set of links. That is a clue.

Are you also Issue 33987 with Jitsi ?

**Comment by hallo43** [comment]
i have same issues. we are using rocket.chat for internal company, and not allow access from internet.
but when upgrading version 7.0.0 so error occur. We only use community not need EE features.
now the mail function is not work.

**Comment by reetp** [comment]
> have same issues. we are using rocket.chat for internal company, and not allow access from internet.
> but when upgrading version 7.0.0 so error occur. We only use community not need EE features.
> now the mail function is not work.

There is nothing to show that this is actually the same issue. Their server is not air-gapped but yours is.

In your case I am afraid you need to register your instance with Rocket.Chat (don't shoot the messenger - I don't work for Rocket)

https://docs.rocket.chat/docs/rocketchat-air-gapped-deployment
https://docs.rocket.chat/docs/air-gapped-license
https://docs.rocket.chat/v1/docs/rocketchat-release-notes

**Comment by saschafoerster** [comment]
> On v7 you have 50 users on the starter plan and you are using 9.

Thats what I thought. But there is a difference between the role "users" and "guests". The starter plan only counts "the users", but has 0 places for guest (which is a bug in my opinion). 
 
> In any event the likelihood this is due to a networking issue within your docker instance or Synology.

I tried restarting the container and the Synology, then it worked. 

> Are you also Issue 33987 with Jitsi ?

No.

**Comment by saschafoerster** [comment]
Here we go again. After the restart of docker, it worked for a day, now it thinks again it can not be connected to the internet and stops all internal communications. I am really annoyed by this business interruption that is caused by a malfunctioning license check.

**Comment by saschafoerster** [comment]
These are related logs, that look suspicious to me: 

```
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:33.147Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:33.646Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:35.976Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:36.196Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:36.494Z","pid":1,"hostname":"84ed53951489","name":"Callbacks","msg":"Executing callback with id kWz5oFN3GXJypSfBk for hook workspaceLicenseRemoved"}
rocketchat-rocketchat-1  | {"level":30,"time":"2024-11-21T09:23:36.497Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Synced with Rocket.Chat Cloud","function":"syncCloudData"}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:36.497Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Resetting cached value Cloud_Workspace_Supported_Versions_Token in settings"}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:36.500Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."}
rocketchat-rocketchat-1  | {"level":20,"time":"2024-11-21T09:23:38.762Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Supported versions","supportedVersionsFromBuild":"2024-11-01T01:18:24.339484173Z","response":"2024-11-21T09:23:38.668598554Z"}
rocketchat-rocketchat-1  | {"level":30,"time":"2024-11-21T09:23:38.763Z","pid":1,"hostname":"84ed53951489","name":"System","msg":"Using supported versions from cloud"}

```

**Comment by reetp** [comment]
I have had a test v7 running on a cloudy vm since release and not had a single issue.

Watching bugs & open I haven't seen any others issues, except where people are blocking access themselves.

Have you considered it may be due to networking on your synology or elsewhere on your network, which I have seen before? I did say this previously.

Having to restart to permit access sounds more like a firewall type issue. It might be worth running some network tests on your instance, from inside your docker container, and a close inspection of your firewall & proxy setup.

Note they are not going to rescind the decision to licence check.

**Comment by reetp** [comment]
> The starter plan only counts "the users", but has 0 places for guest (which is a bug in my opinion).

If that were the case you would register every user as a guest..... :-)

It's not a bug as nothing is broken. It just doesn't work the way you want it. At best it's a feature request, but doubt it would get traction.

I usually have one 'guest' account that I reserve for this type of thing. With 50 free seats on Starter it shouldn't be an issue for most.

**Comment by adolfombarros** [comment]
I have the same issue...

Versão 7.1.0
Versão do mecanismo de aplicativos 1.48.0
Versão do nó v20.18.0
Migração do banco de dados 318
MongoDB 6.0.19 / wiredTiger (oplog Ativado)
Detalhes do Commit
HEAD: (73af9c537)
Branch: HEAD
Release 7.1.0

I tried restarting the container, then it worked.

**Comment by reetp** [comment]
You are lucky that I read old bugs occasionally of this gets missed.

> I have the same issue...
 
They reported it on 7.0.0 and you reported it on 7.1.0 so it isn't necessarily the same.

In any event for general support issue please ask your well documented question on https://open.rocket.chat/channel/support

If we discover a bug then we can open a new issue.

**Comment by Soonogo** [comment]
After upgrading from 6.x to 7.1.0, I also encountered this issue. I deployed it locally and started the server with Node locally. I don't need to connect to cloud services. I can use the offline version. What should I do?
<img width="308" alt="image" src="https://github.com/user-attachments/assets/1265ee80-9ae3-4887-a6a8-2121cc630030" />

https://docs.rocket.chat/docs/updating-rocketchat

**Comment by reetp** [comment]
As per conversations here

https://open.rocket.chat/channel/support?msg=Co23eeaDT5bCExmqW

Please read for v7.0

https://docs.rocket.chat/v1/docs/rocketchat-release-notes

![Screenshot_20241217_180107_Firefox Beta.jpg](https://github.com/user-attachments/assets/de03dc6e-070d-4e7c-bab1-0d5b40de7ad9)

CE no longer supports airgapped. You need a licence.

(Don't shoot the messenger)

**Comment by Charsly** [comment]
The issue also occurred after upgrading from version 7.3.0 to 7.3.1, which never happened before. Can anyone help me? The log is as follows:
{"level":50,"time":"2025-02-18T01:34:55.615Z","pid":1319,"hostname":"k8s-master","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.<br>    at abort (/snap/rocketchat-server/1635/programs/server/npm/node_modules/node-fetch/lib/index.js:1458:16)<br>    at AbortSignal.abortAndFinalize (/snap/rocketchat-server/1635/programs/server/npm/node_modules/node-fetch/lib/index.js:1473:4)<br>    at AbortSignal.dispatchEvent (/snap/rocketchat-server/1635/programs/server/npm/node_modules/event-target-shim/src/event-target.mjs:337:35)<br>    at abortSignal (/snap/rocketchat-server/1635/programs/server/npm/node_modules/abort-controller/src/abort-signal.ts:68:12)<br>    at AbortController.abort (/snap/rocketchat-server/1635/programs/server/npm/node_modules/abort-controller/src/abort-controller.ts:26:9)<br>    at Timeout.<anonymous> (/snap/rocketchat-server/1635/programs/server/npm/node_modules/@rocket.chat/server-fetch/src/index.ts:43:48)<br>    at listOnTimeout (node:internal/timers:594:17)<br>    at processTimers (node:internal/timers:529:7)","name":"AbortError"}} 
{"level":50,"time":"2025-02-18T01:34:55.632Z","pid":1319,"hostname":"k8s-master","name":"System","msg":"Failed to get Checkout URL with Rocket.Chat Billing Service","url":"/api/v2/checkout","err":{"type":"CloudWorkspaceAccessTokenEmptyError","message":"Workspace access token is empty","stack":"Error: Workspace access token is empty<br>    at legacySyncWorkspace (app/cloud/server/functions/syncWorkspace/legacySyncWorkspace.ts:158:9)<br>    at processTicksAndRejections (node:internal/process/task_queues:105:5)<br>    at syncWorkspace (app/cloud/server/functions/syncWorkspace/index.ts:35:6)<br>    at getCheckoutUrl (app/cloud/server/functions/getCheckoutUrl.ts:15:3)<br>    at ee/server/requestSeatsRoute.ts:28:71"}}

**Comment by reetp** [comment]
Please see above - you probably need to fix/resync your licencing for airgapped because it can't contact the server to check.

**Comment by tim-tation** [comment]
Same issue here, but no way to fix/resync the license, since the workspace wouldn't connect to Rocket Chat Cloud anymore.

Two weeks after updating to 7.0.0 we suddenly went into air-gapped read-only mode. "Connect it to the internet" or "updating to a premium plan to restore full functionality" wouldn’t work. After some research I found out, that I should delete the existing workspace registration in the Rocket Chat Cloud first and then re-register it. That didn’t work either.

I thought it doesn’t work because it showed that it is still registered (not showing a registration button). Since I couldn’t get rid of the registration, I deleted the entry in the mongodb with db.rocketchat_settings.remove( {"id": /Cloud/} ). After that I got the “Register workspace” button back, but unfortunately that didn’t help either because the registration would stuck - with “use token” saying “Token not recognized”, by cloud account mail being stuck in step 1. It feels like Rocket.Chat Cloud blocked our server. Any ideas what else could be tried?

### Server Setup Information

Version of Rocket.Chat Server: 7.0.4
Operating System: Ubuntu 22.04.5 LTS
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 20.17.0 - x64
MongoDB Version: 6.0.20
Proxy: nginx
Firewalls involved: iptables

### Rocket.Chat Logs Excerpts

“Failed to Connect with Rocket.Chat Cloud”,“url”:“/api/oauth/clients”,“err”:{“type”:“AbortError”,“message”:“The user aborted a request.”,“stack”:“AbortError: The user aborted a request.\n at abort (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1458:16)\n at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1473:4)\n at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/src/event-target.mjs:337:35)\n at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/src/abort-signal.ts:68:12)\n at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/src/abort-controller.ts:26:9)\n at Timeout. (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/src/index.ts:42:48)\n at listOnTimeout (node:internal/timers:581:17)\n at processTimers (node:internal/timers:519:7)”,“name”:“AbortError”}}

“Failed to communicate with Rocket.Chat Cloud”,“url”:"https://releases.rocket.chat/v2/server/supportedVersions",“err”:{“type”:“FetchError”,“message”:"request to https://releases.rocket.chat/v2/server/supportedVersions failed, reason: ",“stack”:“FetchError: request to https://releases.rocket.chat/v2/server/supportedVersions failed, reason: \n at ClientRequest. (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1501:11)\n at ClientRequest.emit (node:events:519:28)\n at ClientRequest.emit (node:domain:488:12)\n at emitErrorEvent (node:_http_client:108:11)\n at TLSSocket.socketErrorListener (node:_http_client:511:5)\n at TLSSocket.emit (node:events:519:28)\n at TLSSocket.emit (node:domain:488:12)\n at emitErrorNT (node:internal/streams/destroy:169:8)\n at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n at processTicksAndRejections (node:internal/process/task_queues:82:21)”,“errno”:“ETIMEDOUT”,“code”:“ETIMEDOUT”,“name”:“FetchError”}}

“Failed to get Checkout URL with Rocket.Chat Billing Service”,“url”:“/api/v2/checkout”,“err”:{“type”:“CloudWorkspaceAccessTokenEmptyError”,“message”:“Workspace access token is empty”,“stack”:“Error: Workspace access token is empty\n at getWorkspaceAccessTokenOrThrow (app/cloud/server/functions/getWorkspaceAccessToken.ts:82:9)\n at processTicksAndRejections (node:internal/process/task_queues:95:5)\n at getCheckoutUrl (app/cloud/server/functions/getCheckoutUrl.ts:17:17)\n at ee/server/requestSeatsRoute.ts:28:71”}}

**Comment by reetp** [comment]
> Same issue here, but no way to fix/resync the license, since the workspace wouldn't connect to Rocket Chat Cloud anymore.

Lucky I spotted this. Replying to old closed issues is not good. And really this is support rather than a bug so should be asked in the appropriate place:

[Open Support](https://open.rocket.chat/channel/support)
[Forums] (https://forums.rocket.chat/)

What licence are you on please?
How many users?

Note:

> CE no longer supports airgapped. You need a licence.

Starter is free for 50 users.

**Comment by saschafoerster** [comment]
@reetp I am really annoyed, that you don't seem to understand the issue, that is on the side of RocketChat. Anyway, are you part of the team of RocketChat? Or are you just here to annoy users? 
 If yes, you destroy my trust in RocketChat and I will more and more look into other solutions, if your are not able to stop blaming us for "holding it wrong": 

- We use starter license with a RocketChat server, that is and was NOT air gapped. 
- RocketChat then stops working, as it thinks it IS airgapped, when it IS NOT airgapped. 
- RocketChat is having a bug in correctly recognizing, that an instance is not airgapped, when it has internet connection and then stops working. It should not stop working, as it is having an internet connection. 
- Support will not help, as the starter-license is not having any support included (I asked them already and get a reply, that we should go to Github).  And it's a bug, not "you are holding it wrong" and need support. 

But this is my last comment to this, ever.

**Comment by reetp** [comment]
So please don't `@` me. No, I don't work here. I do what I can do to help as a volunteer and don't need abuse thanks.

I do have extremely good contacts in Rocket and as a result I am probably the best chance of a solution. So don't shoot the messenger.

I am trying to understand each persons situation so we can fix them specifically - too many 'metoos' here with no specifics mean we are guessing and get no fixes. The devs will not listen to vague waffle - they want hard facts. We need to make it easy for them.

> I am really annoyed,

You may well be. That doesn't give you the right to have a go at me. You can of course complain to Rocket.Chat but.....

> Support will not help, as the starter-license is not having any support included (I asked them already and get a reply, that we should go to Github). 

You get what you pay for.  Sorry. That's the terms and conditions you agreed to.

Note you also opened this in mid November - 3 months ago -  then disappeared and now back again? I have no idea if your install is working or not now. What happened in the meantime?

I had asked you to do this as well 

> You need to log into the docker shell via docker -it exec blah and test your network connectivity.

Test with:

`wget https://releases.rocket.chat/v2/server/supportedVersions`

That never appeared to happen.

> * We use starter license with a RocketChat server, that is and was NOT air gapped.

Ummmmm but you said above:

> I switched from starter license to community license
> License Type: Community

What can I say?

I also remember your case was slightly odd because of this comment:

> Thats what I thought. But there is a difference between the role "users" and "guests". The starter plan only counts "the users", but has 0 places for guest (which is a bug in my opinion).

I'm wondering if you are doing something that trips you over the user limit eg permitting open guest registration that you do not monitor. But you haven't said any of that so hard to know.

> But this is my last comment to this, ever.

A bit shortsighted IMHO. In which case we can't get you a solution then.

Your issue is possibly an issue with the licence - pre v7 the backend cloud would get in a knot if you downgraded to CE and then tried to upgrade back to Starter but that should be fixed now.

More likely it is to do with your server/network, or possibly do with your comment on users.

But unless we can try and nail it down we can't fix it.

If you want a fix you need to answer some of my questions so I can speak to the right person for an answer.

Thanks.

**Comment by MarcosSpessatto** [comment]
@saschafoerster The analysis indicates this issue is likely a false positive, potentially resulting from an upgrade scenario. If a previous version, where statistics reporting was optional and manually disabled, was upgraded, the workspace may not have transmitted usage reports. Consequently, cloud acknowledgment, which is used to determine air-gapped status, would be absent.

While typically resolved upon reconnection to cloud synchronization, the migration to the Community Edition may have introduced a conflicting condition. The absence of prior statistics transmission likely led the workspace to incorrectly identify itself as an air-gapped instance.

To further investigate, please verify if any records exist within the `rocketchat_statistics` collection containing the `statsToken` property and let me know.

**Comment by tim-tation** [comment]
@reetp sorry for that, but for my understanding this topic did not get solved, I'm here with @saschafoerster we never were air-gapped, aren't and don't want to be. But thank you anyway for still willing to help!

We also were Starter at one point, switched to CE way before and it worked as a charme for probably over a year. Just now with 7.0.0 we're told to be a air-gapped workspace.

wget https://releases.rocket.chat/v2/server/supportedVersions gives me...

https://releases.rocket.chat/v2/server/supportedVersions
Resolving releases.rocket.chat (releases.rocket.chat)... 2606:4700:10::6816:2d88, 2606:4700:10::6816:2c88, 2606:4700:10::ac43:2a33, ...
Connecting to releases.rocket.chat (releases.rocket.chat)|2606:4700:10::6816:2d88|:443... connected.
HTTP request sent, awaiting response... 200 OK

docker exec -it <container> sh
wget https://releases.rocket.chat/v2/server/supportedVersions
... will stuck on
Connecting to releases.rocket.chat (172.67.42.51:443)
wget: can't connect to remote host (172.67.42.51): Operation timed out

@MarcosSpessatto thank you, too!
db.rocketchat_statistics.find({}, {"statsToken":1})
gies me 20 lines of { _id: 'XXXXXXXXXXX' }

**Comment by reetp** [comment]
> docker exec -it sh wget https://releases.rocket.chat/v2/server/supportedVersions ... will stuck on Connecting to releases.rocket.chat (172.67.42.51:443) wget: can't connect to remote host (172.67.42.51): Operation timed out

As I suspected - hence the question. If your sever can't contact that IRL you are in trouble.

You might want to consider this - essentially exactly the same symptoms:

https://forums.rocket.chat/t/failure-to-reach-cloud-rocket-chat-servers-from-ovh-instance/19901/17?u=reetp

**Comment by tim-tation** [comment]
That worked for me, too! Yeah juhuuu!
But how can that be? I never even touched the iptables.

**Comment by reetp** [comment]
> That worked for me, too! Yeah juhuuu!

As suspected.

> But how can that be? I never even touched the iptables.

No, but docker does.

You need to read and learn more about the tools you use.

eg

https://docs.docker.com/engine/network/packet-filtering-firewalls/

**Comment by HanadaLee** [comment]
Just for reference

if you are running rocket.chat in mainland China or other countries or regions where there may be Internet restrictions, it may be in read-only mode because it cannot connect to releases.rocket.chat

Currently, all operators in mainland China are unable to run rocket.chat

https://github.com/RocketChat/Rocket.Chat/issues/34863

**Comment by saschafoerster** [comment]
I used the starter license now for some months without really needing it, but it was the only way of getting a working installation, as community license had this "air gapped“-issue blocking our instance. 

Today I downgraded from starter to community license to test again, version 7.3.3, I will see how long it works and then reply. 

I tested: 

```
wget https://releases.rocket.chat/v2/server/supportedVersions
--2025-03-01 14:18:57--  https://releases.rocket.chat/v2/server/supportedVersions
Resolving releases.rocket.chat... 104.22.44.136, 104.22.45.136, 172.67.42.51, ...
Connecting to releases.rocket.chat|104.22.44.136|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'supportedVersions'

supportedVersions                             [ <=>                                                                               ]  21.56K  --.-KB/s    in 0.004s  

2025-03-01 14:19:00 (5.98 MB/s) - 'supportedVersions' saved [22074]


```
Then in docker:

```
 docker exec -it rocketchat-rocketchat-1 sh
/app/bundle $ wget https://releases.rocket.chat/v2/server/supportedVersions
Connecting to releases.rocket.chat (172.67.42.51:443)
saving to 'supportedVersions'
supportedVersions    100% |*********************************************************************************************************************| 22069  0:00:00 ETA
'supportedVersions' saved
/app/bundle $ 
```
Last but not least: 

`db.rocketchat_statistics.find({}, {"statsToken":1})`

Gives me a list of more than 40K items. 

So no firewall issues I guess. I only wonder, why I have so many statsToken.

**Comment by saschafoerster** [comment]
And here we go again, 24h later our workspace is blocked. Our team is now unable to work, when I stay in community edition. But I am ready to help us find the cause. 

<img width="1199" alt="Image" src="https://github.com/user-attachments/assets/c0e13364-6366-41ba-8ef9-a66b0d853999" />
<img width="276" alt="Image" src="https://github.com/user-attachments/assets/c85fa195-35ed-485c-902d-799a18bc0e0f" />

First test: 

```
wget https://releases.rocket.chat/v2/server/supportedVersions
--2025-03-02 16:25:18--  https://releases.rocket.chat/v2/server/supportedVersions
Resolving releases.rocket.chat... 172.67.42.51, 104.22.44.136, 104.22.45.136, ...
Connecting to releases.rocket.chat|172.67.42.51|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'supportedVersions.1'

supportedVersions.1                               [ <=>                                                                                              ]  21.56K  --.-KB/s    in 0.001s  

2025-03-02 16:25:24 (23.8 MB/s) - 'supportedVersions.1' saved [22074]
```
Then second test in the docker-container "rocketchat-rocketchat-1"

```
 wget https://releases.rocket.chat/v2/server/supportedVersions
Connecting to releases.rocket.chat (172.67.42.51:443)
saving to 'supportedVersions'
supportedVersions    100% |****************************************************************************************************************************************| 22074  0:00:00 ETA
'supportedVersions' saved
```

And last in the mongosh, I get all the items as before. 

I saved the log-files and I can sent them via email to the rocketchat-team.

**Comment by saschafoerster** [comment]
When starting I see this: 
`"System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."}
`
and 
`"name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}`

and 
```
"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}
"Callbacks","msg":"Executing callback with id XXXXXXXXXX for hook workspaceLicenseRemoved"}
"System","msg":"Synced with Rocket.Chat Cloud","function":"syncCloudData"}
"System","msg":"Resetting cached value Cloud_Workspace_Supported_Versions_Token in settings"}
"System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."}
"System","msg":"Supported versions","supportedVersionsFromBuild":"2025-03-01T01:14:40.6887489Z","response":"2025-03-02T15:44:39.187148815Z"}
"System","msg":"Using supported versions from cloud"}
```

Restarting the docker container makes it work again. (without switching license, I stay with community for now).

**Comment by HanadaLee** [comment]
> When starting I see this: `"System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."} ` and `"name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}`
> 
> and
> 
> ```
> "System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}
> "Callbacks","msg":"Executing callback with id XXXXXXXXXX for hook workspaceLicenseRemoved"}
> "System","msg":"Synced with Rocket.Chat Cloud","function":"syncCloudData"}
> "System","msg":"Resetting cached value Cloud_Workspace_Supported_Versions_Token in settings"}
> "System","msg":"Workspace credentials cache hit using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register. Avoiding generating a new access token from cloud services."}
> "System","msg":"Supported versions","supportedVersionsFromBuild":"2025-03-01T01:14:40.6887489Z","response":"2025-03-02T15:44:39.187148815Z"}
> "System","msg":"Using supported versions from cloud"}
> ```
> 
> Restarting the docker container makes it work again. (without switching license, I stay with community for now).

I solved the problem by hijacking the following domains in the container and forwarding them to other servers that can access rocketchat official. You can check the connectivity with these domains. collector.rocket.chat plays a decisive role

    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    extra_hosts:
      - go.rocket.chat:172.17.0.1
      - open.rocket.chat:172.17.0.1
      - docs.rocket.chat:172.17.0.1
      - developer.rocket.chat:172.17.0.1
      - nps.rocket.chat:172.17.0.1
      - omni-gateway.rocket.chat:172.17.0.1
      - billing.rocket.chat:172.17.0.1
      - releases.rocket.chat:172.17.0.1
      - marketplace.rocket.chat:172.17.0.1
      - collector.rocket.chat:172.17.0.1

**Comment by saschafoerster** [comment]
Some more logs, that are hopefully helping. 

```
{"level":20,"time":"2025-03-03T15:12:00.377Z","pid":1,"hostname":"f0b09175340f","name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."} 
{"level":50,"time":"2025-03-03T15:12:09.327Z","pid":1,"hostname":"f0b09175340f","name":"SyncedCron","msg":"Failed to send usage report","err":{"type":"FetchError","message":"request to https://collector.rocket.chat/ failed, reason: getaddrinfo EAI_AGAIN collector.rocket.chat","stack":"FetchError: request to https://collector.rocket.chat/ failed, reason: getaddrinfo EAI_AGAIN collector.rocket.chat<br>    at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1501:11)<br>    at ClientRequest.emit (node:events:518:28)<br>    at ClientRequest.emit (node:domain:489:12)<br>    at emitErrorEvent (node:_http_client:103:11)<br>    at TLSSocket.socketErrorListener (node:_http_client:506:5)<br>    at TLSSocket.emit (node:events:518:28)<br>    at TLSSocket.emit (node:domain:489:12)<br>    at emitErrorNT (node:internal/streams/destroy:170:8)<br>    at emitErrorCloseNT (node:internal/streams/destroy:129:3)<br>    at processTicksAndRejections (node:internal/process/task_queues:90:21)","errno":"EAI_AGAIN","code":"EAI_AGAIN","name":"FetchError"}} 
```
I tried different computers with different internet access to connect to https://collector.rocket.chat, but I always get 404.

**Comment by reetp** [comment]
Note I believe a lot of the team have fiestas right now so answers may be slow for a few days.

**Comment by saschafoerster** [comment]
On 7.4.0 and the version before, it is working some days in a row as community license without being blocked as air-gapped, when its not. I keep an eye on this.

**Comment by pierre-lehnen-rc** [comment]
looks like two separate issues around the same thing:
1. Failure to send stats to `collector.rocket.chat`.
2. When a License is removed, rocket.chat assumes that "newest stats have not been synced" == "sync doesn't work" == "air-gapped", which is also wrong.

**Comment by saschafoerster** [comment]
This morning, the chat was blocked again, 7.4.0. I am ready to test whatever is needed to find out what creates this issue.

**Comment by gabriellsh** [comment]
Hi @saschafoerster, how are you doing? I think I might now the cause but I need you to follow a few steps. Maybe some I'll say has already been said, but I'll try to be clearer and include all the steps at once.

1. First, I need you to test the server's connection to `https://collector.rocket.chat/`. This is the only relevant endpoint for the airgapped restriction. Every time you start the server, or every 12 hours after the first time IIRC, the rocket.chat server collects statistics and tries to send them to that URL. This request responds with a signed token with a date, which is then decoded and used as "proof" that the sync happpened. If that request fails, there will be no token, thus the workspace getting locked to read-only.

2. If the collection failed at any point, in `Admin -> Reports` there should be a log starting with `Failed to send usage report ...` with a description of an error. I don't think these logs are persistent so if you restarted your server and the connection was successful, it won't show that error there. BUT, it means that maybe subsequent requests are failing

  2.1. Now here's a real issue: Supposedly the last existing TOKEN should be used if subsequent request are made. Right now after investigating a little bit, I think it's actually the last RECORD in the collection that is being used instead, despite such token existing or not.

  2.2. Is it possible by any chance that you can query the DB directly? If so, find all records in the `rocketchat_statistics` collection with the following options: `{ sort: { createdAt: -1 }, projection: { statsToken: 1 }, limit: 10 }` (Feel free to hide any valid token if you feel like it, but dont leave it empty so we can check in which records they exist).

**Comment by saschafoerster** [comment]
Hi @gabriellsh, thank you for your help: 

As there were many updates in the last days, I had plenty of restarts, so I maybe need to wait some more days without upgrades. Now step by step: 

1. I can connect to collector: 

```
/docker/rocket.chat$ curl -v https://collector.rocket.chat
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/2
> Host: collector.rocket.chat
> user-agent: curl/7.86.0
> accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 404 
< date: Thu, 13 Mar 2025 12:37:44 GMT
< content-type: text/plain
< content-length: 18
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 91fb95941c591629-DUS
< alt-svc: h3=":443"; ma=86400
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):


```
2. I did not find any mention of "usage reports", but I will wait some more days without updates and see if they appear. 

Here is the obfuscated export of the database query: 

```
rs0 [direct: primary] rocketchat> db.rocketchat_statistics.find(
...   {}, 
...   { statsToken: 1 }
... ).sort(
...   { createdAt: -1 }
... ).limit(10)
[
  {
    _id: '67d141d0cf9056893951cff0',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67ce9ed0cf9056893951cc89',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67cbfbd1cf9056893951c97a',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67ca9c40f50ab3d3b81fb3c6',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67c869c0e6f81583778a5efd',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67c5c6c060013bfcb413a8a1',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67c459206f7b3c251454b8f3',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67c2b30c79d4ba7edbbb2b56',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67bd6d406819765582cb9965',
    statsToken: 'eyOBFUSCATED'
  },
  {
    _id: '67baca406819765582cb9707',
    statsToken: 'eyOBFUSCATED'
  }
]
```

Hope this helps, else let me know. :)

**Comment by saschafoerster** [comment]
Okay, this morning the chat was blocked again: 

I searched for collector in the logs: 

```
rocketchat-rocketchat-1  | {"level":20,"time":"2025-03-14T07:12:00.513Z","pid":1,"hostname":"90bf9f1a40f8","name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}
rocketchat-rocketchat-1  | {"level":50,"time":"2025-03-14T07:12:10.571Z","pid":1,"hostname":"90bf9f1a40f8","name":"SyncedCron","msg":"Failed to send usage report","err":{"type":"FetchError","message":"request to https://collector.rocket.chat/ failed, reason: getaddrinfo EAI_AGAIN collector.rocket.chat","stack":"FetchError: request to https://collector.rocket.chat/ failed, reason: getaddrinfo EAI_AGAIN collector.rocket.chat\n    at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:524:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at processTicksAndRejections (node:internal/process/task_queues:90:21)","errno":"EAI_AGAIN","code":"EAI_AGAIN","name":"FetchError"}}
```

I tried this inside the container and I've got a connection: 

```
/app/bundle $  nslookup collector.rocket.chat
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
collector.rocket.chat	canonical name = collector.rocket.chat.cdn.cloudflare.net
Name:	collector.rocket.chat.cdn.cloudflare.net
Address: 2606:4700:10::6816:2c88
Name:	collector.rocket.chat.cdn.cloudflare.net
Address: 2606:4700:10::6816:2d88
Name:	collector.rocket.chat.cdn.cloudflare.net
Address: 2606:4700:10::ac43:2a33

Non-authoritative answer:
collector.rocket.chat	canonical name = collector.rocket.chat.cdn.cloudflare.net
Name:	collector.rocket.chat.cdn.cloudflare.net
Address: 172.67.42.51
Name:	collector.rocket.chat.cdn.cloudflare.net
Address: 104.22.45.136
Name:	collector.rocket.chat.cdn.cloudflare.net
Address: 104.22.44.136
```
I hope somebody can help

**Comment by Tuurlijk** [comment]
@saschafoerster What fixed it for me was to add 1.1.1.1 and 8.8.8.8 as preferred dns servers in the docker-compose.yaml file:

```yaml

  rocketchat:
    image: ${IMAGE:-registry.rocket.chat/rocketchat/rocket.chat}:${RELEASE:-latest}
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.entrypoints: "websecure"
      traefik.http.routers.rocketchat.tls: true
      traefik.http.routers.rocketchat.tls.certresolver: myresolver
      traefik.http.routers.rocketchat.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.rocketchat.middlewares: "${TRAEFIK_MIDDLEWARES:-development@file},securityHeaders@file"
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: ${ROOT_URL:-http://localhost:3000}
      HOST_PORT: ${HOST_PORT:-443}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
    depends_on:
      - mongodb
    dns:
      - 1.1.1.1
      - 8.8.8.8
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"
```

**Comment by gabriellsh** [comment]
@saschafoerster EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error. In this case, the connection did fail, meaning a token was not retrieved, and thus blocked the workspace.

You might've noticed that the issue was closed automatically, because a PR with the fix was merged. This one https://github.com/RocketChat/Rocket.Chat/pull/35456

The PR won't fix any connection error, but it will prevent the workspace from being locked in the event that a fetch to collector fails. This should've been the case from the start, but we were getting the last record instead of the last token. As soon as 7.5 is released and you upgrade to it you will face less disruptions in your workspaces.

You just have to make sure that at least one of those connections succed every 3 days at least once, or a warning will be displayed. After 7 days of that warning, the workspace will be locked.

Just to make it more clear, it was indeed an issue, but the connection remains necessary. It should always give you plenty of time before a lock from now on.

**Comment by dahaiaqsw** [comment]
> Okay, this morning the chat was blocked again:
> 
> I searched for collector in the logs:
> 
> ```
> rocketchat-rocketchat-1  | {"level":20,"time":"2025-03-14T07:12:00.513Z","pid":1,"hostname":"90bf9f1a40f8","name":"System","msg":"Workspace credentials cache miss using scope: workspace:license:read workspace:client:write workspace:stats:write workspace:push:send marketplace:read marketplace:download fedhub:register, fetching new access token from cloud services."}
> rocketchat-rocketchat-1  | {"level":50,"time":"2025-03-14T07:12:10.571Z","pid":1,"hostname":"90bf9f1a40f8","name":"SyncedCron","msg":"Failed to send usage report","err":{"type":"FetchError","message":"request to https://collector.rocket.chat/ failed, reason: getaddrinfo EAI_AGAIN collector.rocket.chat","stack":"FetchError: request to https://collector.rocket.chat/ failed, reason: getaddrinfo EAI_AGAIN collector.rocket.chat\n    at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:524:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at processTicksAndRejections (node:internal/process/task_queues:90:21)","errno":"EAI_AGAIN","code":"EAI_AGAIN","name":"FetchError"}}
> ```
> 
> I tried this inside the container and I've got a connection:
> 
> ```
> /app/bundle $  nslookup collector.rocket.chat
> Server:		127.0.0.11
> Address:	127.0.0.11:53
> 
> Non-authoritative answer:
> collector.rocket.chat	canonical name = collector.rocket.chat.cdn.cloudflare.net
> Name:	collector.rocket.chat.cdn.cloudflare.net
> Address: 2606:4700:10::6816:2c88
> Name:	collector.rocket.chat.cdn.cloudflare.net
> Address: 2606:4700:10::6816:2d88
> Name:	collector.rocket.chat.cdn.cloudflare.net
> Address: 2606:4700:10::ac43:2a33
> 
> Non-authoritative answer:
> collector.rocket.chat	canonical name = collector.rocket.chat.cdn.cloudflare.net
> Name:	collector.rocket.chat.cdn.cloudflare.net
> Address: 172.67.42.51
> Name:	collector.rocket.chat.cdn.cloudflare.net
> Address: 104.22.45.136
> Name:	collector.rocket.chat.cdn.cloudflare.net
> Address: 104.22.44.136
> ```
> 
> I hope somebody can help

Sir，Is your problem fixed?

**Comment by danielmunoz** [comment]
I having a bit of the same issue. I use Rocket-Chat 6, Community Edition, in Ubuntu Server LTS 24.04, installed via snap.
If I update from 6 to 7 (direct update, or new server install restoring the backup) I have about the same issues described here: it thinks it is air gapped, so it cannot "validate" the free license.
I have virtual machines and backups, so I tried several times with no success.
Something seems wrong in Rocket-Chat 7. IDK. Maybe.

The worst of all this is that the client apps will be incompatible with Rocket-Chat 7 starting April 30.

```
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: [2025-04-23T19:18:53.126Z] INFO  e559a7a4-841a-4e06-a20d-e521cd34a7d6/BROKER: Registered 13 middleware(s).
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: [2025-04-23T19:18:53.128Z] INFO  e559a7a4-841a-4e06-a20d-e521cd34a7d6/BROKER: Transporter: TcpTransporter
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: {"level":30,"time":"2025-04-23T19:18:53.147Z","pid":3310,"hostname":"cohete7","name":"QueueWorker","msg":"Creating indexes for queue worker"}
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: {"level":51,"time":"2025-04-23T19:18:53.152Z","pid":3310,"hostname":"cohete7","name":"DatabaseWatcher","msg":"Using change streams"}
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: === UnHandledPromiseRejection ===
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: InvalidLicenseError: Invalid license
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]:     at validateFormat (/snap/rocketchat-server/1670/programs/server/npm/node_modules/@rocket.chat/license/src/validation/validateFormat.ts:12:9)
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]:     at processTicksAndRejections (node:internal/process/task_queues:105:5)
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]:     at LicenseImp.setLicense (/snap/rocketchat-server/1670/programs/server/npm/node_modules/@rocket.chat/license/src/license.ts:252:9)
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: ---------------------------------
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: Errors like this can cause oplog processing errors.
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: Future node.js versions will automatically exit the process
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: =================================
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: {"level":30,"time":"2025-04-23T19:18:53.330Z","pid":3310,"hostname":"cohete7","name":"QueueWorker","msg":"Registering workers of type \"work\""}
Apr 23 19:18:53 cohete7 rocketchat-server.rocketchat-server[3310]: {"level":30,"time":"2025-04-23T19:18:53.330Z","pid":3310,"hostname":"cohete7","name":"QueueWorker","msg":"Registering workers of type \"workComplete\""}
```

**Comment by saschafoerster** [comment]
@gabriellsh The issue is back for me as well. Would you maybe re-open?

**Comment by saschafoerster** [comment]
I will now try the DNS workaround (just with other DNS then the mentionned ones).

**Comment by reetp** [comment]
These issues are NOT related. Please do not waste time referencing issues that are irrelevant just because you are angry - or frustrated. You will just get ignored.

If you have a paid licence then contact support which you have paid for.

If not, this is open source. There are zero guarantees.

You make no mention of current version, whether you have upgraded etc.

You have already been advised this is likely a DNS related issue, though there may be an issue fixed in later versions, but you fail to state anything concrete.

You need to be crystal clear with your data. Versions, tests, etc.

Please focus. That way you may get some help.

**Comment by gabriellsh** [comment]
Hey @reetp indeed the DNS issues are not a priority here, but there's some (or should be) safeguards regarding this verification. Even if a request fails, it should only restrict a workspace after the warning period ends. Which I don't think is the case here.

@saschafoerster I'll try to simulate a network issue by blocking the cloud domains, I'll get back to you.

**Comment by saschafoerster** [comment]
@gabriellsh Thank you. Looking forward in testing this with the next releaes.
