### ISSUE TITLE
Email verification not working when MAIL_URL env variable is passed

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#3602]
Your Rocket.Chat version: 0.34

I pass the env variable MAIL_URL properly. I manage to send emails by other means.

I see 2 strange things:
- email - smtp section is not populated
- when I go to account - registration - email verification, it show me the following warning:
  `Make sure you have correct SMTP settings to use this feature`

Let me know If I could help debug that?

Thanks!

**Comment by sadeva** [comment]
Hi @pierreozoux,

Did you install it on a docker container? And what email provider do you use?

Maybe you can try encoding the SMTP credentials, especially if the username contains `@`.

**Comment by pierreozoux** [comment]
I do use the docker container (I helped designing it :) ).
I am my own SMTP provider :) - https://indiehosters.net

I don't understand what you mean by "try encoding the SMTP credentials".

My understanding is that:
 - if I populate the env `MAIL_URL`, it should populate the `SMTP` section in `email` settings.

Do you want screenshot to confirm what I'm saying? I could also provide an "ephemeral" instance with this particular problem. But just start an instance with the `MAIL_URL` you should be able to reproduce.

Let me know if there is anything I can help on!

**Comment by TheReal1604** [comment]
@pierreozoux In my docker-compose deployment the mail env is working in docker, please check the correct syntax:

`MAIL_URL=smtp://yourmailbox@yourdomain.com:yourpassword@smtp.yourmailserver.com:465/`

Or can you post your anonymized `MAIL_URL` env variable here?

**Comment by pierreozoux** [comment]
My env:

```
MAIL_URL=smtp://noreply.chat.indie.host@indie.host:mypass@mail.indie.host:587/
```

What do you mean it is working, can you go to:
 - `administration` - `email` - `smtp` and tell me if it is populated or not?
 - `administration` - `account` - `registration` - `email verification` and tell me if you get a warning?

Thanks!

**Comment by TheReal1604** [comment]
Yes it's populated. And no, I got no error in this view. 

Your mail Url looks fine. Can you share your docker compose or docker command with us?

**Comment by TheReal1604** [comment]
Just an idea.. Can you test another mailbox for that with not that much "." In it. Just a noreply@indie.host for example?

**Comment by pierreozoux** [comment]
Ok, just go there:

https://test-mail-url.indie.host/admin/Email

username: admin
pass: testtest

check it there, you'll see, everything is as described.

And I can send email actually.

And here is the env variable from within the container:
MAIL_URL=smtp://noreply.test-mail-url.indie.host@indie.host:iCIVEgD1XgPPbgkODJu8@mail.indie.host:587/

Actually the mail sent is without from field.

(I'll delete everything, once fixed)


On 29-06-2016 15:51, TheReal1604 wrote:
> Just an idea.. Can you test another mailbox for that with not that much
> "." In it. Just a noreply@indie.host <mailto:noreply@indie.host> for
> example?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/3602#issuecomment-229380962>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABxvHTwGAG2zYLbe6lIWPgRPEk2zqegzks5qQoaKgaJpZM4I69Vr>.
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by TheReal1604** [comment]
I checked the smtp settings and know what you mean. Can you test please, if it is working with a simpler mailbox name? Like test@indie.host? 

And please post your anonymised docker-compose file or the docket command you run. Thanks!

**Comment by sadeva** [comment]
Hi @pierreozoux, I have setup your mail. Do you get a test email in your inbox?
I've got one, so it should be working now.

**Comment by thiesschneider** [comment]
perhaps you have an @ in your password so the string is not passed correctly to rocketchat?

**Comment by pierreozoux** [comment]
@sadeva of course you can configure email in the web UI. The bug is that, it should pick it from env.

@thiesschneider thanks for the suggestion, but no, there is no @ in the password.

@TheReal1604 why removing dots, my username is like this, it should work.

I did a test again, and still the same behavior:


    administration - email - smtp is not populated from env var.
    administration - account - registration - there is a warning `Make sure you have correct SMTP settings to use this feature`

I'd like to be able to setup a full rocket.chat instance, unattended. So Rocket.Chat should be able to configure everything from env var MAIL_URL.

Here the current test instance:
https://test.indie.host
admin/testtest

env:
MAIL_URL=smtp://test2@indie.host:3Q9jAGAwXZW8@mail.indie.host:587/
(see I removed the dots, but still the same :) )

If there is anything I can help to debug this, let me know :)

Thanks!

Pierre

**Comment by pierreozoux** [comment]
closing in favor of #6192
