### ISSUE TITLE
RC 7.7.0 channels with new messages are not getting highlighted

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#36131]
### Description:

In RC 7.7.0 sending messages does not highlight channels after a while. This may be related to ditching of use of oplog in this version.

Workaround is to enable oplog again via running variable, run only one instance / node-process or downgrade to RC 7.6.x.
(There are no schema changes between 7.6.x and 7.7.0 so downgrade is somewhat lower risk operation this time.)

### Steps to reproduce:

1. Keep running RC 7.7.0 with 4 or mode instances (node processes) in an environment with 500+ people
2. Wait for a day
3. Messages start failing to get highlighted (test between two accounts)

For reproducing issue see also detailed explanation in comment on this same issue:
https://github.com/RocketChat/Rocket.Chat/issues/36131#issuecomment-2995554607

### Expected behavior:

Messages get delivered as usual in an instant fashion

### Actual behavior:

Message remains gray. Messages get sent after switching to running only one instance. (This particular gray / slowness issue may have been a fluke by that other bug mentioned in this issue's comments.)

Some channels don't get highlighted even when they have new unread messages in them.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.7.0
- License Type: Premium
- Number of Users: 500+
- Operating System: RHEL8
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: Yes
- NodeJS Version: v22.14.0
- MongoDB Version: 6.0.23 / wiredTiger (oplog Enabled) EDIT: Also MongoDB 7.0.20

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

### Additional context

We did not spot meaningful issues for ~12 hours from moving to use RC 7.7.0. Also we have a restart process that restarts all 4 docker instances every night. We spotted issues immediately in the morning when usage spiked normally.

### Relevant logs:

No logs yet

**Comment by Gummikavalier** [comment]
We are preparing to upgrade MongoDB from 6.0 to 7.0 this evening to see if it has any effect.

If not, we'll use the parameter `DISABLE_DB_WATCHERS=false` to enable oplog support in RC 7.7.0.

Edit: Upgraded to MongoDB 7.0. We'll be wiser tomorrow when the usage peaks in the morning.

**Comment by lovekyleman** [comment]
DISABLE_DB_WATCHERS=false everything is fine 
If no DISABLE_DB_WATCHERS=false and you have multiple instances. Rocketchat has no real time data and messages disappear after sending them 
And also Read receipts stop working

**Comment by Gummikavalier** [comment]
I can confirm that issues continued in under 24 hours from switching from MongoDB 6.0 to 7.0.

At the beginning everything seemed to work ok, but after the initial rush of people coming to work the issue happened again.

We now use `DISABLE_DB_WATCHERS=false` as a workaround to the problem.

**Comment by sampaiodiego** [comment]
> Also we have a restart process that restarts all 4 docker instances every night. 

@Gummikavalier does this process restarts all of them at once or is it a rolling restart? the reason I'm asking is because I was able to find an issue where it can get stuck if it doesn't find any available instance during the startup, in this case adding a new instance will unstuck them, the instance can even be removed later on..

**Comment by Gummikavalier** [comment]
> > Also we have a restart process that restarts all 4 docker instances every night.
> 
> [@Gummikavalier](https://github.com/Gummikavalier) does this process restarts all of them at once or is it a rolling restart? the reason I'm asking is because I was able to find an issue where it can get stuck if it doesn't find any available instance during the startup, in this case adding a new instance will unstuck them, the instance can even be removed later on..

Hi @sampaiodiego ! Our restart script starts two instances at the time at night, and next 2 after brief 10 seconds. So the answer would be maybe, because that second two instances batch starts so close to the first two.

But we disabled that script immediately after the first encounter of issues. The second time we encountered the issue, there had not been new automatic restarts to the services.

Because of the spiking loads when instance comes up, I start the services in day time giving them ~30 seconds time in between. But I may have been too hasty last time (it was evening when I upgraded mongodb and not many users online).

It is Friday now, so it would not be fruitful (not many users) to repeat testing now. But for Monday morning:
We remove the workaround. Then setup a script to stop all, restart 4 instances, two minutes in between of each of them. Then stop the fourth one. And then we wait for reports from the users.

**Comment by Gummikavalier** [comment]
So far I'm uncertain of the results. We have some reports of messages not being delivered or to be exact, when you refresh, you suddenly get more channels in unread state or messages on the channel appear.

I now configured the loadbalancer with sticky sessions so that we can better analyze the state of session per instance. Previously we had these dynamic; any call went to any instance. (There are many reasons why this can be either good and bad, so I won't comment whether sticky sessions should be enabled or not. Now they are.)

Even when I can fully confirm communication happening between my own two separate accounts happening on different instances, I haven't personally been able to reproduce the issue again. At least not yet.
Theoretically it is also possible that sticky sessions may cure the issue depending on how the mechanism for updates operates in RC.

**Comment by Gummikavalier** [comment]
@sampaiodiego I can now confirm that issue remains even when using sticky (IP based) sessions and slow staggered start of the instances in the nightly restart.

We switched back to `DISABLE_DB_WATCHERS=false` now.

I used three different sessions (1 admin, two own sessions) to follow activity on channels, and the second of my own sessions on a different instance failed to update unread status on one channel for ~ 40 minutes.

Only pressing refresh (F5) in the web client updated the status into correct one.

**Comment by bnryz** [comment]
We are also running into this issue with our 4-node RC deployment. Switching back to `DISABLE_DB_WATCHERS=false` resolves the issue for us. It looks like oplog tailing, which is deemed [a critical feature](https://docs.rocket.chat/docs/running-multiple-instances#verify-your-database) for synchronizing multiple RC instances, is on its way out in 8.0. Can we get a confirmation of what the synchronization mechanism is supposed to look like in 8.0? We worry that if we have to revert to DB watchers now to keep our systems working, that an upgrade to 8.0 in the future will be untenable.

**Comment by reetp** [comment]
Still the same on 7.7.1?

Just checking.

**Comment by gemelen** [comment]
I'd assume that nothing changed as it's not accepted as bug so far (and such an environment not considered a main deployment schema, if I understand the documentation correctly).

Only a few people who has a multi-instance deployment with 7.7.0 and later reported it as a problem.

What's a usual way here for the issue to be triaged and thus potentially fixed?

**Comment by reetp** [comment]
> What's a usual way here for the issue to be triaged and thus potentially fixed?

If you have a paid version open a ticket.

If not then have a read here which explains what Rocket & Github.

First three points.

https://gist.github.com/reetp/b0ba4e3d0ea2ff48ca9da00a5a647d42#github

This is where the open source code gets released.

For support on the CE versions use open.rocket.chat or forums.rocket.chat

The devs do look here from time to time, but there is zero guarantee they will do anything.

I try & triage what I can and if I think it is worth them looking at I will flag it internally. But I do not work for Rocket.

Gummi is a EE client and reports issues here, as well as opening a ticket - one of the few communuty minded clients.

So the short answer is use a paid version & get paid support, or use the open source/starter and hope the community may help you, or if it is a well documented issue as above, I may get it raised internally.

**Comment by Gummikavalier** [comment]
I don't dare to try out 7.7.1 without using `DISABLE_DB_WATCHERS=false` in our production.

We are a scientific organization (CSC - IT Center for Science Ltd.) which means our users are more used to bleeding edge software than other types of organizations. But I risk the good will of our users _if_ I do tests unless they are for troubleshooting to create/confirm the issue in the first place for reporting, or expectation of possible fixes afterwards. (They'll come directly at me and ask "Why did you expect that anything had changed when there was no indication of such change?" and call me a fool. Fun side of working in a company full of brainboxes.)

I'll see if I can reproduce the issue in the test environment using sticky sessions. However, there we have only couple of test users.

**Comment by Gummikavalier** [comment]
Ok, I can reproduce the issue (also in RC 7.7.1) pretty consistently by doing following:

EDIT: Removed the need for multi instance setup and sticky sessions to reproduce this issue.
(That was related to other race condition bug mentioned by sampadiego in the comments.)

The setup:
Two separate accounts Alice and Bob, two separate computers with different IP addresses. Remote desktop server is good for this as long as it has different IP address accessing RC.

Strictly speaking the second computer is not necessary to trigger and notice the issue. But it is the only way to be able to keep Bob's client in focus on the test channel to immediately spot when it happens.

Triggering the issue:

1. Create a test channel and join to it with both accounts. You will also need two extra channels for the test.
2. Both users need to be looking at the test channel with browsers. Also the RC browser window needs to remain focused for automatic mark-as-read to happen after receiving messages. (This makes spotting the issue easier.)
3. With the account Alice type in several messages. At the same time pay attention to highlighting of the channel in Bob's view.
4. You see that the Bob's channel gets highlighted and then marked as read again automatically. Increase the pace of sending the messages until highlighting stops happening. The channel should remain non highlighted. (Hammer in 1, enter, 1 enter, 1, enter and keep doing that faster and faster. If the highlighting gets stuck as unread, as Bob visit some other channel, return to test channel, and then repeat this point 4. hammering until the channel status sticks as marked as read instead.)
5. With Bob, switch to another channel so that focus is not on the test channel anymore.
6. Again with Alice type in more messages on the test channel. One should be enough.
7. Note that the test channel does not get highlighted anymore for Bob
8. Any other channels still get highlighted for Bob
9. _If you visit the test channel as Bob, you will see the "missing" messages like there was no issues at all._ You can go to any other channel but this one channel does not get highlighted anymore. _The issue is only with highlighting the channels._
10. If you reload the page (regular F5 is enough in the browser), highlighting of the channel starts working again.Hence also my original subject for this issue is incorrect. It should read: `Highlighting channels stops working`.

I was also able to trigger this to concern all channels after repeating the triggering methods on several channels in a row. Even on ones that had not been involved in the test before started failing to highlight.

You can see when the issue triggers in the test scenario at points 3 and 4. With Bob's windows focused when Bob is facing the same channel, the channel still gets highlighted for a second, and then it gets marked as read again. This automatic highlighting and non highlightning stops happening when the issue has triggered.

Additional note: Rate limiters were off in our test system, so it should not have been throttling getting involved.

**Comment by gemelen** [comment]
> The devs do look here from time to time, but there is zero guarantee they will do anything.
> I try & triage what I can and if I think it is worth them looking at I will flag it internally. But I do not work for Rocket.
> Gummi is a EE client and reports issues here, as well as opening a ticket - one of the few communuty minded clients.

Thank you for the efforts.

Just to make it clear, my assumptions in the previous reply were based on my review of changes between 7.7.0 and 7.7.1, not just out of thin air.

And to provide another angle for the problem:
my setup is a kubernetes deployment, RC 7.7.0, two pods with RC, two+arbiter with Mongo 7.0 - I see the same behaviour as the original poster

**Comment by pierre-lehnen-rc** [comment]
Just to clarify: Do you still experience issues with grey messages / slowdowns too, or only the issue with rooms not being flagged as unread?

If the problem is only with the highlighting, then it looks similar to an issue I've tried to debug before but was unable to reproduce consistently. I'll try following your instructions, but this may take me some time still.

On the mean time if you can reproduce it consistently on your setup, can you check two things for me?

1. On Bob's view, open the browser's developer tools, go to the network tab and then filter by websockets ("Socket" in chrome, "WS" in firefox). Clear the list and refresh the tab, then follow the steps to trigger the issue. Once it happens, check back on the network tab to see how many websockets it lists (if you're able to export the messages from those sockets, even better).

2. After the issue happened, don't refresh the browser yet. Try navigating between channels as Bob and check if the problem goes away on its own. If not, wait a couple minutes and try navigating again and check once more.

**Comment by Gummikavalier** [comment]
@pierre-lehnen-rc I think that slowdown issue was a separate and may have been part of that race condition thing sampaiodiego mentioned with several instances starting at the same time.

I still have the setup, but it takes a while to do the testing. But I'll report back evening at latest what I can see.

**Comment by Gummikavalier** [comment]
@pierre-lehnen-rc Ok, test done. I'm using Firefox.

1. On Bob's view, after the issue has been triggered (required only 3 - 4 messages this time).

Highlighting stops working. I can see only one websocket in the list, the same that was opened when reload/refresh was done in the beginning of the test.

I moved to other channel as Bob. I send new messages onto test channel as Alice. I can see that Bob's websocket's `Response` view reacts to the messages with `stream-room-messages` event that contains the channel, sender's name and message of the newly sent message.
```
{"msg":"changed","collection":"stream-room-messages","id":"id","fields":{"eventName":"826a6PiXqaaiwnrt6","args":[{"_id":"GmS7KjXeJjgWs3bCP","rid":"826a6PiXqaaiwnrt6","msg":"1","ts":{"$date":1750864716596},"u":{"_id":"asdfasdfasdfasdf","username":"alice","name":"Alice"},"_updatedAt":{"$date":1750864716612},"urls":[],"mentions":[],"channels":[],"md":[{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"1"}]}]}]}}
```
So indeed the messages are getting transferred all the time.

(Personal note: not all channels are handled like this; it seems there is some kind of focus mechanism. Channels you haven't visited lately don't get updated with messages all the time by this message stream, but they use only notify stream.)

_Before the issue has been triggered_ Bob also gets these notify type messages:
```
{"msg":"changed","collection":"stream-notify-user","id":"id","fields":{"eventName":"xbYA2GYcfcuJjdGCf/subscriptions-changed","args":["updated",{"_id":"680c8869e06b5051f969994c","open":true,"alert":true,"unread":0,"userMentions":0,"groupMentions":0,"ts":{"$date":1745651817779},"rid":"826a6PiXqaaiwnrt6","name":"message-testing1","fname":"message-testing1","customFields":{},"t":"c","u":{"_id":"qwerqwerqwerqwer","username":"bob","name":"Bob"},"_updatedAt":{"$date":1750865189405},"ls":{"$date":1750865189405}}]}}
```
When highlighting stops working, Bob stops getting these `stream-notify-user` messages for that particular channel completely. Only `stream-room-messages` still work.

At this point of the issue `steam-notify-user` messages still work for channels that you have not yet visited earlier. But after you visit them (and get this assumed "recent focus treatment" of mine), those channels seem to stop getting notify messages too, and they stop highlighting too. So eventually the issue "spreads" and users start noticing it better.

So as far as I can see, this seems to be an issue in the stream management, but I cannot tell whether it is client's job to inform the server of state of channels that now fail, or is it server end malfunctioning in some way. Since reload of the browser client end helps, I suspect former.

2. Waiting or navigating other channels does not seem to cure the situation at the Bob's end. On the contrary; visiting other channel triggers the issue on them too after the original highlighting issue has begun.

I also switched between different presence states manually in case streams get disabled for some presence fluke. But only reload makes highlighting and notify stream work again on those malfunctioning channels.

**Comment by Gummikavalier** [comment]
Regarding the amount of websocket connections; I did get two of them after few reloads couple of times, but the triggering factor was always the reload itself.

The highlighting / `stream-notify-user` issue happened in my tests with one.

**Comment by pierre-lehnen-rc** [comment]
That actually clarifies a lot, thanks!

I had personally noticed the `subscriptions-changed` notification not reaching the client before but I always thought it was related to the client's websocket jumping from an overloaded server instance into a new one - something that had happened a lot on the same environment where I had noticed the issue but apparently for this case it was just a coincidence. That explains why I couldn't force the error by causing reconnections.

The main difference is that in the cases I saw it happen before, it would only happen for one single message and then with the next one everything would resume working again.

> but I cannot tell whether it is client's job to inform the server of state of channels that now fail, or is it server end malfunctioning in some way.

The client tells the server what it wants to be notified about, and the server then sends those notifications every time something changes in a resource that the client is interested on. In this case it seems like the client is still expecting to receive the notifications but the server is not sending them.

The fact that a refresh restores it seems to indicate that the server is "losing track" of the client's request, but I don't think that's really it. Specially because disabling db watchers would have no impact on that.

Looking at the code I think that the server not sending the notification might not be the real issue, but just another symptom of something else deeper down. I'll run some tests to confirm this and update here when I have more news. If I'm right then the problem might be completely unrelated and much older, with things working properly with db watchers only because db watchers may sometimes send redundant notifications.

**Comment by Gummikavalier** [comment]
@pierre-lehnen-rc You can also scratch the multi instance and sticky sessions configuration from the test scenario completely. I just tested that to reproduce this highlighting issue, running one instance without `DISABLE_DB_WATCHERS=false` seems to be enough. Makes sense too. :)

You may still want to keep Alice and Bob on separate computers, as it allows keeping Bob's view in focus to immediately spot when the issue triggers. I was able to reproduce it on one computer and one server instance also.

This further alleviates that my original reported "messages don't get delivered" issue was a completely separate case commented by @sampaiodiego here: https://github.com/RocketChat/Rocket.Chat/issues/36131#issuecomment-2946305723

**Comment by pierre-lehnen-rc** [comment]
Yep, I managed to see it happening on my local instance shortly after sending that message, but it's quite hard to get it to happen this way because as it turns out, this is a race condition and running locally with a single instance the window of opportunity for it to happen is much smaller than in a complex setup.

The cause is some optimizations we made for very large rooms. In short when we flag a room as 'unread' the logic that determines if a notification must be sent is not directly tied to an actual write operation on mongo and one of them may end up happening without the other.

Then if the client thinks the room is already 'read' when it isn't, it won't try to change its state anymore either, which makes the channel continue showing up as 'read' until some user action causes it to get synced again (there's a few that would do this)

With db watchers the notification was directly tied to the data changing on mongo so there was no way to get desynced.

**Comment by himpierre** [comment]
Has this been fixed with 7.7.2? Hesitating to upgrade because of this bug.

**Comment by Gummikavalier** [comment]
7.7.2 docker image not yet available so I haven't been able to test it for that yet.

But you can always use `DISABLE_DB_WATCHERS=false` variable in your deployment to work around the problem. There is no issue on 7.7.0 and 7.7.1 when you use this.

**Comment by himpierre** [comment]
Yeah. Perhaps I'm gonna do that if it turns out the bug hasn't been fixed with 7.7.2.

cheers!

**Comment by Gummikavalier** [comment]
For the record, I tested 7.7.3 and 7.8.0-rc.7 and this still happens on both. Very easily even in one instance, two client computers scenario.

We'll probably have to wait longer until the real cause of this issue surfaces and can be fixed, as hinted by pierre-lehnen-rc.

**Comment by himpierre** [comment]
Thanks for the heads-up.

cheers!

Am 3. Juli 2025 17:28:06 MESZ schrieb Gummikavalier ***@***.***>:
>Gummikavalier left a comment (RocketChat/Rocket.Chat#36131)
>
>For the record, I tested 7.7.3 and 7.8.0-rc.7 and this still happens on both. Very easily even in one instance, two client computers scenario.
>
>We'll probably have to wait longer until the real cause of this issue surfaces and can be fixed, as hinted by pierre-lehnen-rc.
>

**Comment by casalsgh** [comment]
Folks, Team is working on items related to this. For now, if all pod/services have  flag DISABLE_DB_WATCHERS=false releases 7.7.x and 7.8.x are expected to work fine

**Comment by casalsgh** [comment]
still no ETA, but is being analyzed

**Comment by ggazzo** [comment]
it should be closed by https://github.com/RocketChat/Rocket.Chat/pull/36433 please @Gummikavalier check

**Comment by Gummikavalier** [comment]
Thanks, I'll test within two days. 👍

**Comment by lovekyleman** [comment]
7.8.1 doesn't fix the issue

**Comment by Gummikavalier** [comment]
For us 7.8.1 does seem to fix the highlight issue in our test environment at least. Note that you may have to reload the web client after the upgrade before testing.

I'll still do further testing and next week in production too.

**Comment by ggazzo** [comment]
@lovekyleman Can you check if we are talking about exactly the same issue? I think the problem of subscription not being marked as unread in the sidebar has been satisfactorily solved. is your procedure to reproduce the same?

**Comment by pierre-lehnen-rc** [comment]
I tested the process extensively here today and turns out there were multiple different problems with that same code.

#36433 solved some problems that ultimately had the same effect as the issue reported here, but was not exactly the same thing (or at least not the same as the issue I reproduced on my tests). 

Another relevant PR included on 7.8.1 was #36463. This one changed how the client sends the requests to flag a room as read. It doesn't fix the server problem by itself, but it may have affected how easy it is to reproduce it locally.

I've now added a new fix on #36472 that will ensure that the server doesn't flag any room as unread unless a notification is also being sent to the clients about it.

**Comment by Gummikavalier** [comment]
@pierre-lehnen-rc @ggazzo 

We have not spotted issues since upgrading our main production system to 7.8.1 during the weekend and removing `DISABLE_DB_WATCHERS=false` from the env.

Also now running on RC 7.8.2 since this morning.

I'll keep this open for a while, but close the issue by the end of the week if the status remains ok.

**Comment by Gummikavalier** [comment]
There has not been any comments from our user base since the upgrade to 7.8.1 / 7.8.2 for a week. Works well enough and I'm closing this issue.

Note: At the time of closing https://github.com/RocketChat/Rocket.Chat/pull/36472 had not been implemented yet, so some issues may still crop up.

**Comment by Gummikavalier** [comment]
This read state change may be related to Firefox freezing badly with accounts that have high amount of channels:
https://github.com/RocketChat/Rocket.Chat/issues/36643

**Comment by reetp** [comment]
A 'FWIW'

Also seen reports that on desktop FF 141+ has some "local" AI for 'smart' tab grouping (why???) that may affect performance.
