### ISSUE TITLE
Incoming webhook payload is empty due to script compilation failure

### ISSUE THREAD

**Issue by mkd2380** [RocketChat/Rocket.Chat#37800]
When storing JavaScript scripts for the bot in the Rocket.Chat, the bot was sending empty payloads.
Upon inspection, the database-stored script had a syntax error and the compiled field was empty.
Manually compiling the script in the database resolved the issue, and the bot started processing webhooks correctly

### Steps to reproduce:

1. Go to 'Integrations' 
2. Click on 'New for creating Incoming WebHook Integration' 
3. write your scripts and save

### Expected behavior:

Scripts stored in the database should compile automatically and execute correctly, so that webhook payloads are processed as expected.

### Actual behavior:

The bot fails to process webhooks because the stored script does not compile. The compiled field in the database is empty until manually `compiled`

### Server Setup Information:

- Version of Rocket.Chat Server: 7.13.1
- Number of Users: 20
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 1 
- NodeJS Version: v22.16.0
- MongoDB Version:  7.0.15 / wiredTiger (oplog Enabled)

### Additional context

This issue highlights that database-stored scripts may fail to compile automatically if there is a syntax error or missing Babel plugin. Manually compiling the script in the database resolves the issue.

```
Error [BABEL] unknown file: Cannot find module '@babel/plugin-syntax-nullish-coalescing-operator'
While processing: "base$0$0"
```

**Comment by Anurag13075** [comment]
can you assign me?

**Comment by KrishCodesw** [comment]
Hi there ! 
I noticed this is caused by a missing Babel plugin in the build environment.

Since Node v22 supports nullish coalescing natively, we can likely remove the plugin requirement from the Babel config, or simply add @babel/plugin-syntax-nullish-coalescing-operator to the dev dependencies to resolve the module not found error.

I can open a PR to add the dependency if this issue is still open for contribution.

**Comment by 0936y** [comment]
Hi there ,
We are facing a similar issue. New webhooks are not working, and there is no error visible in the Rocket.Chat logs. The incoming webhook message appears empty. However, we found a script processing error in the database.

**rs0 [direct: primary] rocketchat> db.rocketchat_integrations.find({ _id: "ID" }).pretty()**
```
[
  {
    _id: 'ID',
    enabled: false,
    channel: [ '#criticalalerts' ],
    username: 'prometheus',
    name: 'criticalalerts',
    alias: '',
    avatarUrl: '',
    emoji: '',
    scriptEnabled: true,
    script: 'class Script {\n' +
      '    process_incoming_request({\n' +
      '        request\n' +
      '    }) {\n' +
      '        console.log(request.content);\n' +
      '\n' +
      '        var alertColor = "warning";\n' +
      '        if (request.content.status == "resolved") {\n' +
      '            alertColor = "good";\n' +
      '        } else if (request.content.status == "firing") {\n' +
      '            alertColor = "danger";\n' +
      '        }\n' +
      '\n' +
      '        let finFields = [];\n' +
      '        for (i = 0; i < request.content.alerts.length; i++) {\n' +
      '            var endVal = request.content.alerts[i];\n' +
      '            var elem = {\n' +
      '                title: "alertname: " + endVal.labels.alertname,\n' +
      '                value: "*instance:* " + endVal.labels.instance,\n' +
      '                short: false\n' +
      '            };\n' +
      '\n' +
      '            finFields.push(elem);\n' +
      '\n' +
      '            if (!!endVal.annotations.summary) {\n' +
      '                finFields.push({\n' +
      '                    title: "summary",\n' +
      '                    value: endVal.annotations.summary\n' +
      '                });\n' +
      '            }\n' +
      '\n' +
      '            if (!!endVal.annotations.severity) {\n' +
      '                finFields.push({\n' +
      '                    title: "severity",\n' +
      '                    value: endVal.annotations.severity\n' +
      '                });\n' +
      '            }\n' +
      '\n' +
      '            if (!!endVal.annotations.description) {\n' +
      '                finFields.push({\n' +
      '                    title: "description",\n' +
      '                    value: endVal.annotations.description\n' +
      '                });\n' +
      '            }\n' +
      '        }\n' +
      '\n' +
      '        return {\n' +
      '            content: {\n' +
      '                username: "prometheus",\n' +
      '                attachments: [{\n' +
      '                    color: alertColor,\n' +
      '                    title_link: request.content.externalURL,\n' +
      '                    title: "Prometheus notification",\n' +
      '                    fields: finFields\n' +
      '                }]\n' +
      '            }\n' +
      '        };\n' +
      '\n' +
      '        return {\n' +
      '            error: {\n' +
      '                success: false\n' +
      '            }\n' +
      '        };\n' +
      '    }\n' +
      '}',
    type: 'webhook-incoming',
    token: 'TOKEN',
    userId: 'xxx3',
    _createdAt: ISODate('2022-01-19T13:14:44.022Z'),
    _createdBy: { _id: 'User1', username: 'User1' },
    _updatedAt: ISODate('2025-12-15T16:14:54.479Z'),
    _updatedBy: { _id: 'User2', username: 'User2' },
    overrideDestinationChannelEnabled: true,
    scriptError: {
      name: 'Error',
      message: "[BABEL] unknown file: Cannot find module '@babel/plugin-syntax-nullish-coalescing-operator'\n" +
        'Require stack:\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-preset-meteor/proposals.js\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-preset-meteor/index.js\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@meteorjs/babel/options.js\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@meteorjs/babel/index.js\n' +
        '- /app/bundle/programs/server/boot.js\n' +
        '- /app/bundle/main.js (While processing: "base$0$0")',
      stack: "Error: [BABEL] unknown file: Cannot find module '@babel/plugin-syntax-nullish-coalescing-operator'\n" +
        'Require stack:\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-preset-meteor/proposals.js\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-preset-meteor/index.js\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@meteorjs/babel/options.js\n' +
        '- /app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@meteorjs/babel/index.js\n' +
        '- /app/bundle/programs/server/boot.js\n' +
        '- /app/bundle/main.js (While processing: "base$0$0")\n' +
        '    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)\n' +
        '    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)\n' +
        '    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)\n' +
        '    at Function._load (node:internal/modules/cjs/loader:1211:37)\n' +
        '    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n' +
        '    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n' +
        '    at Module.<anonymous> (node:internal/modules/cjs/loader:1487:12)\n' +
        '    at Module.mod.require (/app/bundle/programs/server/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)\n' +
        '    at Module.mod.require (/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)\n' +
        '    at require (node:internal/modules/helpers:135:16)\n' +
        '    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-preset-meteor/proposals.js:2:3)\n' +
        '    at Module.<anonymous> (node:internal/modules/cjs/loader:1730:14)\n' +
        '    at Module.Mp._compile (/tools/static-assets/server/runtime.js:91:21)\n' +
        '    at Object..js (node:internal/modules/cjs/loader:1895:10)\n' +
        '    at Module.<anonymous> (node:internal/modules/cjs/loader:1465:32)\n' +
        '    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)\n' +
        '    at Function._load (node:internal/modules/cjs/loader:1282:12)\n' +
        '    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n' +
        '    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n' +
        '    at Module.<anonymous> (node:internal/modules/cjs/loader:1487:12)\n' +
        '    at Module.mod.require (/app/bundle/programs/server/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)\n' +
        '    at Module.mod.require (/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)\n' +
        '    at require (node:internal/modules/helpers:135:16)\n' +
        '    at module.exports (/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-preset-meteor/index.js:5:10)\n' +
        '    at sync (/app/bundle/programs/server/npm/node_modules/@babel/core/src/gensync-utils/async.ts:31:25)\n' +
        '    at sync (/app/bundle/programs/server/npm/node_modules/gensync/index.js:182:19)\n' +
        '    at /app/bundle/programs/server/npm/node_modules/gensync/index.js:210:24\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at /app/bundle/programs/server/npm/node_modules/@babel/core/src/config/full.ts:274:23\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at Function.<anonymous> (/app/bundle/programs/server/npm/node_modules/@babel/core/src/gensync-utils/async.ts:10:3)\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at evaluateSync (/app/bundle/programs/server/npm/node_modules/gensync/index.js:251:28)\n' +
        '    at Function.sync (/app/bundle/programs/server/npm/node_modules/gensync/index.js:89:14)\n' +
        '    at sync (/app/bundle/programs/server/npm/node_modules/@babel/core/src/gensync-utils/async.ts:83:25)\n' +
        '    at sync (/app/bundle/programs/server/npm/node_modules/gensync/index.js:182:19)\n' +
        '    at onFirstPause (/app/bundle/programs/server/npm/node_modules/gensync/index.js:210:24)\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at cachedFunction (/app/bundle/programs/server/npm/node_modules/@babel/core/src/config/caching.ts:131:34)\n' +
        '    at cachedFunction.next (<anonymous>)\n' +
        '    at loadPresetDescriptor (/app/bundle/programs/server/npm/node_modules/@babel/core/src/config/full.ts:485:12)\n' +
        '    at loadPresetDescriptor.next (<anonymous>)\n' +
        '    at recursePresetDescriptors (/app/bundle/programs/server/npm/node_modules/@babel/core/src/config/full.ts:120:33)\n' +
        '    at recursePresetDescriptors.next (<anonymous>)\n' +
        '    at recursePresetDescriptors (/app/bundle/programs/server/npm/node_modules/@babel/core/src/config/full.ts:159:34)\n' +
        '    at recursePresetDescriptors.next (<anonymous>)\n' +
        '    at /app/bundle/programs/server/npm/node_modules/@babel/core/src/config/full.ts:226:21\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at loadFullConfig (/app/bundle/programs/server/npm/node_modules/@babel/core/src/config/full.ts:168:4)\n' +
        '    at loadFullConfig.next (<anonymous>)'
    },
    avatar: '',
    scriptEngine: 'isolated-vm'
  }
]

```

**Comment by dodaa08** [comment]
I tested this issue and was unable to reproduce the bug.

## Environment:
- **Rocket.Chat Version:** 7.14.0-develop
- **Node.js:** v22.16.0
- **OS:** Fedora
- **Browser:** Microsoft Edge

## Test Results:
Tested both the Prometheus script from the comments above and modern JavaScript syntax (nullish coalescing `??` and optional chaining `?.`). Both legacy and modern scripts compiled and executed successfully.

<img width="548" height="278" alt="Image" src="https://github.com/user-attachments/assets/80eb0a5d-1423-4889-a18c-9617d97c2c66" />

It appears this may have been fixed in recent commits.

**Comment by kevin-aidevlabs** [comment]
I can confirm this is happening in 7.13.2. I didn't dare to touch the database, downgrading to 7.12.2 and saving the scripts in it worked.

**Comment by shiavm006** [comment]
Hi! I'd like to work on this issue
As @KrishCodesw mentioned, since Node v22 supports nullish coalescing natively, we should configure Babel to target the Node version being used. This way Babel won't try to transpile features that are already native.

**Comment by Gummikavalier** [comment]
I tested that this issue still exists in RC 8.0.1.

Edit: Also informed the devs about it.

**Comment by Gummikavalier** [comment]
The devs confirmed that this particular babel-issue is already tasked at their end.

**Comment by unix196** [comment]
Is there any information in which version the integration was fixed?

**Comment by Gummikavalier** [comment]
According to my own notes it would have been RC 8.1.0.

Also these got backports according to the fix itself:
8.0.2
7.13.4

**Comment by unix196** [comment]
Hm, upgrade to 7.13.5, now it says an error when a message comes into RocketChat from GitLab:
```
Error occured while parsing an incoming webhook request. Details attached

Error: 'TypeError: Cannot read properties of undefined (reading 'web_url')', Message: 'Cannot read properties of undefined (reading 'web_url')', Stack: 'TypeError: Cannot read properties of undefined (reading 'web_url') at Script.pushEvent (<isolated-vm>:44:6226) at Script.process_incoming_request (<isolated-vm>:44:929) at process_incoming_request (<isolated-vm>:52:120)'
```
the code is taken from here - https://docs.rocket.chat/docs/gitlab

**Comment by rhodesgarret56-cell** [comment]
From what I can tell, the fix should be included starting around 8.1.0,
with backports to 8.0.x and 7.13.x.

That said, if you’re still seeing issues on 7.13.5, it might be related to
something else or a partial fix. The error you’re getting looks more like a
payload/format issue with the webhook.

Might be worth double-checking the payload against the current docs or
testing with a minimal example.

**Comment by unix196** [comment]
> Hm, upgrade to 7.13.5, now it says an error when a message comes into RocketChat from GitLab:
> 
> ```
> Error occured while parsing an incoming webhook request. Details attached
> 
> Error: 'TypeError: Cannot read properties of undefined (reading 'web_url')', Message: 'Cannot read properties of undefined (reading 'web_url')', Stack: 'TypeError: Cannot read properties of undefined (reading 'web_url') at Script.pushEvent (<isolated-vm>:44:6226) at Script.process_incoming_request (<isolated-vm>:44:929) at process_incoming_request (<isolated-vm>:52:120)'
> ```
> 
> the code is taken from here - https://docs.rocket.chat/docs/gitlab

we upgrade rocketchat to 8.2.1, but the error remains the same :(
