### ISSUE TITLE
No default channel for user created through OAUTH

### ISSUE THREAD

**Issue by fcoppolani** [RocketChat/Rocket.Chat#5376]
Your Rocket.Chat version: 0.48.2

Hi,

we are using OAUTH (with keycloak) and newly created users are not in general channel (but it is set as the default one). Manually created users are OK though. So our new users are "left alone" when logging in rocket.chat, they have to click on "more channels", "general", and then "join".
Is there a workaround ?

Regards,

**Comment by graywolf336** [comment]
@rodrigok Shouldn't this have changed and actually be fixed already via #5152 in v0.49?

**Comment by rodrigok** [comment]
That should be fixed already on version 0.48.0 via this PR https://github.com/RocketChat/Rocket.Chat/pull/5152 since we moved the `joinDefaultChannels` to inside `Accounts.insertUserDoc`.

@fcoppolani Can you help me to reproduce your issue? Can you share your OAuth settings with me privately?

**Comment by fcoppolani** [comment]
Thanks for your reply, I re-checked this is indeed 0.48.2 version. I don't see any parameter joinDefaultChannels in the console admin ? I will check the code about that.
@rodrigok I sent you an email with the settings.

**Comment by neyre** [comment]
I'm experiencing the same issue on 0.48.2. New members created via Oauth (custom provider) don't get added to any default channels.

**Comment by engelgabriel** [comment]
@neyre can you please try with the new version 0.49.0 ?

**Comment by fcoppolani** [comment]
@engelgabriel I tried out the 0.49.0 today and it is still the same.
