### ISSUE TITLE
Remind Me Command

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#659]
I'll admit, I forget things very very quickly. As a result of that, I use the `/remind me` command quite often. Maybe this is a command for Hubot but would be neat to have built into the core.
##

**Comment by rodrigogs** [comment]
How would be the command syntax?

My idea is:

# /remind `<user>` `<when>` ``<message>`\`
* If <user> arg is 'me', it should understand that its a self reminder

* <when> arg could be something like https://github.com/rainder/human-to-cron

* We could wrap <message> with `` to deal with <when> dynamism

# /remind list
Lists all reminders created by the user

# /remind help
Shows help 

What do you think?

**Comment by rodrigok** [comment]
My ideia:

**/remindme** `message`
**/remind** `@user` `message`
**/remind** `list`
**/remind** `remove` `123`

Reminders with date and time could be complex because we need some place to alert user about the reminder.

This looks good for a initial implementation

**Comment by jclabaugh** [comment]
https://github.com/github/hubot-scripts/blob/master/src/scripts/remind.coffee

**Comment by geekgonecrazy** [comment]
We could for sure use that as a reference :)

But wouldn't be able to use it.  Simply because we already have a slashcommand handler in place.

**Comment by graywolf336** [comment]
@jclabaugh That syntax reminds me a lot of Slack's remind me command. Good find

**Comment by rodrigok** [comment]
I liked

**/remind** me to `<message>`
**/remind** `<@user>` to `<message>`

and let time to after?

**Comment by graywolf336** [comment]
I've always used it as:

`/remind me on <date> at <time> to <action>`

But I can see the `<@user>` being useful instead of `me`.

**Comment by curioussavage** [comment]
@rodrigok you might already know this but in response to your comment above about a place to notify the user, in slack the bot just private messages you. I would love this feature.

Also btw, awesome project guys, I remember reading about his project in the meteor forum when it just started, its coming along very well.

**Comment by com-ethode-jables** [comment]
I would love this feature as well.  It's something I use daily with Slack.

Slack's documentation on how this works is available here:  https://get.slack.help/hc/en-us/articles/208423427-Setting-reminders

E.g. `/remind me every Friday to review invoices` or `/remind #super-awesome-project every weekday at 4:30 PM to log project hours for the day`, etc.

**Comment by pierreozoux** [comment]
I don't think this should be a core feature, you can find already a lot of scripts doing this:

https://www.npmjs.com/search?q=hubot+remind

**Comment by geekgonecrazy** [comment]
Yeah... it might be adding un-needed complexities to the core.  Because we'll need to then use some sort of cron type process to keep track of all the reminders.

**Comment by giggio** [comment]
This is a core feature. I would like to be reminded to read later a certain message, for example. The slash command is just one expression of it.

**Comment by 0x6c** [comment]
Pretty nice feature.
As commands are already there.

**Comment by JAndrew77** [comment]
I know for a fact that managers of companies appreciate this feature very much, can assign tasks to their employees and to have feedback of their progress, boss will decide to adopt a free Slack alternatives only if this feature will be implemented. think about it.

**Comment by stepek** [comment]
I'll work on this feature.

**Comment by borisschapira** [comment]
@stepek my hero.

**Comment by lukasreichart** [comment]
@stepek are there any updates from you side?
Just asking, because I would love to see this feature implemented and would be willing to help you out.

**Comment by jszaszvari** [comment]
There are literally hundreds of hubot scripts which do exactly this.. The devs should be working on core features and bug fixes, not reinventing something that is already out there.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close 

... what @jszaszvari said.

Cheers
Thomas

**Comment by timkinnane** [comment]
Added this as a proposal to #10174 - as suggested, it's a solved issue, but might make a good bot building tutorial case.

**Comment by saschafoerster** [comment]
Still missing this feature. And I tried several Hubot-scripts, which did not work.

**Comment by reetp** [comment]
> Still missing this feature. And I tried several Hubot-scripts, which did not work.

https://rocket.chat/docs/getting-support/

I suggest the #bots channel

**Comment by murtaza98** [comment]
Hello All :wave: I'm quite excited to share my new Reminder app over here. It provides a solution to most of the issues mentioned over here. Check out [this doc](https://add-reminders.gitbook.io/docs/) for more info about this app. 

Also, feel free to reach out to me on any below-mentioned channels if you wish to share any feedback or suggestions or even criticism.

Open server of Rocket.Chat: https://open.rocket.chat/direct/murtaza.patrawala
Email: murtaza98.professional@gmail.com
[LinkedIn](https://www.linkedin.com/in/murtaza-patrawala-b17419166/)

**Comment by saschafoerster** [comment]
@murtaza98 Is there a reason, why there is no public source code? 
https://github.com/AddReminders/Reminders-in-RocketChat
