### ISSUE TITLE
Usernames are still being displayed with use real name setting enabled

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#6725]
Rocket.Chat Version: 0.55.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: Docker image

Some people's usernames are still being displayed in the direct messages list, instead of full names with the Use real name setting enabled.

This caused an inconsistent look with a mixture of usernames and full names.

(All users have set their full name)

**Comment by danpospisil** [comment]
We have the same issue - user has full name in the actual chat window, but the header and user lists shows username for the user. @alexbrazier - since you are the author of this, do you have any fix available?

**Comment by alexbrazier** [comment]
Related to #3851 and #6597

**Comment by alexbrazier** [comment]
@danpospisil The names are now loaded using the cache, but for some reason it does not seem to be pushing everything to the client side. I will have a look later today, but @rodrigok will probably have more of an idea what the issue is?

**Comment by Ulrar** [comment]
I had to delete my conversations and re-create them to fix that. Not a huge deal, but losing the history is unfortunate. You do consider that a bug then, should I tell my users to wait before deleting their conversations too ?

**Comment by alexbrazier** [comment]
I'm unable to recreate this locally with a 1000 users, but it is still persistent on our production system, with about 20% of users still showing their username. It also seems to be random which users are just showing the username, and it seem to change at times. (from what I've noticed, it seems to be gradually picking up more names, rather than losing them)

**Comment by mddvul22** [comment]
Has there been any progress on this?  We just turned on the setting to use real names (with our ldap server).  And we have also turned on the ldap setting to sync data.  Still some users show as userids in the sidebar, rather than their full name.  If you chat with a person, their full name shows, though.  ulrar said they had to delete conversations to fix this.  However, for some of these people, I don't have any conversations with them to delete.  Furthermore, I've discovered an odd issue.  "user A" shows up for me, as "userid".  But for another user, "user A" shows up as "full name".  So, it doesn't seem consistent for everybody.

**Comment by mddvul22** [comment]
@alexbrazier I've also noticed this morning that for some users it seems to go back and forth.

**Comment by alexbrazier** [comment]
@mddvul22 we had the same issue, I'm not sure what the problem was, but it seemed to gradually improve over time, until quite quickly it was showing everyones real names. I think its something to do with caching, so potentially clearing the local cache in the browser might fix it.

**Comment by mddvul22** [comment]
I've worked on this much of today.  In our case, (and maybe everybody else's?) is that that we are ldap enabled but we also have "login fallback" set to true.  Because of this, we have some ldap users who should be logging in with their usernames but are logging in with their email addresses.  When they log in with their email address, it uses the local RC backup account, and the ldap sync never happens and so their full name is never displayed.  I've had to go around and work with people to correct this.  

The problem has even compounded because of the following scenarios that have happened in the past:

1. Some users have initially logged into Rocket Chat using ldap account.  Successful.
2. Then, they somewhere along the way, started using their email address to login.
3. Then, some time later, they changed their ldap password.
4. They continued to log into Rocket Chat, though, with their stale local account.
5. So, not only were they not using their username to login, they weren't even using their ldap password, either!

If I'm correct about this, then part of this problem is partially related to the following bugs:
https://github.com/RocketChat/Rocket.Chat/issues/4554
https://github.com/RocketChat/Rocket.Chat/issues/6144

**Comment by Ulrar** [comment]
I can tell you that's not what happened with us as we never used LDAP. But
we haven't had the problem since the initial update so it might be
different I guess

**Comment by localguru** [comment]
same here 0.56.0

**Comment by mddvul22** [comment]
I was able to fix our issue by simply restarting the Rocket Chat services.

**Comment by realakshun** [comment]
How do you enable 'Use real names'?  I cannot find this option.   We are using LDAP auth and also see usernames for all messaging.

**Comment by ggazzo** [comment]
@alexbrazier do you know if the problem persists on new versions? > 0.63.x

**Comment by alexbrazier** [comment]
@ggazzo I would say it is probably fixed now as our server is now working on the latest version.

I'll close it as its been inactive for a while, and if someone does have the issue they can reopen.

**Comment by ggazzo** [comment]
thanks

**Comment by jathan** [comment]
I am having this issue on 0.69.  Random users appear as usernames.  What is interesting is that that the problem behaves differently for different users.  So one user will see Joe and Mary as usernames, but Joe will see Sue and Betty as usernames.  It persists across sessions and browsers/clients.  All the data is there if you select the user profile.  It just happens on the DM list on the left.

**Comment by jschewebbn** [comment]
I'm using the native client on Linux through snap. I have version 2.7.0 and I'm seeing usernames for private conversations rather than real names in the left bar. Inside the chat I see real names.

**Comment by tassoevan** [comment]
@jathan and @jschewebbn: Is it the same problem shown in the video posted at #11913?

**Comment by jschewebbn** [comment]
@tassoevan  yes

**Comment by Crazy-Hopper** [comment]
Sorry, I can't say this issue is fixed as I'm using 0.69.2 (1 instance, oplog enabled, no ldap, all users have real names). I've noticed that showing real name vs username really depends on WHO sent the first message.
If I'm sending the direct message to the user, I see the real name, but the recipient sees the username. Hiding and reopening the room doesn't fix it.

**Comment by piotrkochan** [comment]
Problem still exists, should be reopened

**Comment by tassoevan** [comment]
@piotrkochan We're tracking it in #11913.
