### ISSUE TITLE
Default Selector For Channels Missing

### ISSUE THREAD

**Issue by DanManB** [RocketChat/Rocket.Chat#6777]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.0

The default selector for channels seems to be gone. This is a big issue for my team as we have an announcements channel.

**Comment by k0nsl** [comment]
This put a spook in my wheel as well since I just archived our primary/default channel and now there is no option of making another (new) channel/group the default.

**Comment by Rohlik** [comment]
This was implemented in https://github.com/RocketChat/Rocket.Chat/pull/2290 but now is gone...

**Comment by gregs007** [comment]
Confirmed 0.55.1. 
It's missing from both user UI and admin/rooms UI, see screenshots:

![screen shot 2017-05-06 at 7 40 58 am](https://cloud.githubusercontent.com/assets/1286811/25772071/55ab2b60-3230-11e7-86cc-a10a25b47027.png)
![screen shot 2017-05-06 at 7 40 26 am](https://cloud.githubusercontent.com/assets/1286811/25772072/55b04bd6-3230-11e7-9fe6-9d85a808f5be.png)

**Comment by DanManB** [comment]
So is this going to be fixed or what?

**Comment by indiadamjones** [comment]
Looking for this feature too.  Deleted initial #general channel, so I could recreate a fresh default channel.  Maybe not the best way to tackle that idea, but I didn't want to have to delete all the hubot test messages one by one.  Anyway, perhaps a way to define the default channel in the docker-compose.yml?  Tried to pull 0.55.0 and see if I could spin up, with the feature, but didn't see it.  +1 thanks.  (Next time will just create a scratch channel, and delete that instead, derp)

**Comment by lanrenags** [comment]
I also want this feature this is an showstopper for me

**Comment by gregs007** [comment]
In the meantime, if you need to set a room to default while waiting for this to be fixed (I'm running in ubuntu snap):
`gschwart@rocketchat:~$` sudo /snap/rocketchat-server/current/bin/mongo`
Then in mongo shell:
`rs0:PRIMARY> use parties
switched to db parties
rs0:PRIMARY> db.rocketchat_room.update({"name":"test"},{$set: {"default": true}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
rs0:PRIMARY>'

**Comment by geekgonecrazy** [comment]
This is fixed in 0.56.0 if you're on snap you should now be on that version and the selector already available to you :+1:

**Comment by geekgonecrazy** [comment]
Fixed via: https://github.com/RocketChat/Rocket.Chat/commit/345b4ffe288d51411b6cbc505c2de19e2ffd8320

**Comment by aventrax** [comment]
Sorry but I had this issue on 0.56 too, so I updated to 0.57.2 and the issue is still there.
I have no button to edit the default channel, @geekgonecrazy if the commit fixed the issue editing ChannelSettings.js, I haven't any file named like this on my installation, so.... I do not understand!

**Comment by najtin** [comment]
this is back

![Unbenannt](https://user-images.githubusercontent.com/42641080/72846437-de494880-3ca0-11ea-9f7e-eecd20883002.png)

**Comment by GeorgeGedox** [comment]
This issue is still present. There is no button to make a room default in the current version, why is this closed?

**Comment by najtin** [comment]
this was fixed and then the bug appeared again
last year it definitly worked fine

**Comment by najtin** [comment]
i think its somewhere in https://github.com/RocketChat/Rocket.Chat/commit/c2ed1e325af38f6d4b2eb6a8452fafa29d8f71db but couldnt find iot so far

**Comment by RAurelian** [comment]
> In the meantime, if you need to set a room to default while waiting for this to be fixed (I'm running in ubuntu snap):
> 
> `gschwart@rocketchat:~$ sudo /snap/rocketchat-server/current/bin/mongo `
> 
> Then in mongo shell:
> 
> ```
> rs0:PRIMARY> use parties
> switched to db parties
> rs0:PRIMARY> db.rocketchat_room.update({"name":"test"},{$set: {"default": true}})
> WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
> rs0:PRIMARY>
> ```
> 
> The name of my room in this case is **test**

THANK YOU for the guide - I`m on v2.4.2 (Ubuntu Snap) and there is no way to set the default status of a room from the UI, so this worked.
