### ISSUE TITLE
Inline code formatting not correct for multi-line code

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#9625]
### Description:

![image](https://user-images.githubusercontent.com/179595/35920933-9a806390-0c19-11e8-9546-aae756e505ad.png)

If you select a text in the chat text area (where you write messages) and want to mark it as inline code, it is not taken into account, whether the text that is selected is single-line or multi-line. It only works as expected for single-line text.

### Server Setup Information:

Version of Rocket.Chat Server: 0.61.0
Operating System: Oracle Linux 7
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
DB Replicaset Oplog: Disabled
Node Version: 8.9.4

### Steps to Reproduce:

1. Type multi-line text in chat text area
2. Click on the icon (see image above) to mark text as inline code

### Expected behavior:

Text should be transformed to 

    ```this
    is a multiline
    text```

### Actual behavior:

Text is transformed to

    `this
    is a multiline
    text`

### Relevant logs:

**Comment by rgoerner** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/9581

This seems to be still a open bug? Hm ;(

**Comment by TheRealBecks** [comment]
Yeah, that bug is still open. Also the documentation is not correct as there is a white space in the code tag: https://rocket.chat/docs/contributing/documentation/markdown-styleguide/#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines
Documentation:
\`\` \`
Correct tag:
\`\`\`

**Comment by diegobelotti** [comment]
May be it was fixed fo sure from 4.1 up to 4.8.7.
In every 5.x inline code has moved from
```code
here```
to
`code here`
and multiline is not working

**Comment by cuu508** [comment]
I signed up for a trial Rocket.Chat account, the dashboard shows it's running version 6.22. 

I can enter multi-line preformatted text in the chat box (the back-ticks have to be on separate lines):

![image](https://github.com/RocketChat/Rocket.Chat/assets/661859/09b76698-06d1-4964-a398-abfe4dbc80b6)

I can post multi-line preformatted text via incoming webhooks, in the `text` field:

![image](https://github.com/RocketChat/Rocket.Chat/assets/661859/16c99bf9-1d83-40dc-9b61-5276dfa51bc2)

Posting it in an attachment's `text` or `pretext` field also works:

![image](https://github.com/RocketChat/Rocket.Chat/assets/661859/ea2b6844-efee-4794-9fb5-da3c6f75530d)

Posting it in an attachment's field does not work – it seems to get displayed as inline code:

![image](https://github.com/RocketChat/Rocket.Chat/assets/661859/ee0a3460-fd53-42ee-8bea-0fa042c0f596)

**Comment by MartinSchoeler** [comment]
Today we have separate options for single line and multiline code, I'll be closing this for now, thanks!

**Comment by cuu508** [comment]
@MartinSchoeler  multiline code formatting is still broken in attachment field.

Example webhook payload: 

![image](https://github.com/user-attachments/assets/271dae0c-b4f0-4929-b3b6-183ad91813f8)

Looks OK in the mobile app:

![image](https://github.com/user-attachments/assets/15811309-6e97-4120-a5e8-20152a02ca29)

Broken in the desktop app (all on the same line):

![image](https://github.com/user-attachments/assets/d5941749-dea0-4801-877d-8c55c63ced00)
